DROP INDEX PS_BEN_PROG_PARTIC
/
DROP INDEX PSABEN_PROG_PARTIC
/
CREATE UNIQUE  iNDEX PS_BEN_PROG_PARTIC ON PS_BEN_PROG_PARTIC (EMPLID,
   EMPL_RCD,
   COBRA_EVENT_ID,
   EFFDT DESC) TABLESPACE PSINDEX STORAGE (INITIAL 81920 NEXT 81920
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PS_BEN_PROG_PARTIC NOPARALLEL LOGGING
/
CREATE   INDEX PSABEN_PROG_PARTIC ON PS_BEN_PROG_PARTIC (EMPLID,
   EMPL_RCD,
   EFFDT,
   BENEFIT_PROGRAM) TABLESPACE PSINDEX STORAGE (INITIAL 40000 NEXT
 100000 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL
 NOLOGGING
/
ALTER INDEX PSABEN_PROG_PARTIC NOPARALLEL LOGGING
/
DROP INDEX PS_DIVERS_ETHNIC
/
CREATE UNIQUE  iNDEX PS_DIVERS_ETHNIC ON PS_DIVERS_ETHNIC (EMPLID,
   REG_REGION,
   ETHNIC_GRP_CD) TABLESPACE PSINDEX STORAGE (INITIAL 40000 NEXT
 100000 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL
 NOLOGGING
/
ALTER INDEX PS_DIVERS_ETHNIC NOPARALLEL LOGGING
/
DROP INDEX PSCJOB
/
DROP INDEX PS_JOB
/
DROP INDEX PSAJOB
/
DROP INDEX PSBJOB
/
DROP INDEX PS4JOB
/
DROP INDEX PS5JOB
/
DROP INDEX PS6JOB
/
DROP INDEX PS0JOB
/
DROP INDEX PS1JOB
/
DROP INDEX PS2JOB
/
DROP INDEX PS3JOB
/
CREATE UNIQUE  iNDEX PS_JOB ON PS_JOB (EMPLID,
   EMPL_RCD,
   EFFDT DESC,
   EFFSEQ DESC) TABLESPACE PSINDEX STORAGE (INITIAL 286720 NEXT 286720
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PS_JOB NOPARALLEL LOGGING
/
CREATE   INDEX PS0JOB ON PS_JOB (PER_ORG,
   EMPLID,
   EMPL_RCD,
   EFFDT DESC,
   EFFSEQ DESC) TABLESPACE PSINDEX STORAGE (INITIAL 40000 NEXT 100000
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PS0JOB NOPARALLEL LOGGING
/
CREATE   INDEX PS1JOB ON PS_JOB (DEPTID,
   EMPLID,
   EMPL_RCD,
   EFFDT DESC,
   EFFSEQ DESC) TABLESPACE PSINDEX STORAGE (INITIAL 40000 NEXT 100000
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PS1JOB NOPARALLEL LOGGING
/
CREATE   INDEX PS2JOB ON PS_JOB (JOBCODE,
   EMPLID,
   EMPL_RCD,
   EFFDT DESC,
   EFFSEQ DESC) TABLESPACE PSINDEX STORAGE (INITIAL 40000 NEXT 100000
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PS2JOB NOPARALLEL LOGGING
/
CREATE   INDEX PS3JOB ON PS_JOB (POSITION_NBR,
   EMPLID,
   EMPL_RCD,
   EFFDT DESC,
   EFFSEQ DESC) TABLESPACE PSINDEX STORAGE (INITIAL 40000 NEXT 100000
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PS3JOB NOPARALLEL LOGGING
/
CREATE   INDEX PS4JOB ON PS_JOB (SUPERVISOR_ID,
   EMPLID,
   EMPL_RCD,
   EFFDT DESC,
   EFFSEQ DESC) TABLESPACE PSINDEX STORAGE (INITIAL 40000 NEXT 100000
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PS4JOB NOPARALLEL LOGGING
/
CREATE   INDEX PS5JOB ON PS_JOB (MB_BADGE_NUMBER,
   EMPLID,
   EMPL_RCD,
   EFFDT DESC,
   EFFSEQ DESC) TABLESPACE PSINDEX STORAGE (INITIAL 40000 NEXT 100000
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PS5JOB NOPARALLEL LOGGING
/
CREATE   INDEX PS6JOB ON PS_JOB (MB_INTEGRAL_NUMBER,
   EMPLID,
   EMPL_RCD,
   EFFDT DESC,
   EFFSEQ DESC) TABLESPACE PSINDEX STORAGE (INITIAL 40000 NEXT 100000
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PS6JOB NOPARALLEL LOGGING
/
CREATE   INDEX PSAJOB ON PS_JOB (EMPLID,
   EMPL_RCD,
   EFFDT DESC,
   EFFSEQ DESC,
   DEPTID) TABLESPACE PSINDEX STORAGE (INITIAL 286720 NEXT 286720
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PSAJOB NOPARALLEL LOGGING
/
CREATE   INDEX PSBJOB ON PS_JOB (EMPLID,
   EMPL_RCD,
   EFFDT DESC,
   EFFSEQ DESC,
   EMPL_STATUS,
   MAIN_APPT_NUM_JPN,
   APPT_TYPE) TABLESPACE PSINDEX STORAGE (INITIAL 40000 NEXT 100000
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PSBJOB NOPARALLEL LOGGING
/
CREATE   INDEX PSCJOB ON PS_JOB (REPORTS_TO) TABLESPACE PSINDEX
 STORAGE (INITIAL 40000 NEXT 100000 MAXEXTENTS UNLIMITED PCTINCREASE
 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PSCJOB NOPARALLEL LOGGING
/
DROP INDEX PS1JOBCODE_TBL
/
DROP INDEX PS2JOBCODE_TBL
/
DROP INDEX PSAJOBCODE_TBL
/
DROP INDEX PSBJOBCODE_TBL
/
DROP INDEX PS_JOBCODE_TBL
/
DROP INDEX PS0JOBCODE_TBL
/
CREATE UNIQUE  iNDEX PS_JOBCODE_TBL ON PS_JOBCODE_TBL (SETID,
   JOBCODE,
   EFFDT DESC) TABLESPACE PSINDEX STORAGE (INITIAL 16384 NEXT 16384
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PS_JOBCODE_TBL NOPARALLEL LOGGING
/
CREATE   INDEX PS0JOBCODE_TBL ON PS_JOBCODE_TBL (DESCR,
   SETID,
   JOBCODE,
   EFFDT DESC) TABLESPACE PSINDEX STORAGE (INITIAL 40000 NEXT 100000
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PS0JOBCODE_TBL NOPARALLEL LOGGING
/
CREATE   INDEX PS1JOBCODE_TBL ON PS_JOBCODE_TBL (GVT_OCC_SERIES,
   SETID,
   JOBCODE,
   EFFDT DESC) TABLESPACE PSINDEX STORAGE (INITIAL 40000 NEXT 100000
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PS1JOBCODE_TBL NOPARALLEL LOGGING
/
CREATE   INDEX PS2JOBCODE_TBL ON PS_JOBCODE_TBL (GVT_OFFICIAL_DESCR,
   SETID,
   JOBCODE,
   EFFDT DESC) TABLESPACE PSINDEX STORAGE (INITIAL 40000 NEXT 100000
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PS2JOBCODE_TBL NOPARALLEL LOGGING
/
CREATE   INDEX PSAJOBCODE_TBL ON PS_JOBCODE_TBL (JOB_FAMILY)
 TABLESPACE PSINDEX STORAGE (INITIAL 40000 NEXT 100000 MAXEXTENTS
 UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PSAJOBCODE_TBL NOPARALLEL LOGGING
/
CREATE   INDEX PSBJOBCODE_TBL ON PS_JOBCODE_TBL (JOB_PROFILE_ID)
 TABLESPACE PSINDEX STORAGE (INITIAL 40000 NEXT 100000 MAXEXTENTS
 UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PSBJOBCODE_TBL NOPARALLEL LOGGING
/
DROP INDEX PS_NAMES
/
DROP INDEX PS0NAMES
/
DROP INDEX PS1NAMES
/
DROP INDEX PS2NAMES
/
DROP INDEX PS3NAMES
/
DROP INDEX PS4NAMES
/
DROP INDEX PS5NAMES
/
DROP INDEX PSANAMES
/
DROP INDEX PSBNAMES
/
CREATE UNIQUE  iNDEX PS_NAMES ON PS_NAMES (EMPLID,
   NAME_TYPE,
   EFFDT DESC) TABLESPACE PSINDEX STORAGE (INITIAL 16384 NEXT 16384
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PS_NAMES NOPARALLEL LOGGING
/
CREATE   INDEX PS0NAMES ON PS_NAMES (NAME,
   EMPLID,
   NAME_TYPE,
   EFFDT DESC) TABLESPACE PSINDEX STORAGE (INITIAL 40000 NEXT 100000
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PS0NAMES NOPARALLEL LOGGING
/
CREATE   INDEX PS1NAMES ON PS_NAMES (LAST_NAME_SRCH,
   EMPLID,
   NAME_TYPE,
   EFFDT DESC) TABLESPACE PSINDEX STORAGE (INITIAL 40000 NEXT 100000
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PS1NAMES NOPARALLEL LOGGING
/
CREATE   INDEX PS2NAMES ON PS_NAMES (FIRST_NAME_SRCH,
   EMPLID,
   NAME_TYPE,
   EFFDT DESC) TABLESPACE PSINDEX STORAGE (INITIAL 40000 NEXT 100000
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PS2NAMES NOPARALLEL LOGGING
/
CREATE   INDEX PS3NAMES ON PS_NAMES (SECOND_LAST_SRCH,
   EMPLID,
   NAME_TYPE,
   EFFDT DESC) TABLESPACE PSINDEX STORAGE (INITIAL 40000 NEXT 100000
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PS3NAMES NOPARALLEL LOGGING
/
CREATE   INDEX PS4NAMES ON PS_NAMES (NAME_AC,
   EMPLID,
   NAME_TYPE,
   EFFDT DESC) TABLESPACE PSINDEX STORAGE (INITIAL 40000 NEXT 100000
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PS4NAMES NOPARALLEL LOGGING
/
CREATE   INDEX PS5NAMES ON PS_NAMES (NAME_DISPLAY_SRCH,
   EMPLID,
   NAME_TYPE,
   EFFDT DESC) TABLESPACE PSINDEX STORAGE (INITIAL 40000 NEXT 100000
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PS5NAMES NOPARALLEL LOGGING
/
CREATE   INDEX PSANAMES ON PS_NAMES (LAST_NAME_SRCH,
   NAME_TYPE,
   EFFDT,
   EMPLID) TABLESPACE PSINDEX STORAGE (INITIAL 40000 NEXT 100000
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PSANAMES NOPARALLEL LOGGING
/
CREATE   INDEX PSBNAMES ON PS_NAMES (NAME_DISPLAY_SRCH,
   NAME_TYPE,
   EFFDT,
   EMPLID) TABLESPACE PSINDEX STORAGE (INITIAL 40000 NEXT 100000
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PSBNAMES NOPARALLEL LOGGING
/
DROP INDEX PS_PER_ORG_ASGN
/
DROP INDEX PS0PER_ORG_ASGN
/
DROP INDEX PS1PER_ORG_ASGN
/
DROP INDEX PSAPER_ORG_ASGN
/
CREATE UNIQUE  iNDEX PS_PER_ORG_ASGN ON PS_PER_ORG_ASGN (EMPLID,
   EMPL_RCD) TABLESPACE PSINDEX STORAGE (INITIAL 40000 NEXT 100000
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PS_PER_ORG_ASGN NOPARALLEL LOGGING
/
CREATE   INDEX PS0PER_ORG_ASGN ON PS_PER_ORG_ASGN (PER_ORG,
   EMPLID,
   EMPL_RCD) TABLESPACE PSINDEX STORAGE (INITIAL 40000 NEXT 100000
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PS0PER_ORG_ASGN NOPARALLEL LOGGING
/
CREATE   INDEX PS1PER_ORG_ASGN ON PS_PER_ORG_ASGN (ORG_INSTANCE_ERN,
   EMPLID,
   EMPL_RCD) TABLESPACE PSINDEX STORAGE (INITIAL 40000 NEXT 100000
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PS1PER_ORG_ASGN NOPARALLEL LOGGING
/
CREATE   INDEX PSAPER_ORG_ASGN ON PS_PER_ORG_ASGN (EMPLID,
   BENEFIT_RCD_NBR,
   EMPL_RCD) TABLESPACE PSINDEX STORAGE (INITIAL 40000 NEXT 100000
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PSAPER_ORG_ASGN NOPARALLEL LOGGING
/
DROP INDEX PS_PER_ORG_INST
/
DROP INDEX PS0PER_ORG_INST
/
CREATE UNIQUE  iNDEX PS_PER_ORG_INST ON PS_PER_ORG_INST (EMPLID,
   ORG_INSTANCE_ERN) TABLESPACE PSINDEX STORAGE (INITIAL 40000 NEXT
 100000 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL
 NOLOGGING
/
ALTER INDEX PS_PER_ORG_INST NOPARALLEL LOGGING
/
CREATE   INDEX PS0PER_ORG_INST ON PS_PER_ORG_INST (PER_ORG,
   EMPLID,
   ORG_INSTANCE_ERN) TABLESPACE PSINDEX STORAGE (INITIAL 40000 NEXT
 100000 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL
 NOLOGGING
/
ALTER INDEX PS0PER_ORG_INST NOPARALLEL LOGGING
/
DROP INDEX PS_POSITION_DATA
/
DROP INDEX PS0POSITION_DATA
/
DROP INDEX PS1POSITION_DATA
/
DROP INDEX PS2POSITION_DATA
/
DROP INDEX PS3POSITION_DATA
/
DROP INDEX PS4POSITION_DATA
/
DROP INDEX PS5POSITION_DATA
/
DROP INDEX PS6POSITION_DATA
/
DROP INDEX PSAPOSITION_DATA
/
DROP INDEX PSBPOSITION_DATA
/
CREATE UNIQUE  iNDEX PS_POSITION_DATA ON PS_POSITION_DATA
 (POSITION_NBR,
   EFFDT DESC) TABLESPACE PSINDEX STORAGE (INITIAL 16384 NEXT 16384
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PS_POSITION_DATA NOPARALLEL LOGGING
/
CREATE   INDEX PS0POSITION_DATA ON PS_POSITION_DATA (DESCR,
   POSITION_NBR,
   EFFDT DESC) TABLESPACE PSINDEX STORAGE (INITIAL 40000 NEXT 100000
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PS0POSITION_DATA NOPARALLEL LOGGING
/
CREATE   INDEX PS1POSITION_DATA ON PS_POSITION_DATA (BUSINESS_UNIT,
   POSITION_NBR,
   EFFDT DESC) TABLESPACE PSINDEX STORAGE (INITIAL 40000 NEXT 100000
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PS1POSITION_DATA NOPARALLEL LOGGING
/
CREATE   INDEX PS2POSITION_DATA ON PS_POSITION_DATA (DEPTID,
   POSITION_NBR,
   EFFDT DESC) TABLESPACE PSINDEX STORAGE (INITIAL 40000 NEXT 100000
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PS2POSITION_DATA NOPARALLEL LOGGING
/
CREATE   INDEX PS3POSITION_DATA ON PS_POSITION_DATA (JOBCODE,
   POSITION_NBR,
   EFFDT DESC) TABLESPACE PSINDEX STORAGE (INITIAL 40000 NEXT 100000
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PS3POSITION_DATA NOPARALLEL LOGGING
/
CREATE   INDEX PS4POSITION_DATA ON PS_POSITION_DATA (POSN_STATUS,
   POSITION_NBR,
   EFFDT DESC) TABLESPACE PSINDEX STORAGE (INITIAL 40000 NEXT 100000
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PS4POSITION_DATA NOPARALLEL LOGGING
/
CREATE   INDEX PS5POSITION_DATA ON PS_POSITION_DATA (JOB_SHARE,
   POSITION_NBR,
   EFFDT DESC) TABLESPACE PSINDEX STORAGE (INITIAL 40000 NEXT 100000
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PS5POSITION_DATA NOPARALLEL LOGGING
/
CREATE   INDEX PS6POSITION_DATA ON PS_POSITION_DATA (REPORTS_TO,
   POSITION_NBR,
   EFFDT DESC) TABLESPACE PSINDEX STORAGE (INITIAL 40000 NEXT 100000
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PS6POSITION_DATA NOPARALLEL LOGGING
/
CREATE   INDEX PSAPOSITION_DATA ON PS_POSITION_DATA (ORGCODE,
   POSITION_NBR,
   EFFDT DESC,
   DESCR,
   DEPTID,
   JOBCODE,
   POSN_STATUS,
   REPORTS_TO,
   ORGCODE_FLAG) TABLESPACE PSINDEX STORAGE (INITIAL 32768 NEXT 32768
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PSAPOSITION_DATA NOPARALLEL LOGGING
/
CREATE   INDEX PSBPOSITION_DATA ON PS_POSITION_DATA (ORGCODE_FLAG,
   POSITION_NBR,
   EFFDT DESC,
   DESCR,
   DEPTID,
   JOBCODE,
   POSN_STATUS,
   REPORTS_TO) TABLESPACE PSINDEX STORAGE (INITIAL 32768 NEXT 32768
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PSBPOSITION_DATA NOPARALLEL LOGGING
/
DROP INDEX PS_SAL_GRADE_TBL
/
DROP INDEX PS0SAL_GRADE_TBL
/
CREATE UNIQUE  iNDEX PS_SAL_GRADE_TBL ON PS_SAL_GRADE_TBL (SETID,
   SAL_ADMIN_PLAN,
   GRADE,
   EFFDT DESC) TABLESPACE PSINDEX STORAGE (INITIAL 16384 NEXT 16384
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PS_SAL_GRADE_TBL NOPARALLEL LOGGING
/
CREATE   INDEX PS0SAL_GRADE_TBL ON PS_SAL_GRADE_TBL (DESCR,
   SETID,
   SAL_ADMIN_PLAN,
   GRADE,
   EFFDT DESC) TABLESPACE PSINDEX STORAGE (INITIAL 40000 NEXT 100000
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PS0SAL_GRADE_TBL NOPARALLEL LOGGING
/
DROP INDEX PS_UNION_TBL
/
DROP INDEX PS0UNION_TBL
/
CREATE UNIQUE  iNDEX PS_UNION_TBL ON PS_UNION_TBL (UNION_CD,
   EFFDT DESC) TABLESPACE PSINDEX STORAGE (INITIAL 16384 NEXT 16384
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PS_UNION_TBL NOPARALLEL LOGGING
/
CREATE   INDEX PS0UNION_TBL ON PS_UNION_TBL (DESCR,
   UNION_CD,
   EFFDT DESC) TABLESPACE PSINDEX STORAGE (INITIAL 16384 NEXT 16384
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PS0UNION_TBL NOPARALLEL LOGGING
/
DROP INDEX PS_PERSONAL_DATA
/
DROP INDEX PS0PERSONAL_DATA
/
DROP INDEX PS1PERSONAL_DATA
/
DROP INDEX PS2PERSONAL_DATA
/
CREATE UNIQUE  iNDEX PS_PERSONAL_DATA ON PS_PERSONAL_DATA (EMPLID)
 TABLESPACE PSINDEX STORAGE (INITIAL 40000 NEXT 100000 MAXEXTENTS
 UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PS_PERSONAL_DATA NOPARALLEL LOGGING
/
CREATE   INDEX PS0PERSONAL_DATA ON PS_PERSONAL_DATA (NAME,
   EMPLID) TABLESPACE PSINDEX STORAGE (INITIAL 40000 NEXT 100000
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PS0PERSONAL_DATA NOPARALLEL LOGGING
/
CREATE   INDEX PS1PERSONAL_DATA ON PS_PERSONAL_DATA (LAST_NAME_SRCH,
   EMPLID) TABLESPACE PSINDEX STORAGE (INITIAL 40000 NEXT 100000
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PS1PERSONAL_DATA NOPARALLEL LOGGING
/
CREATE   INDEX PS2PERSONAL_DATA ON PS_PERSONAL_DATA (CAMPUS_ID,
   EMPLID) TABLESPACE PSINDEX STORAGE (INITIAL 40000 NEXT 100000
 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL NOLOGGING
/
ALTER INDEX PS2PERSONAL_DATA NOPARALLEL LOGGING
/
