
 SELECT 'SALA' 
 , A.NATIONAL_ID 
 , B.ERNCD_REG_HRS 
 , B.REG_HRS 
 , B.CHECK_DT 
 , B.REG_PAY 
 , C.PAY_END_DT 
-- , (CASE A.PAYMENT_TYPE WHEN 'E' THEN %DateAdd(C.PAY_END_DT, -13) WHEN 'M' THEN %DateAdd(C.PAY_END_DT, -13) WHEN 'W' THEN %DateAdd(C.PAY_END_DT, -6) ELSE %DateAdd(C.PAY_END_DT, -6) END) 
 , C.PAY_END_DT 
 , A.HOURLY_RT 
 , 0 
 , B.PAYCHECK_NBR 
  FROM PS_MB_RET_EMPL A 
  , PS_MB_PAY_EARNINGS B 
  , PS_MB_RET_HEAD C 
 WHERE A.EMPLID = B.EMPLID 
   AND B.PAY_END_DT = C.PAY_END_DT 
   AND A.MB_PAYCHECK_NBR = B.PAYCHECK_NBR



 SELECT 'CONT' 
 , A.NATIONAL_ID 
 , B.DEDCD 
 , B.DED_CUR 
 , A.CHECK_DT 
 , C.PAY_END_DT 
-- , (CASE A.PAYMENT_TYPE WHEN 'E' THEN %DateAdd(C.PAY_END_DT, -13) WHEN 'M' THEN %DateAdd(C.PAY_END_DT, -13) WHEN 'W' THEN %DateAdd(C.PAY_END_DT, -6) ELSE %DateAdd(C.PAY_END_DT, -6) END) 
 , C.PAY_END_DT 
 , A.MB_PAYCHECK_NBR 
  FROM PS_MB_RET_EMPL A 
  , PS_MB_PAY_DED B 
  , PS_MB_RET_HEAD C 
 WHERE A.EMPLID = B.EMPLID 
   AND B.PAY_END_DT = C.PAY_END_DT 
   AND B.DEDCD = '005' 
   AND B.DED_CLASS = 'B' 
   AND A.MB_PAYCHECK_NBR = B.PAYCHECK_NBR
