--Set current schema = 'PSFNPRD'

------------------ Below is the 1st SQL I used., thi had some issues and then went for the 2nd sql below.
SELECT E.DEPTID DEPTID 
 , E.DESCR DESCR 
 , C.INV_ITEM_ID INV_ITEM_ID 
 , C.DESCR ITEM_DESC 
 , A.TRANSACTION_GROUP TRANSACTION_GROUP 
 , A.ACCOUNTING_DT ACCOUNTING_DT 
 , SUM(A.MONETARY_AMOUNT) MONETARY_AMOUNT 
 , SUM(CASE WHEN A.TRANSACTION_GROUP = '030' THEN A.MONETARY_AMOUNT ELSE 0 END) USAGE_AND_SHIPMENTS 
 , SUM(CASE WHEN A.TRANSACTION_GROUP = '041' THEN A.MONETARY_AMOUNT ELSE 0 END) CYCLE_COUNT_ADJUSTMENTS 
 , SUM(CASE WHEN A.TRANSACTION_GROUP = '050' THEN A.MONETARY_AMOUNT ELSE 0 END) USER_ADJUSTMENTS 
 , SUM(CASE WHEN A.TRANSACTION_GROUP = '051' THEN A.MONETARY_AMOUNT ELSE 0 END) INVENTORY_SCRAP 
 , SUM(CASE WHEN A.TRANSACTION_GROUP NOT IN ('030' 
 , '041' 
 , '050' 
 , '051') THEN A.MONETARY_AMOUNT ELSE 0 END) OTHER_TRANSACTIONS 
 , MAX(B.QTY) QTY 
 , F.OPRID 
 , F.RUN_CNTL_ID 
 , F.FROM_DATE 
 , F.THRU_DATE 
  FROM PS_CM_ACCTG_LINE A 
  , PS_TRANSACTION_INV B 
  , PS_MASTER_ITEM_TBL C 
  , ps_dept_tbl_eff_vw E 
  , PS_MB_RUNCTL_IN F 
  , PS_MB_RUNCTL_IN02 G 
 WHERE A.ACCOUNTING_DT BETWEEN F.FROM_DATE AND F.THRU_DATE 
   AND A.DEPTID = G.DEPTID 
   AND F.OPRID = G.OPRID 
   AND F.RUN_CNTL_ID = G.RUN_CNTL_ID 
   AND A.ACCOUNT NOT IN ('1510000' , '1520000' , '1590495') 
   AND A.BUSINESS_UNIT = B.BUSINESS_UNIT 
   AND A.INV_ITEM_ID = B.INV_ITEM_ID 
   AND A.DT_TIMESTAMP = B.DT_TIMESTAMP 
   AND A.SEQ_NBR = B.SEQ_NBR 
   AND A.INV_ITEM_ID = C.INV_ITEM_ID 
   AND A.DEPTID = E.DEPTID 
   AND A.FUND_CODE = '05' 
   AND C.SETID = 'SHARE' 
  GROUP BY C.INV_ITEM_ID , C.DESCR , E.DEPTID , E.DESCR , A.ACCOUNTING_DT , A.TRANSACTION_GROUP , F.OPRID , F.RUN_CNTL_ID , F.FROM_DATE , F.THRU_DATE
  


-------------------------------------------------------------------------
------------------------------ 2 ----------------------------------------
-------------------------------------------------------------------------

SELECT E.DEPTID DEPTID 
 , E.DESCR DESCR 
 , C.INV_ITEM_ID INV_ITEM_ID 
 , C.DESCR ITEM_DESC 
 , A.TRANSACTION_GROUP TRANSACTION_GROUP 
 , SUM(A.MONETARY_AMOUNT) MONETARY_AMOUNT 
 , SUM(A.USAGE_AND_SHIPMENTS) USAGE_AND_SHIPMENTS 
 , SUM(A.CYCLE_COUNT_ADJUSTMENTS) CYCLE_COUNT_ADJUSTMENTS 
 , SUM(A.USER_ADJUSTMENTS) USER_ADJUSTMENTS 
 , SUM(A.INVENTORY_SCRAP) INVENTORY_SCRAP 
 , SUM(A.OTHER_TRANSACTIONS) OTHER_TRANSACTIONS 
 , SUM(CASE 
         WHEN A.TRANSACTION_GROUP = '010' THEN B.QTY * -1 
	     WHEN A.TRANSACTION_GROUP = '020' THEN B.QTY * -1 
	     WHEN A.TRANSACTION_GROUP = '022' THEN B.QTY * -1 
	     WHEN A.TRANSACTION_GROUP = '024' THEN B.QTY * -1 
	     WHEN A.TRANSACTION_GROUP = '041' AND A.ADJUST_TYPE = ' ' THEN B.QTY * -1
         WHEN A.TRANSACTION_GROUP = '041' AND A.ADJUST_TYPE = 'D' THEN B.QTY * -1 
         WHEN A.TRANSACTION_GROUP = '041' AND A.ADJUST_TYPE = 'I' THEN B.QTY * -1 
	     WHEN A.TRANSACTION_GROUP = '042' THEN 0 
	     WHEN A.TRANSACTION_GROUP = '050' AND A.ADJUST_TYPE = 'I' THEN B.QTY * -1 
         WHEN A.TRANSACTION_GROUP = '060' THEN 0 
         ELSE
         B.QTY
       END) QTY 
   , A.OPRID 
   , A.RUN_CNTL_ID 
   , A.FROM_DATE 
   , A.THRU_DATE 
  FROM ( 
 SELECT IA.BUSINESS_UNIT BUSINESS_UNIT 
 , IA.INV_ITEM_ID INV_ITEM_ID 
 , IA.DEPTID DEPTID 
 , IA.dt_timestamp dt_timestamp 
 , IA.seq_nbr seq_nbr 
 , IA.ADJUST_TYPE ADJUST_TYPE 
 , IA.TRANSACTION_GROUP TRANSACTION_GROUP 
 , SUM(IA.MONETARY_AMOUNT) MONETARY_AMOUNT 
 , SUM(CASE WHEN IA.TRANSACTION_GROUP = '030' THEN IA.MONETARY_AMOUNT ELSE 0 END) USAGE_AND_SHIPMENTS 
 , SUM(CASE WHEN IA.TRANSACTION_GROUP = '041' THEN IA.MONETARY_AMOUNT ELSE 0 END) CYCLE_COUNT_ADJUSTMENTS 
 , SUM(CASE WHEN IA.TRANSACTION_GROUP = '050' THEN IA.MONETARY_AMOUNT ELSE 0 END) USER_ADJUSTMENTS 
 , SUM(CASE WHEN IA.TRANSACTION_GROUP = '051' THEN IA.MONETARY_AMOUNT ELSE 0 END) INVENTORY_SCRAP 
 , SUM(CASE WHEN IA.TRANSACTION_GROUP NOT IN ('030' 
 , '041' 
 , '050' 
 , '051') THEN IA.MONETARY_AMOUNT ELSE 0 END) OTHER_TRANSACTIONS 
 , F.OPRID OPRID 
 , F.RUN_CNTL_ID RUN_CNTL_ID 
 , F.FROM_DATE FROM_DATE 
 , F.THRU_DATE THRU_DATE 
  FROM PS_CM_ACCTG_LINE IA 
  , PS_MB_RUNCTL_IN F 
  , PS_MB_RUNCTL_IN02 G 
 		  WHERE IA.ACCOUNTING_DT BETWEEN '2011-08-27' AND '2011-09-02'--	   F.FROM_DATE AND F.THRU_DATE  	--
		    AND IA.DEPTID = '225016'-- G.DEPTID --
		    AND F.OPRID = 'MBBATCH'-- G.OPRID --
		    AND F.RUN_CNTL_ID = 'MBINOP02_225016'-- G.RUN_CNTL_ID --
		    AND IA.FUND_CODE = '05'  
		    AND IA.ACCOUNT NOT IN ('1510000' , '1520000' , '1590495')
  GROUP BY IA.BUSINESS_UNIT , IA.INV_ITEM_ID , IA.DEPTID , IA.dt_timestamp , IA.seq_nbr , IA.ADJUST_TYPE , IA.TRANSACTION_GROUP , F.OPRID , F.RUN_CNTL_ID , F.FROM_DATE , F.THRU_DATE ) A , PS_TRANSACTION_INV B , PS_MASTER_ITEM_TBL C , PS_DEPT_TBL_EFF_VW E 
 WHERE A.BUSINESS_UNIT = B.BUSINESS_UNIT 
   AND A.INV_ITEM_ID = B.INV_ITEM_ID 
   AND A.DT_TIMESTAMP = B.DT_TIMESTAMP 
   AND A.SEQ_NBR = B.SEQ_NBR 
   AND A.INV_ITEM_ID = C.INV_ITEM_ID 
   AND A.DEPTID = E.DEPTID 
   AND C.SETID = 'SHARE' 
  GROUP BY C.INV_ITEM_ID , C.DESCR ,E.DEPTID , E.DESCR, A.OPRID , A.RUN_CNTL_ID , A.FROM_DATE , A.THRU_DATE , A.TRANSACTION_GROUP

SELECT E.DEPTID DEPTID 
 , E.DESCR DESCR 
 , C.INV_ITEM_ID INV_ITEM_ID 
 , C.DESCR ITEM_DESC
 , A.TRANSACTION_GROUP TRANSACTION_GROUP
 --, A.ACCOUNTING_DT 
 , sum(A.MONETARY_AMOUNT) MONETARY_AMOUNT 
 , sum(A.USAGE_AND_SHIPMENTS) USAGE_AND_SHIPMENTS 
 , sum(A.CYCLE_COUNT_ADJUSTMENTS) CYCLE_COUNT_ADJUSTMENTS 
 , sum(A.USER_ADJUSTMENTS) USER_ADJUSTMENTS 
 , sum(A.INVENTORY_SCRAP) INVENTORY_SCRAP 
 , sum(A.OTHER_TRANSACTIONS) OTHER_TRANSACTIONS 
 , SUM(CASE 
         WHEN A.TRANSACTION_GROUP = '010' THEN B.QTY * -1 
	     WHEN A.TRANSACTION_GROUP = '020' THEN B.QTY * -1 
	     WHEN A.TRANSACTION_GROUP = '022' THEN B.QTY * -1 
	     WHEN A.TRANSACTION_GROUP = '024' THEN B.QTY * -1 
	     WHEN A.TRANSACTION_GROUP = '041' AND A.ADJUST_TYPE = ' ' THEN B.QTY * -1
         WHEN A.TRANSACTION_GROUP = '041' AND A.ADJUST_TYPE = 'D' THEN B.QTY * -1 
         WHEN A.TRANSACTION_GROUP = '041' AND A.ADJUST_TYPE = 'I' THEN B.QTY * -1 
	     WHEN A.TRANSACTION_GROUP = '042' THEN 0 
	     WHEN A.TRANSACTION_GROUP = '050' AND A.ADJUST_TYPE = 'I' THEN B.QTY * -1 
         WHEN A.TRANSACTION_GROUP = '060' THEN 0 
         ELSE
         B.QTY
       END) QTY 
 , A.OPRID 
 , A.RUN_CNTL_ID 
 , A.FROM_DATE 
 , A.THRU_DATE 
  FROM (
          SELECT IA.BUSINESS_UNIT BUSINESS_UNIT
             , IA.INV_ITEM_ID INV_ITEM_ID
             , IA.DEPTID DEPTID
             , IA.dt_timestamp dt_timestamp
             , IA.seq_nbr seq_nbr
             , IA.ADJUST_TYPE ADJUST_TYPE
             , IA.TRANSACTION_GROUP TRANSACTION_GROUP
  --           , IA.ACCOUNTING_DT ACCOUNTING_DT 
             , SUM(IA.MONETARY_AMOUNT) MONETARY_AMOUNT
			 , SUM(CASE WHEN IA.TRANSACTION_GROUP = '030' THEN IA.MONETARY_AMOUNT ELSE 0 END) USAGE_AND_SHIPMENTS 
			 , SUM(CASE WHEN IA.TRANSACTION_GROUP = '041' THEN IA.MONETARY_AMOUNT ELSE 0 END) CYCLE_COUNT_ADJUSTMENTS 
			 , SUM(CASE WHEN IA.TRANSACTION_GROUP = '050' THEN IA.MONETARY_AMOUNT ELSE 0 END) USER_ADJUSTMENTS 
		     , SUM(CASE WHEN IA.TRANSACTION_GROUP = '051' THEN IA.MONETARY_AMOUNT ELSE 0 END) INVENTORY_SCRAP
		     , SUM(CASE WHEN IA.TRANSACTION_GROUP NOT IN ('030', '041', '050', '051') THEN IA.MONETARY_AMOUNT ELSE 0 END) OTHER_TRANSACTIONS
             , F.OPRID OPRID
             , F.RUN_CNTL_ID RUN_CNTL_ID
             , F.FROM_DATE FROM_DATE
             , F.THRU_DATE THRU_DATE		                    
		  FROM PS_CM_ACCTG_LINE IA
		     , PS_MB_RUNCTL_IN F 
             , PS_MB_RUNCTL_IN02 G  
 		  WHERE IA.ACCOUNTING_DT BETWEEN '2011-08-27' AND '2011-09-02'--	   F.FROM_DATE AND F.THRU_DATE  	--
		    AND IA.DEPTID = '225016'-- G.DEPTID --
		    AND F.OPRID = 'MBBATCH'-- G.OPRID --
		    AND F.RUN_CNTL_ID = 'MBINOP02_225016'-- G.RUN_CNTL_ID --
		    AND IA.FUND_CODE = '05'  
		    AND IA.ACCOUNT NOT IN ('1510000' , '1520000' , '1590495')
		  GROUP BY IA.BUSINESS_UNIT
                 , IA.INV_ITEM_ID
                 , IA.DEPTID
             	 , IA.dt_timestamp
                 , IA.seq_nbr
                 , IA.ADJUST_TYPE
                 , IA.TRANSACTION_GROUP                 
    --        	 , IA.ACCOUNTING_DT                         
	             , F.OPRID
    	         , F.RUN_CNTL_ID 
        	     , F.FROM_DATE 
            	 , F.THRU_DATE                         
       ) A
  , PS_TRANSACTION_INV B 
  , PS_MASTER_ITEM_TBL C 
  , PS_DEPT_TBL_EFF_VW E 
 WHERE A.BUSINESS_UNIT = B.BUSINESS_UNIT 
   AND A.INV_ITEM_ID = B.INV_ITEM_ID 
   AND A.DT_TIMESTAMP = B.DT_TIMESTAMP 
   AND A.SEQ_NBR = B.SEQ_NBR 
   AND A.INV_ITEM_ID = C.INV_ITEM_ID 
   AND A.DEPTID = E.DEPTID 
   AND C.SETID = 'SHARE' 
 GROUP BY C.INV_ITEM_ID , C.DESCR ,E.DEPTID , E.DESCR, A.TRANSACTION_GROUP
 --, A.ACCOUNTING_DT
 , A.OPRID , A.RUN_CNTL_ID , A.FROM_DATE , A.THRU_DATE

-------------------------------------------------------------------------
---------------------------------END 2-----------------------------------
-------------------------------------------------------------------------


select * from PS_TRANSACTION_INV 
where BUSINESS_UNIT = 'BS012'
and INV_ITEM_ID = '02690379'
and DT_TIMESTAMP between '2011-08-29-10.43.36.000000' and '2011-09-02-12.52.32.326803'
--and SEQ_NBR = 1



select 1, BUSINESS_UNIT, INV_ITEM_ID, DT_TIMESTAMP, SEQ_NBR, '', '',QTY--, monetary_amount 
from PS_TRANSACTION_INV 
where BUSINESS_UNIT = 'BS012'
and INV_ITEM_ID = '02694038'
and DT_TIMESTAMP between '2011-08-29-10.43.36.000000' and '2011-09-02-12.52.32.326803'

union all
   
select 2, BUSINESS_UNIT, INV_ITEM_ID, DT_TIMESTAMP, SEQ_NBR, TRANSACTION_GROUP, ADJUST_TYPE, monetary_amount
from PS_CM_ACCTG_LINE 
where BUSINESS_UNIT = 'BS012'
and INV_ITEM_ID = '02037138'  
and ACCOUNTING_DT BETWEEN '2011-08-27' AND '2011-09-02'
and ACCOUNT NOT IN ('1510000' , '1520000' , '1590495')
AND FUND_CODE = '05'






select 1, BUSINESS_UNIT, INV_ITEM_ID, DT_TIMESTAMP, SEQ_NBR, '' TRANSACTION_GROUP, '' ADJUST_TYPE,QTY--, monetary_amount 
from PS_TRANSACTION_INV 
where 1=1--BUSINESS_UNIT = 'BS012'
and INV_ITEM_ID = '02690592'
and DT_TIMESTAMP between '2011-04-02-00.00.00.000000' and '2011-04-08-00.00.00.000000'

union all
   
select 2, BUSINESS_UNIT, INV_ITEM_ID, DT_TIMESTAMP, SEQ_NBR, TRANSACTION_GROUP, ADJUST_TYPE, monetary_amount
from PS_CM_ACCTG_LINE 
where 1=1--BUSINESS_UNIT = 'BS012'
and INV_ITEM_ID = '02690592'  
and ACCOUNTING_DT BETWEEN '2011-04-02' AND '2011-04-08'
and ACCOUNT NOT IN ('1510000' , '1520000' , '1590495')
AND FUND_CODE = '05'




order by DT_TIMESTAMP

select *
from PS_CM_ACCTG_LINE 
where INV_ITEM_ID = '02690379'  
and ACCOUNTING_DT BETWEEN '2011-08-27' AND '2011-09-02'
and ACCOUNT NOT IN ('1510000' , '1520000' , '1590495')
AND FUND_CODE = '05'   



