http://www.orafaq.com/node/854  --excellent doc on locks
http://www.myoracleguide.com/s/locks.htm#2 --various locks with working examples
https://forums.oracle.com/forums/thread.jspa?threadID=1085911 --difficult to get the sql of blocking session

http://www.shutdownabort.com/dbaqueries/Performance_Locks_DML.php **** Show locked objects, locked rows and more


-- below query gives the blocking and waiting session information.
select s1.username || '@' || s1.machine
    || ' ( SID=' || s1.sid || ' )  is blocking '
    || s2.username || '@' || s2.machine || ' ( SID=' || s2.sid || ' ) ' AS blocking_status
    from v$lock l1, v$session s1, v$lock l2, v$session s2
    where s1.sid=l1.sid and s2.sid=l2.sid
    and l1.BLOCK=1 and l2.request > 0
    and l1.id1 = l2.id1
    and l2.id2 = l2.id2 ;

-- Below is the longer version of the above query with more information about the session blocking, session waiting, sql of the session waiting. It is difficult to get the sql of the session blocking.
select s1.username || '@'         || s1.machine
                   || ' ( SID='   || s1.sid || ' )  is blocking '
                   || s2.username || '@'    || s2.machine || ' ( SID=' 
                   || s2.sid      || ' ) '  AS blocking_status,
sq.sql_text waiting_sql,
sq.sql_fulltext waiting_sql_full,                   
s1.ACTION ACTION_b,
s1.ACTION_HASH ACTION_HASH_b,
s1.AUDSID AUDSID_b,
s1.BLOCKING_INSTANCE BLOCKING_INSTANCE_b,
s1.BLOCKING_SESSION BLOCKING_SESSION_b,
s1.BLOCKING_SESSION_STATUS BLOCKING_SESSION_STATUS_b,
s1.CLIENT_IDENTIFIER CLIENT_IDENTIFIER_b,
s1.CLIENT_INFO CLIENT_INFO_b,
s1.COMMAND COMMAND_b,
s1.CREATOR_ADDR CREATOR_ADDR_b,
s1.CREATOR_SERIAL# CREATOR_SERIAL#_b,
s1.CURRENT_QUEUE_DURATION CURRENT_QUEUE_DURATION_b,
s1.ECID ECID_b,
s1.EVENT EVENT_b,
s1.EVENT# EVENT#_b,
s1.FAILED_OVER FAILED_OVER_b,
s1.FAILOVER_METHOD FAILOVER_METHOD_b,
s1.FAILOVER_TYPE FAILOVER_TYPE_b,
s1.FINAL_BLOCKING_INSTANCE FINAL_BLOCKING_INSTANCE_b,
s1.FINAL_BLOCKING_SESSION FINAL_BLOCKING_SESSION_b,
s1.FINAL_BLOCKING_SESSION_STATUS FINAL_BLOCKING_SESSION_STAT_b,
s1.FIXED_TABLE_SEQUENCE FIXED_TABLE_SEQUENCE_b,
s1.LAST_CALL_ET LAST_CALL_ET_b,
s1.LOCKWAIT LOCKWAIT_b,
s1.LOGON_TIME LOGON_TIME_b,
s1.MACHINE MACHINE_b,
s1.MODULE MODULE_b,
s1.MODULE_HASH MODULE_HASH_b,
s1.OSUSER OSUSER_b,
s1.OWNERID OWNERID_b,
s1.P1 P1_b,
s1.P1RAW P1RAW_b,
s1.P1TEXT P1TEXT_b,
s1.P2 P2_b,
s1.P2RAW P2RAW_b,
s1.P2TEXT P2TEXT_b,
s1.P3 P3_b,
s1.P3RAW P3RAW_b,
s1.P3TEXT P3TEXT_b,
s1.PADDR PADDR_b,
s1.PDDL_STATUS PDDL_STATUS_b,
s1.PDML_ENABLED PDML_ENABLED_b,
s1.PDML_STATUS PDML_STATUS_b,
s1.PLSQL_ENTRY_OBJECT_ID PLSQL_ENTRY_OBJECT_ID_b,
s1.PLSQL_ENTRY_SUBPROGRAM_ID PLSQL_ENTRY_SUBPROGRAM_ID_b,
s1.PLSQL_OBJECT_ID PLSQL_OBJECT_ID_b,
s1.PLSQL_SUBPROGRAM_ID PLSQL_SUBPROGRAM_ID_b,
s1.PORT PORT_b,
s1.PQ_STATUS PQ_STATUS_b,
s1.PREV_CHILD_NUMBER PREV_CHILD_NUMBER_b,
s1.PREV_EXEC_ID PREV_EXEC_ID_b,
s1.PREV_EXEC_START PREV_EXEC_START_b,
s1.PREV_HASH_VALUE PREV_HASH_VALUE_b,
s1.PREV_SQL_ADDR PREV_SQL_ADDR_b,
s1.PREV_SQL_ID PREV_SQL_ID_b,
s1.PROCESS PROCESS_b,
s1.PROGRAM PROGRAM_b,
s1.RESOURCE_CONSUMER_GROUP RESOURCE_CONSUMER_GROUP_b,
s1.ROW_WAIT_BLOCK# ROW_WAIT_BLOCK#_b,
s1.ROW_WAIT_FILE# ROW_WAIT_FILE#_b,
s1.ROW_WAIT_OBJ# ROW_WAIT_OBJ#_b,
s1.ROW_WAIT_ROW# ROW_WAIT_ROW#_b,
s1.SADDR SADDR_b,
s1.SCHEMA# SCHEMA#_b,
s1.SCHEMANAME SCHEMANAME_b,
s1.SECONDS_IN_WAIT SECONDS_IN_WAIT_b,
s1.SEQ# SEQ#_b,
s1.SERIAL# SERIAL#_b,
s1.SERVER SERVER_b,
s1.SERVICE_NAME SERVICE_NAME_b,
s1.SESSION_EDITION_ID SESSION_EDITION_ID_b,
s1.SID SID_b,
s1.SQL_ADDRESS SQL_ADDRESS_b,
s1.SQL_CHILD_NUMBER SQL_CHILD_NUMBER_b,
s1.SQL_EXEC_ID SQL_EXEC_ID_b,
s1.SQL_EXEC_START SQL_EXEC_START_b,
s1.SQL_HASH_VALUE SQL_HASH_VALUE_b,
s1.SQL_ID SQL_ID_b,
s1.SQL_TRACE SQL_TRACE_b,
s1.SQL_TRACE_BINDS SQL_TRACE_BINDS_b,
s1.SQL_TRACE_PLAN_STATS SQL_TRACE_PLAN_STATS_b,
s1.SQL_TRACE_WAITS SQL_TRACE_WAITS_b,
s1.STATE STATE_b,
s1.STATUS STATUS_b,
s1.TADDR TADDR_b,
s1.TERMINAL TERMINAL_b,
s1.TIME_REMAINING_MICRO TIME_REMAINING_MICRO_b,
s1.TIME_SINCE_LAST_WAIT_MICRO TIME_SINCE_LAST_WAIT_MICRO_b,
s1.TOP_LEVEL_CALL# TOP_LEVEL_CALL#_b,
s1.TYPE TYPE_b,
s1.USER# USER#_b,
s1.USERNAME USERNAME_b,
s1.WAIT_CLASS WAIT_CLASS_b,
s1.WAIT_CLASS# WAIT_CLASS#_b,
s1.WAIT_CLASS_ID WAIT_CLASS_ID_b,
s1.WAIT_TIME WAIT_TIME_b,
s1.WAIT_TIME_MICRO WAIT_TIME_MICRO_b,
s2.ACTION ACTION_w,
s2.ACTION_HASH ACTION_HASH_w,
s2.AUDSID AUDSID_w,
s2.BLOCKING_INSTANCE BLOCKING_INSTANCE_w,
s2.BLOCKING_SESSION BLOCKING_SESSION_w,
s2.BLOCKING_SESSION_STATUS BLOCKING_SESSION_STATUS_w,
s2.CLIENT_IDENTIFIER CLIENT_IDENTIFIER_w,
s2.CLIENT_INFO CLIENT_INFO_w,
s2.COMMAND COMMAND_w,
s2.CREATOR_ADDR CREATOR_ADDR_w,
s2.CREATOR_SERIAL# CREATOR_SERIAL#_w,
s2.CURRENT_QUEUE_DURATION CURRENT_QUEUE_DURATION_w,
s2.ECID ECID_w,
s2.EVENT EVENT_w,
s2.EVENT# EVENT#_w,
s2.FAILED_OVER FAILED_OVER_w,
s2.FAILOVER_METHOD FAILOVER_METHOD_w,
s2.FAILOVER_TYPE FAILOVER_TYPE_w,
s2.FINAL_BLOCKING_INSTANCE FINAL_BLOCKING_INSTANCE_w,
s2.FINAL_BLOCKING_SESSION FINAL_BLOCKING_SESSION_w,
s2.FINAL_BLOCKING_SESSION_STATUS FINAL_BLOCKING_SESSION_STAT_w,
s2.FIXED_TABLE_SEQUENCE FIXED_TABLE_SEQUENCE_w,
s2.LAST_CALL_ET LAST_CALL_ET_w,
s2.LOCKWAIT LOCKWAIT_w,
s2.LOGON_TIME LOGON_TIME_w,
s2.MACHINE MACHINE_w,
s2.MODULE MODULE_w,
s2.MODULE_HASH MODULE_HASH_w,
s2.OSUSER OSUSER_w,
s2.OWNERID OWNERID_w,
s2.P1 P1_w,
s2.P1RAW P1RAW_w,
s2.P1TEXT P1TEXT_w,
s2.P2 P2_w,
s2.P2RAW P2RAW_w,
s2.P2TEXT P2TEXT_w,
s2.P3 P3_w,
s2.P3RAW P3RAW_w,
s2.P3TEXT P3TEXT_w,
s2.PADDR PADDR_w,
s2.PDDL_STATUS PDDL_STATUS_w,
s2.PDML_ENABLED PDML_ENABLED_w,
s2.PDML_STATUS PDML_STATUS_w,
s2.PLSQL_ENTRY_OBJECT_ID PLSQL_ENTRY_OBJECT_ID_w,
s2.PLSQL_ENTRY_SUBPROGRAM_ID PLSQL_ENTRY_SUBPROGRAM_ID_w,
s2.PLSQL_OBJECT_ID PLSQL_OBJECT_ID_w,
s2.PLSQL_SUBPROGRAM_ID PLSQL_SUBPROGRAM_ID_w,
s2.PORT PORT_w,
s2.PQ_STATUS PQ_STATUS_w,
s2.PREV_CHILD_NUMBER PREV_CHILD_NUMBER_w,
s2.PREV_EXEC_ID PREV_EXEC_ID_w,
s2.PREV_EXEC_START PREV_EXEC_START_w,
s2.PREV_HASH_VALUE PREV_HASH_VALUE_w,
s2.PREV_SQL_ADDR PREV_SQL_ADDR_w,
s2.PREV_SQL_ID PREV_SQL_ID_w,
s2.PROCESS PROCESS_w,
s2.PROGRAM PROGRAM_w,
s2.RESOURCE_CONSUMER_GROUP RESOURCE_CONSUMER_GROUP_w,
s2.ROW_WAIT_BLOCK# ROW_WAIT_BLOCK#_w,
s2.ROW_WAIT_FILE# ROW_WAIT_FILE#_w,
s2.ROW_WAIT_OBJ# ROW_WAIT_OBJ#_w,
s2.ROW_WAIT_ROW# ROW_WAIT_ROW#_w,
s2.SADDR SADDR_w,
s2.SCHEMA# SCHEMA#_w,
s2.SCHEMANAME SCHEMANAME_w,
s2.SECONDS_IN_WAIT SECONDS_IN_WAIT_w,
s2.SEQ# SEQ#_w,
s2.SERIAL# SERIAL#_w,
s2.SERVER SERVER_w,
s2.SERVICE_NAME SERVICE_NAME_w,
s2.SESSION_EDITION_ID SESSION_EDITION_ID_w,
s2.SID SID_w,
s2.SQL_ADDRESS SQL_ADDRESS_w,
s2.SQL_CHILD_NUMBER SQL_CHILD_NUMBER_w,
s2.SQL_EXEC_ID SQL_EXEC_ID_w,
s2.SQL_EXEC_START SQL_EXEC_START_w,
s2.SQL_HASH_VALUE SQL_HASH_VALUE_w,
s2.SQL_ID SQL_ID_w,
s2.SQL_TRACE SQL_TRACE_w,
s2.SQL_TRACE_BINDS SQL_TRACE_BINDS_w,
s2.SQL_TRACE_PLAN_STATS SQL_TRACE_PLAN_STATS_w,
s2.SQL_TRACE_WAITS SQL_TRACE_WAITS_w,
s2.STATE STATE_w,
s2.STATUS STATUS_w,
s2.TADDR TADDR_w,
s2.TERMINAL TERMINAL_w,
s2.TIME_REMAINING_MICRO TIME_REMAINING_MICRO_w,
s2.TIME_SINCE_LAST_WAIT_MICRO TIME_SINCE_LAST_WAIT_MICRO_w,
s2.TOP_LEVEL_CALL# TOP_LEVEL_CALL#_w,
s2.TYPE TYPE_w,
s2.USER# USER#_w,
s2.USERNAME USERNAME_w,
s2.WAIT_CLASS WAIT_CLASS_w,
s2.WAIT_CLASS# WAIT_CLASS#_w,
s2.WAIT_CLASS_ID WAIT_CLASS_ID_w,
s2.WAIT_TIME WAIT_TIME_w,
s2.WAIT_TIME_MICRO WAIT_TIME_MICRO_w
from v$lock l1
   , v$session s1
   , v$lock l2
   , v$session s2
   , v$sql sq
where s1.sid=l1.sid and s2.sid=l2.sid
   and l1.BLOCK=1 
   and l2.request > 0
   and l1.id1 = l2.id1
   and l2.id2 = l2.id2
   and S2.SQL_ID = sq.sql_id (+) 

--------------------
------LOCKED OBJECTS
--------------------
select	oracle_username || ' (' || s.osuser || ')' username
,	s.sid || ',' || s.serial# sess_id
,	owner || '.' ||	object_name object
,	object_type
,	decode(	l.block
	,	0, 'Not Blocking'
	,	1, 'Blocking'
	,	2, 'Global') status
,	decode(v.locked_mode
	,	0, 'None'
	,	1, 'Null'
	,	2, 'Row-S (SS)'
	,	3, 'Row-X (SX)'
	,	4, 'Share'
	,	5, 'S/Row-X (SSX)'
	,	6, 'Exclusive', TO_CHAR(lmode)) mode_held
	,   sq.sql_text waiting_sql
    ,   sq.sql_fulltext waiting_sql_full,
S.ACTION ACTION_b,
S.ACTION_HASH ACTION_HASH_b,
S.AUDSID AUDSID_b,
S.BLOCKING_INSTANCE BLOCKING_INSTANCE_b,
S.BLOCKING_SESSION BLOCKING_SESSION_b,
S.BLOCKING_SESSION_STATUS BLOCKING_SESSION_STATUS_b,
S.CLIENT_IDENTIFIER CLIENT_IDENTIFIER_b,
S.CLIENT_INFO CLIENT_INFO_b,
S.COMMAND COMMAND_b,
S.CREATOR_ADDR CREATOR_ADDR_b,
S.CREATOR_SERIAL# CREATOR_SERIAL#_b,
S.CURRENT_QUEUE_DURATION CURRENT_QUEUE_DURATION_b,
S.ECID ECID_b,
S.EVENT EVENT_b,
S.EVENT# EVENT#_b,
S.FAILED_OVER FAILED_OVER_b,
S.FAILOVER_METHOD FAILOVER_METHOD_b,
S.FAILOVER_TYPE FAILOVER_TYPE_b,
S.FINAL_BLOCKING_INSTANCE FINAL_BLOCKING_INSTANCE_b,
S.FINAL_BLOCKING_SESSION FINAL_BLOCKING_SESSION_b,
S.FINAL_BLOCKING_SESSION_STATUS FINAL_BLOCKING_SESSION_STAT_b,
S.FIXED_TABLE_SEQUENCE FIXED_TABLE_SEQUENCE_b,
S.LAST_CALL_ET LAST_CALL_ET_b,
S.LOCKWAIT LOCKWAIT_b,
S.LOGON_TIME LOGON_TIME_b,
S.MACHINE MACHINE_b,
S.MODULE MODULE_b,
S.MODULE_HASH MODULE_HASH_b,
S.OSUSER OSUSER_b,
S.OWNERID OWNERID_b,
S.P1 P1_b,
S.P1RAW P1RAW_b,
S.P1TEXT P1TEXT_b,
S.P2 P2_b,
S.P2RAW P2RAW_b,
S.P2TEXT P2TEXT_b,
S.P3 P3_b,
S.P3RAW P3RAW_b,
S.P3TEXT P3TEXT_b,
S.PADDR PADDR_b,
S.PDDL_STATUS PDDL_STATUS_b,
S.PDML_ENABLED PDML_ENABLED_b,
S.PDML_STATUS PDML_STATUS_b,
S.PLSQL_ENTRY_OBJECT_ID PLSQL_ENTRY_OBJECT_ID_b,
S.PLSQL_ENTRY_SUBPROGRAM_ID PLSQL_ENTRY_SUBPROGRAM_ID_b,
S.PLSQL_OBJECT_ID PLSQL_OBJECT_ID_b,
S.PLSQL_SUBPROGRAM_ID PLSQL_SUBPROGRAM_ID_b,
S.PORT PORT_b,
S.PQ_STATUS PQ_STATUS_b,
S.PREV_CHILD_NUMBER PREV_CHILD_NUMBER_b,
S.PREV_EXEC_ID PREV_EXEC_ID_b,
S.PREV_EXEC_START PREV_EXEC_START_b,
S.PREV_HASH_VALUE PREV_HASH_VALUE_b,
S.PREV_SQL_ADDR PREV_SQL_ADDR_b,
S.PREV_SQL_ID PREV_SQL_ID_b,
S.PROCESS PROCESS_b,
S.PROGRAM PROGRAM_b,
S.RESOURCE_CONSUMER_GROUP RESOURCE_CONSUMER_GROUP_b,
S.ROW_WAIT_BLOCK# ROW_WAIT_BLOCK#_b,
S.ROW_WAIT_FILE# ROW_WAIT_FILE#_b,
S.ROW_WAIT_OBJ# ROW_WAIT_OBJ#_b,
S.ROW_WAIT_ROW# ROW_WAIT_ROW#_b,
S.SADDR SADDR_b,
S.SCHEMA# SCHEMA#_b,
S.SCHEMANAME SCHEMANAME_b,
S.SECONDS_IN_WAIT SECONDS_IN_WAIT_b,
S.SEQ# SEQ#_b,
S.SERIAL# SERIAL#_b,
S.SERVER SERVER_b,
S.SERVICE_NAME SERVICE_NAME_b,
S.SESSION_EDITION_ID SESSION_EDITION_ID_b,
S.SID SID_b,
S.SQL_ADDRESS SQL_ADDRESS_b,
S.SQL_CHILD_NUMBER SQL_CHILD_NUMBER_b,
S.SQL_EXEC_ID SQL_EXEC_ID_b,
S.SQL_EXEC_START SQL_EXEC_START_b,
S.SQL_HASH_VALUE SQL_HASH_VALUE_b,
S.SQL_ID SQL_ID_b,
S.SQL_TRACE SQL_TRACE_b,
S.SQL_TRACE_BINDS SQL_TRACE_BINDS_b,
S.SQL_TRACE_PLAN_STATS SQL_TRACE_PLAN_STATS_b,
S.SQL_TRACE_WAITS SQL_TRACE_WAITS_b,
S.STATE STATE_b,
S.STATUS STATUS_b,
S.TADDR TADDR_b,
S.TERMINAL TERMINAL_b,
S.TIME_REMAINING_MICRO TIME_REMAINING_MICRO_b,
S.TIME_SINCE_LAST_WAIT_MICRO TIME_SINCE_LAST_WAIT_MICRO_b,
S.TOP_LEVEL_CALL# TOP_LEVEL_CALL#_b,
S.TYPE TYPE_b,
S.USER# USER#_b,
S.USERNAME USERNAME_b,
S.WAIT_CLASS WAIT_CLASS_b,
S.WAIT_CLASS# WAIT_CLASS#_b,
S.WAIT_CLASS_ID WAIT_CLASS_ID_b,
S.WAIT_TIME WAIT_TIME_b,
S.WAIT_TIME_MICRO WAIT_TIME_MICRO_b	
from	v$locked_object v
,	dba_objects d
,	v$lock l
,	v$session s
,   v$sql sq
where 	v.object_id = d.object_id
and 	v.object_id = l.id1
and 	v.session_id = s.sid
and     S.SQL_ID = sq.sql_id (+) 
order by oracle_username
,	session_id	
	


SELECT DECODE(request,0,'Holder: ','Waiter: ')||sid sess,
id1, id2, lmode, request, type
FROM V$LOCK
WHERE (id1, id2, type) IN
(SELECT id1, id2, type FROM V$LOCK WHERE request>0)
ORDER BY id1, request


select * from dba_hist_active_sess_history


SELECT start_timestamp,commit_timestamp,logon_user,table_owner,table_name,operation, undo_sql
FROM flashback_transaction_query ftq,v$transaction vt,v$session vs
WHERE ftq.xid = vt.xid and vt.ses_addr=vs.saddr AND vs.sid=1234;
 
SELECT start_timestamp,commit_timestamp,logon_user,table_owner,table_name,operation, undo_sql
FROM flashback_transaction_query ftq,v$transaction vt,v$session vs
WHERE ftq.xid = vt.xid and vt.ses_addr=vs.saddr AND vs.sid=1235;

 
 
 

