
declare

v_cnt      NUMBER;
v_cnt_conv NUMBER;
v_cnt_prod NUMBER;
record_count_mismatch exception;

begin
for i in
(
SELECT 
  CMCL_COMP_CODE,
  CMCL_CHG_ORD_AUTONUM_FLAG,
  CMCL_BUDG_REV_AUTONUM_FLAG,
  CMCL_CHG_ORD_NUMBER_MASK,
  CMCL_BUDG_REV_NUMBER_MASK,
  CMCL_POST_CONTR_FLAG,
  CMCL_UPD_PC_COMPL_FLAG,
  CMCL_TRANSFER_BALANCED_FLAG,
  CMCL_INT_CO_NUMBER_MASK,
  CMCL_TRANSF_CO_NUMBER_MASK,
  CMCL_PHS_QTY_ENTRY_CAT_CODE,
  CMCL_DEFAULT_JOB_FLAG,
  CMCL_GROUP_SC_TASK_FLAG,
  CMCL_PROPOSAL_AUTONUM_FLAG,
  CMCL_PROPOSAL_CODE_MASK,
  CMCL_OWN_CHG_AUTONUM_FLAG,
  CMCL_OWN_CHG_NUM_MASK,
  CMCL_CREATE_SC_FROM_CM,
  CMCL_INT_CHG_UPD_BUDG_FLAG,
  CMCL_UPD_PROJ_AMT_FLAG,
  CMCL_BILL_TRANSFER_BAL_FLAG,
  CMCL_CALC_PROJ_AMT_METHOD,
  --CMCL__IU__CREATE_DATE,
  --CMCL__IU__CREATE_USER,
  --CMCL__IU__UPDATE_DATE,
  --CMCL__IU__UPDATE_USER,
  CMCL_REQ_BILLCODE_TRN_CO_FLAG,
  CMCL_ORIGB_CO_NUMBER_MASK,
  CMCL_PCI_SCCO_ROLLUP_FLAG,
  CMCL_BILL_AMT_FROM_RATE_FLAG,
  CMCL_ALLOW_PHSENT_NULLCAT_FLAG,
  CMCL_UPD_JB_MAXBILL_AMT_FLAG,
  CMCL_TRN_BAL_POSTING_ONLY_FLAG
FROM DA.CMCTRL@CONV 
WHERE CMCL_COMP_CODE not in ('ZZ')
) loop
INSERT INTO DA.CMCTRL
(  
  CMCL_COMP_CODE,
  CMCL_CHG_ORD_AUTONUM_FLAG,
  CMCL_BUDG_REV_AUTONUM_FLAG,
  CMCL_CHG_ORD_NUMBER_MASK,
  CMCL_BUDG_REV_NUMBER_MASK,
  CMCL_POST_CONTR_FLAG,
  CMCL_UPD_PC_COMPL_FLAG,
  CMCL_TRANSFER_BALANCED_FLAG,
  CMCL_INT_CO_NUMBER_MASK,
  CMCL_TRANSF_CO_NUMBER_MASK,
  CMCL_PHS_QTY_ENTRY_CAT_CODE,
  CMCL_DEFAULT_JOB_FLAG,
  CMCL_GROUP_SC_TASK_FLAG,
  CMCL_PROPOSAL_AUTONUM_FLAG,
  CMCL_PROPOSAL_CODE_MASK,
  CMCL_OWN_CHG_AUTONUM_FLAG,
  CMCL_OWN_CHG_NUM_MASK,
  CMCL_CREATE_SC_FROM_CM,
  CMCL_INT_CHG_UPD_BUDG_FLAG,
  CMCL_UPD_PROJ_AMT_FLAG,
  CMCL_BILL_TRANSFER_BAL_FLAG,
  CMCL_CALC_PROJ_AMT_METHOD,
  --CMCL__IU__CREATE_DATE,
  --CMCL__IU__CREATE_USER,
  --CMCL__IU__UPDATE_DATE,
  --CMCL__IU__UPDATE_USER,
  CMCL_REQ_BILLCODE_TRN_CO_FLAG,
  CMCL_ORIGB_CO_NUMBER_MASK,
  CMCL_PCI_SCCO_ROLLUP_FLAG,
  CMCL_BILL_AMT_FROM_RATE_FLAG,
  CMCL_ALLOW_PHSENT_NULLCAT_FLAG,
  CMCL_UPD_JB_MAXBILL_AMT_FLAG,
  CMCL_TRN_BAL_POSTING_ONLY_FLAG

)
values
(
i.    CMCL_COMP_CODE,
i.    CMCL_CHG_ORD_AUTONUM_FLAG,
i.    CMCL_BUDG_REV_AUTONUM_FLAG,
i.    CMCL_CHG_ORD_NUMBER_MASK,
i.    CMCL_BUDG_REV_NUMBER_MASK,
i.    CMCL_POST_CONTR_FLAG,
i.    CMCL_UPD_PC_COMPL_FLAG,
i.    CMCL_TRANSFER_BALANCED_FLAG,
i.    CMCL_INT_CO_NUMBER_MASK,
i.    CMCL_TRANSF_CO_NUMBER_MASK,
i.    CMCL_PHS_QTY_ENTRY_CAT_CODE,
i.    CMCL_DEFAULT_JOB_FLAG,
i.    CMCL_GROUP_SC_TASK_FLAG,
i.    CMCL_PROPOSAL_AUTONUM_FLAG,
i.    CMCL_PROPOSAL_CODE_MASK,
i.    CMCL_OWN_CHG_AUTONUM_FLAG,
i.    CMCL_OWN_CHG_NUM_MASK,
i.    CMCL_CREATE_SC_FROM_CM,
i.    CMCL_INT_CHG_UPD_BUDG_FLAG,
i.    CMCL_UPD_PROJ_AMT_FLAG,
i.    CMCL_BILL_TRANSFER_BAL_FLAG,
i.    CMCL_CALC_PROJ_AMT_METHOD,
--i.    --CMCL__IU__CREATE_DATE,
--i.    --CMCL__IU__CREATE_USER,
--i.    --CMCL__IU__UPDATE_DATE,
--i.    --CMCL__IU__UPDATE_USER,
i.    CMCL_REQ_BILLCODE_TRN_CO_FLAG,
i.    CMCL_ORIGB_CO_NUMBER_MASK,
i.    CMCL_PCI_SCCO_ROLLUP_FLAG,
i.    CMCL_BILL_AMT_FROM_RATE_FLAG,
i.    CMCL_ALLOW_PHSENT_NULLCAT_FLAG,
i.    CMCL_UPD_JB_MAXBILL_AMT_FLAG,
i.    CMCL_TRN_BAL_POSTING_ONLY_FLAG

);
end loop;
--commit;
select count(1) into v_cnt_conv from CMCTRL@conv;
select count(1) into v_cnt_prod from CMCTRL@prod;
if v_cnt_conv - v_cnt_prod = 0
then
dbms_output.put_line ('Number of records in PROD match with CONV for CMCTRL table.');
else
dbms_output.put_line ('Number of records in PROD does not match with CONV for CMCTRL table.');
Raise record_count_mismatch;
end if;
Select count(1) into v_cnt from DA.CMCTRL@PROD where CMCL_COMP_CODE not in ('ZZ');
dbms_output.put_line ('Inserted '||v_cnt||' records into CMCTRL table, check and commit.');
EXCEPTION
WHEN record_count_mismatch
THEN
DBMS_OUTPUT.PUT_LINE ('There is a mismatch in PROD and CONV for this table.');
WHEN OTHERS 
THEN
DBMS_OUTPUT.PUT_LINE ('ERROR WHILE INSERTING INTO DA.CMCTRL.');
DBMS_OUTPUT.PUT_LINE (SQLERRM);

end;
/ 