

declare

v_cnt      NUMBER;
v_cnt_conv NUMBER;
v_cnt_prod NUMBER;
record_count_mismatch exception;

begin
for i in
(
SELECT DEPT_COMP_CODE,
  DEPT_CODE,
  DEPT_CONSCHART_CODE,
  DEPT_CTRL_CODE,
  DEPT_NAME,
  DEPT_ADD1,
  DEPT_ADD2,
  DEPT_ADD3,
  DEPT_REGION_CODE,
  DEPT_COUNTRY,
  DEPT_POSTAL_CODE,
  DEPT_COUNTRY_CODE,
  DEPT_AREA_CODE,
  DEPT_PHONE_NUM,
  DEPT_INTER_CLEAR_ACC_CODE,
  DEPT_INCOME_CLOSE_DEPT_CODE,
  DEPT_INCOME_CLOSE_ACC_CODE,
  DEPT_YR,
  DEPT_BU_CODE,
  DEPT_PER,
  DEPT_CLOSE_YR,
  DEPT_BALANCE_FLAG,
  DEPT_TAX_CODE,
  DEPT_FED_TAX1_CODE,
  DEPT_FED_TAX2_CODE,
  DEPT_CK_DIGIT_CODE,
  DEPT_TAX1_CODE,
  DEPT_TAX1_INCINV_FLAG,
  DEPT_TAX2_CODE,
  DEPT_TAX2_INCINV_FLAG,
  DEPT_TAX3_CODE,
  DEPT_TAX3_INCINV_FLAG,
  DEPT_TAX4_CODE,
  DEPT_TAX4_INCINV_FLAG,
  DEPT_TAX5_CODE,
  DEPT_TAX5_INCINV_FLAG,
  DEPT_HIER,
  DEPT_WCB_CODE,
  DEPT_ADDR_COMP_CODE,
  DEPT_ADDR_CODE,
  DEPT_IB_REV_ACC_CODE,
  DEPT_AP_TAX1_CODE,
  DEPT_AP_TAX2_CODE,
  DEPT_AP_TAX3_CODE,
  DEPT_JB_ALT_COMP_ADD_CODE,
  DEPT_JB_ALT_REMIT_ADD_CODE,
  DEPT_FAX_COUNTRY_CODE,
  DEPT_FAX_AREA_CODE,
  DEPT_FAX_NUM,
  --DEPT__IU__CREATE_DATE,
  --DEPT__IU__CREATE_USER,
  --DEPT__IU__UPDATE_DATE,
  --DEPT__IU__UPDATE_USER,
  DEPT_BILLING_RATE_CODE
FROM DA.DEPT_TABLE@CONV
WHERE DEPT_COMP_CODE NOT IN ('ZZ')
) loop
INSERT INTO DA.DEPT_TABLE
( 
  DEPT_COMP_CODE,
  DEPT_CODE,
  DEPT_CONSCHART_CODE,
  DEPT_CTRL_CODE,
  DEPT_NAME,
  DEPT_ADD1,
  DEPT_ADD2,
  DEPT_ADD3,
  DEPT_REGION_CODE,
  DEPT_COUNTRY,
  DEPT_POSTAL_CODE,
  DEPT_COUNTRY_CODE,
  DEPT_AREA_CODE,
  DEPT_PHONE_NUM,
  DEPT_INTER_CLEAR_ACC_CODE,
  DEPT_INCOME_CLOSE_DEPT_CODE,
  DEPT_INCOME_CLOSE_ACC_CODE,
  DEPT_YR,
  DEPT_BU_CODE,
  DEPT_PER,
  DEPT_CLOSE_YR,
  DEPT_BALANCE_FLAG,
  DEPT_TAX_CODE,
  DEPT_FED_TAX1_CODE,
  DEPT_FED_TAX2_CODE,
  DEPT_CK_DIGIT_CODE,
  DEPT_TAX1_CODE,
  DEPT_TAX1_INCINV_FLAG,
  DEPT_TAX2_CODE,
  DEPT_TAX2_INCINV_FLAG,
  DEPT_TAX3_CODE,
  DEPT_TAX3_INCINV_FLAG,
  DEPT_TAX4_CODE,
  DEPT_TAX4_INCINV_FLAG,
  DEPT_TAX5_CODE,
  DEPT_TAX5_INCINV_FLAG,
  DEPT_HIER,
  DEPT_WCB_CODE,
  DEPT_ADDR_COMP_CODE,
  DEPT_ADDR_CODE,
  DEPT_IB_REV_ACC_CODE,
  DEPT_AP_TAX1_CODE,
  DEPT_AP_TAX2_CODE,
  DEPT_AP_TAX3_CODE,
  DEPT_JB_ALT_COMP_ADD_CODE,
  DEPT_JB_ALT_REMIT_ADD_CODE,
  DEPT_FAX_COUNTRY_CODE,
  DEPT_FAX_AREA_CODE,
  DEPT_FAX_NUM,
  --DEPT__IU__CREATE_DATE,
  --DEPT__IU__CREATE_USER,
  --DEPT__IU__UPDATE_DATE,
  --DEPT__IU__UPDATE_USER,
  DEPT_BILLING_RATE_CODE
)
values
(
i.DEPT_COMP_CODE,
i.  DEPT_CODE,
i.  DEPT_CONSCHART_CODE,
i.  DEPT_CTRL_CODE,
i.  DEPT_NAME,
i.  DEPT_ADD1,
i.  DEPT_ADD2,
i.  DEPT_ADD3,
i.  DEPT_REGION_CODE,
i.  DEPT_COUNTRY,
i.  DEPT_POSTAL_CODE,
i.  DEPT_COUNTRY_CODE,
i.  DEPT_AREA_CODE,
i.  DEPT_PHONE_NUM,
i.  DEPT_INTER_CLEAR_ACC_CODE,
i.  DEPT_INCOME_CLOSE_DEPT_CODE,
i.  DEPT_INCOME_CLOSE_ACC_CODE,
i.  DEPT_YR,
i.  DEPT_BU_CODE,
i.  DEPT_PER,
i.  DEPT_CLOSE_YR,
i.  DEPT_BALANCE_FLAG,
i.  DEPT_TAX_CODE,
i.  DEPT_FED_TAX1_CODE,
i.  DEPT_FED_TAX2_CODE,
i.  DEPT_CK_DIGIT_CODE,
i.  DEPT_TAX1_CODE,
i.  DEPT_TAX1_INCINV_FLAG,
i.  DEPT_TAX2_CODE,
i.  DEPT_TAX2_INCINV_FLAG,
i.  DEPT_TAX3_CODE,
i.  DEPT_TAX3_INCINV_FLAG,
i.  DEPT_TAX4_CODE,
i.  DEPT_TAX4_INCINV_FLAG,
i.  DEPT_TAX5_CODE,
i.  DEPT_TAX5_INCINV_FLAG,
i.  DEPT_HIER,
i.  DEPT_WCB_CODE,
i.  DEPT_ADDR_COMP_CODE,
i.  DEPT_ADDR_CODE,
i.  DEPT_IB_REV_ACC_CODE,
i.  DEPT_AP_TAX1_CODE,
i.  DEPT_AP_TAX2_CODE,
i.  DEPT_AP_TAX3_CODE,
i.  DEPT_JB_ALT_COMP_ADD_CODE,
i.  DEPT_JB_ALT_REMIT_ADD_CODE,
i.  DEPT_FAX_COUNTRY_CODE,
i.  DEPT_FAX_AREA_CODE,
i.  DEPT_FAX_NUM,
--i.  --DEPT__IU__CREATE_DATE,
--i.  --DEPT__IU__CREATE_USER,
--i.  --DEPT__IU__UPDATE_DATE,
--i.  --DEPT__IU__UPDATE_USER,
i.  DEPT_BILLING_RATE_CODE

);
end loop;
--commit;
select count(1) into v_cnt_conv from DEPT_TABLE@conv;
select count(1) into v_cnt_prod from DEPT_TABLE@prod;
if v_cnt_conv - v_cnt_prod = 0
then
dbms_output.put_line ('Number of records in PROD match with CONV for DEPT_TABLE table.');
else
dbms_output.put_line ('Number of records in PROD does not match with CONV for DEPT_TABLE table.');
Raise record_count_mismatch;
end if;
Select count(1) into v_cnt from DA.DEPT_TABLE@PROD where DEPT_COMP_CODE NOT IN ('ZZ');
dbms_output.put_line ('Inserted '||v_cnt||' records into DEPT_TABLE table, check and commit.');
EXCEPTION
WHEN record_count_mismatch
THEN
DBMS_OUTPUT.PUT_LINE ('There is a mismatch in PROD and CONV for this table.');
WHEN OTHERS 
THEN
DBMS_OUTPUT.PUT_LINE ('ERROR WHILE INSERTING INTO DA.DEPT_TABLE.');
DBMS_OUTPUT.PUT_LINE (SQLERRM);

end;
/ 