--         Confidentiality Information:                           \par
--                                                                \par
--  This module contains confidential and proprietary information \par
--  of PeopleSoft, Inc.; it is not to be copied, reproduced, or   \par
--  transmitted in any form, by any means, in whole or in part,   \par
--  nor is it to be used for any purpose other than that for      \par
--  which it is expressly provided under the applicable license   \par
--  agreement.                                                    \par
--                                                                \par
--  Copyright (C) 2005 PeopleSoft, Inc. All Rights Reserved.      \par
-- **************************************************************\par
Remark * Script: epddl.sql  Oracle on NT\par
Remark * Date last modified: 6/27/05\par
\par
Remark * This script is used to create tablespaces for the PeopleSoft 8.9\par
Remark * Financials and Supply Chain Management Products.\par
\par
Remark * NOTE: The sizing of the tablespaces here are only sample sizes that will\par
Remark *       hold the demo database tables.  This is not sized correctly for a\par
Remark *       production database.  \par
                                                                  \par
Remark * Users can choose to use the autoextending tablespace feature.\par
Remark * The syntax is at the end of this script.\par
\par
Remark * Change the datafile name as appropriate for your site.\par
\par
set echo on;\par
spool epddl.log;\par
\par
\par
CREATE TABLESPACE AMAPP DATAFILE '+FNPRDDATA/fnprd/datafile/amapp.dbf' SIZE 119M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE AMARCH DATAFILE '+FNPRDDATA/fnprd/datafile/amarch.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE AMLARGE DATAFILE '+FNPRDDATA/fnprd/datafile/amlarge.dbf' SIZE 72M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE AMWORK DATAFILE '+FNPRDDATA/fnprd/datafile/amwork.dbf' SIZE 63M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE APAPP DATAFILE '+FNPRDDATA/fnprd/datafile/apapp.dbf' SIZE 90M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE APARCH DATAFILE '+FNPRDDATA/fnprd/datafile/aparch.dbf' SIZE 5M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE APLARGE DATAFILE '+FNPRDDATA/fnprd/datafile/aplarge.dbf' SIZE 94M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE APWORK DATAFILE '+FNPRDDATA/fnprd/datafile/apwork.dbf' SIZE 193M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE ARAPP DATAFILE '+FNPRDDATA/fnprd/datafile/arapp.dbf' SIZE 42M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE ARARCH DATAFILE '+FNPRDDATA/fnprd/datafile/ararch.dbf' SIZE 3M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE ARLARGE DATAFILE '+FNPRDDATA/fnprd/datafile/arlarge.dbf' SIZE 46M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE ARWORK DATAFILE '+FNPRDDATA/fnprd/datafile/arwork.dbf' SIZE 159M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE AUCAPP DATAFILE '+FNPRDDATA/fnprd/datafile/aucapp.dbf' SIZE 20M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE AUCLRGE DATAFILE '+FNPRDDATA/fnprd/datafile/auclrge.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE BCAPP DATAFILE '+FNPRDDATA/fnprd/datafile/bcapp.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE BDAPP DATAFILE '+FNPRDDATA/fnprd/datafile/bdapp.dbf' SIZE 19M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE BDLARGE DATAFILE '+FNPRDDATA/fnprd/datafile/bdlarge.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE BIAPP DATAFILE '+FNPRDDATA/fnprd/datafile/biapp.dbf' SIZE 33M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE BILARGE DATAFILE '+FNPRDDATA/fnprd/datafile/bilarge.dbf' SIZE 22M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE BIWORK DATAFILE '+FNPRDDATA/fnprd/datafile/biwork.dbf' SIZE 121M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE CAAPP DATAFILE '+FNPRDDATA/fnprd/datafile/caapp.dbf' SIZE 77M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE CAWORK DATAFILE '+FNPRDDATA/fnprd/datafile/cawork.dbf' SIZE 68M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE CFGAPP DATAFILE '+FNPRDDATA/fnprd/datafile/cfgapp.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE CPAPP DATAFILE '+FNPRDDATA/fnprd/datafile/cpapp.dbf' SIZE 8M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE CPLARGE DATAFILE '+FNPRDDATA/fnprd/datafile/cplarge.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE CSAPP DATAFILE '+FNPRDDATA/fnprd/datafile/csapp.dbf' SIZE 8M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE CSLARGE DATAFILE '+FNPRDDATA/fnprd/datafile/cslarge.dbf' SIZE 3M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE CSWORK DATAFILE '+FNPRDDATA/fnprd/datafile/cswork.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE CUAUDIT DATAFILE '+FNPRDDATA/fnprd/datafile/cuaudit.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE CULARG1 DATAFILE '+FNPRDDATA/fnprd/datafile/cularg1.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE CULARG2 DATAFILE '+FNPRDDATA/fnprd/datafile/cularg2.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE CULARG3 DATAFILE '+FNPRDDATA/fnprd/datafile/cularg3.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE CULARGE DATAFILE '+FNPRDDATA/fnprd/datafile/cularge.dbf' SIZE 4M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE DIAPP DATAFILE '+FNPRDDATA/fnprd/datafile/diapp.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE DPAPP DATAFILE '+FNPRDDATA/fnprd/datafile/dpapp.dbf' SIZE 37M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE DPLARGE DATAFILE '+FNPRDDATA/fnprd/datafile/dplarge.dbf' SIZE 10M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE DPWORK DATAFILE '+FNPRDDATA/fnprd/datafile/dpwork.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE EOAPP DATAFILE '+FNPRDDATA/fnprd/datafile/eoapp.dbf' SIZE 3M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE EOBFAPP DATAFILE '+FNPRDDATA/fnprd/datafile/eobfapp.dbf' SIZE 1M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE EOCFAPP DATAFILE '+FNPRDDATA/fnprd/datafile/eocfapp.dbf' SIZE 1M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE EOCMAPP DATAFILE '+FNPRDDATA/fnprd/datafile/eocmapp.dbf' SIZE 1M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE EOCMLRG DATAFILE '+FNPRDDATA/fnprd/datafile/eocmlrg.dbf' SIZE 1M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE EOCMWRK DATAFILE '+FNPRDDATA/fnprd/datafile/eocmwrk.dbf' SIZE 1M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE EOCUAPP DATAFILE '+FNPRDDATA/fnprd/datafile/eocuapp.dbf' SIZE 1M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE EOCULRG DATAFILE '+FNPRDDATA/fnprd/datafile/eoculrg.dbf' SIZE 1M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE EODSAPP DATAFILE '+FNPRDDATA/fnprd/datafile/eodsapp.dbf' SIZE 1M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE EODSLRG DATAFILE '+FNPRDDATA/fnprd/datafile/eodslrg.dbf' SIZE 1M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE EOECAPP DATAFILE '+FNPRDDATA/fnprd/datafile/eoecapp.dbf' SIZE 1M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE EOECLRG DATAFILE '+FNPRDDATA/fnprd/datafile/eoeclrg.dbf' SIZE 1M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE EOECWRK DATAFILE '+FNPRDDATA/fnprd/datafile/eoecwrk.dbf' SIZE 1M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE EOEIAPP DATAFILE '+FNPRDDATA/fnprd/datafile/eoeiapp.dbf' SIZE 1M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE EOEILRG DATAFILE '+FNPRDDATA/fnprd/datafile/eoeilrg.dbf' SIZE 1M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE EOEPAPP DATAFILE '+FNPRDDATA/fnprd/datafile/eoepapp.dbf' SIZE 1M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE EOEPLRG DATAFILE '+FNPRDDATA/fnprd/datafile/eoeplrg.dbf' SIZE 1M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE EOEPWRK DATAFILE '+FNPRDDATA/fnprd/datafile/eoepwrk.dbf' SIZE 1M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE EOEWAPP DATAFILE '+FNPRDDATA/fnprd/datafile/eoewapp.dbf' SIZE 1M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE EOEWLRG DATAFILE '+FNPRDDATA/fnprd/datafile/eoewlrg.dbf' SIZE 1M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE EOEWWRK DATAFILE '+FNPRDDATA/fnprd/datafile/eoewwrk.dbf' SIZE 1M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE EOIUAPP DATAFILE '+FNPRDDATA/fnprd/datafile/eoiuapp.dbf' SIZE 1M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE EOIULRG DATAFILE '+FNPRDDATA/fnprd/datafile/eoiulrg.dbf' SIZE 1M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE EOIUWRK DATAFILE '+FNPRDDATA/fnprd/datafile/eoiuwrk.dbf' SIZE 1M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE EOLARGE DATAFILE '+FNPRDDATA/fnprd/datafile/eolarge.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE EOLTAPP DATAFILE '+FNPRDDATA/fnprd/datafile/eoltapp.dbf' SIZE 1M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE EOPPAPP DATAFILE '+FNPRDDATA/fnprd/datafile/eoppapp.dbf' SIZE 1M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE EOPPLRG DATAFILE '+FNPRDDATA/fnprd/datafile/eopplrg.dbf' SIZE 1M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE EOTPAPP DATAFILE '+FNPRDDATA/fnprd/datafile/eotpapp.dbf' SIZE 1M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE EOTPLRG DATAFILE '+FNPRDDATA/fnprd/datafile/eotplrg.dbf' SIZE 1M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE EXAPP DATAFILE '+FNPRDDATA/fnprd/datafile/exapp.dbf' SIZE 13M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE EXARCH DATAFILE '+FNPRDDATA/fnprd/datafile/exarch.dbf' SIZE 3M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE EXLARGE DATAFILE '+FNPRDDATA/fnprd/datafile/exlarge.dbf' SIZE 12M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE EXWORK DATAFILE '+FNPRDDATA/fnprd/datafile/exwork.dbf' SIZE 81M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE FAAPP DATAFILE '+FNPRDDATA/fnprd/datafile/faapp.dbf' SIZE 32M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE FALARGE DATAFILE '+FNPRDDATA/fnprd/datafile/falarge.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE FAWORK DATAFILE '+FNPRDDATA/fnprd/datafile/fawork.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE FGAPP DATAFILE '+FNPRDDATA/fnprd/datafile/fgapp.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE FGARCH DATAFILE '+FNPRDDATA/fnprd/datafile/fgarch.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE FGIMAGE DATAFILE '+FNPRDDATA/fnprd/datafile/fgimage.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE FGLARGE DATAFILE '+FNPRDDATA/fnprd/datafile/fglarge.dbf' SIZE 6M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE FGTEMP DATAFILE '+FNPRDDATA/fnprd/datafile/fgtemp.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE FGWORK DATAFILE '+FNPRDDATA/fnprd/datafile/fgwork.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE FIAPP DATAFILE '+FNPRDDATA/fnprd/datafile/fiapp.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE FILARGE DATAFILE '+FNPRDDATA/fnprd/datafile/filarge.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE FOAPP DATAFILE '+FNPRDDATA/fnprd/datafile/foapp.dbf' SIZE 10M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE FOIMAGE DATAFILE '+FNPRDDATA/fnprd/datafile/foimage.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE FOLARGE DATAFILE '+FNPRDDATA/fnprd/datafile/folarge.dbf' SIZE 8M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE FOWORK DATAFILE '+FNPRDDATA/fnprd/datafile/fowork.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE FSAPP DATAFILE '+FNPRDDATA/fnprd/datafile/fsapp.dbf' SIZE 202M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE FSAPP1 DATAFILE '+FNPRDDATA/fnprd/datafile/fsapp1.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE FSLARGE DATAFILE '+FNPRDDATA/fnprd/datafile/fslarge.dbf' SIZE 45M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE FSWORK DATAFILE '+FNPRDDATA/fnprd/datafile/fswork.dbf' SIZE 49M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE GLAPP DATAFILE '+FNPRDDATA/fnprd/datafile/glapp.dbf' SIZE 184M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE GLARCH DATAFILE '+FNPRDDATA/fnprd/datafile/glarch.dbf' SIZE 10M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE GLLARGE DATAFILE '+FNPRDDATA/fnprd/datafile/gllarge.dbf' SIZE 99M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE GLWORK DATAFILE '+FNPRDDATA/fnprd/datafile/glwork.dbf' SIZE 121M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE GMAPP DATAFILE '+FNPRDDATA/fnprd/datafile/gmapp.dbf' SIZE 41M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE HRAPP DATAFILE '+FNPRDDATA/fnprd/datafile/hrapp.dbf' SIZE 6M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE HRLARGE DATAFILE '+FNPRDDATA/fnprd/datafile/hrlarge.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE HTAPP DATAFILE '+FNPRDDATA/fnprd/datafile/htapp.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE INAPP DATAFILE '+FNPRDDATA/fnprd/datafile/inapp.dbf' SIZE 128M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE INARCH DATAFILE '+FNPRDDATA/fnprd/datafile/inarch.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE INLARGE DATAFILE '+FNPRDDATA/fnprd/datafile/inlarge.dbf' SIZE 75M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE INWORK DATAFILE '+FNPRDDATA/fnprd/datafile/inwork.dbf' SIZE 319M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE LCAPP DATAFILE '+FNPRDDATA/fnprd/datafile/lcapp.dbf' SIZE 175M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE LCLARGE DATAFILE '+FNPRDDATA/fnprd/datafile/lclarge.dbf' SIZE 8M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
\b CREATE TABLESPACE MBAPP DATAFILE '+FNPRDDATA/fnprd/datafile/mbapp.dbf' SIZE 75M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\b0\par
\par
\b CREATE TABLESPACE MBLARGE DATAFILE '+FNPRDDATA/fnprd/datafile/mblarge.dbf' SIZE 128M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE MBDVLP DATAFILE '+FNPRDDATA/fnprd/datafile/mbdvlp.dbf' SIZE 5M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\b0\par
\par
CREATE TABLESPACE MGAPP DATAFILE '+FNPRDDATA/fnprd/datafile/mgapp.dbf' SIZE 144M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE MGLARGE DATAFILE '+FNPRDDATA/fnprd/datafile/mglarge.dbf' SIZE 7M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE MPAPP DATAFILE '+FNPRDDATA/fnprd/datafile/mpapp.dbf' SIZE 12M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE MPLARGE DATAFILE '+FNPRDDATA/fnprd/datafile/mplarge.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE MPWORK DATAFILE '+FNPRDDATA/fnprd/datafile/mpwork.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE OEAPP DATAFILE '+FNPRDDATA/fnprd/datafile/oeapp.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE OMAPP DATAFILE '+FNPRDDATA/fnprd/datafile/omapp.dbf' SIZE 55M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE OMLARGE DATAFILE '+FNPRDDATA/fnprd/datafile/omlarge.dbf' SIZE 27M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE OMWORK DATAFILE '+FNPRDDATA/fnprd/datafile/omwork.dbf' SIZE 367M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE PBAPP DATAFILE '+FNPRDDATA/fnprd/datafile/pbapp.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE PBIMAGE DATAFILE '+FNPRDDATA/fnprd/datafile/pbimage.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE PBLARGE DATAFILE '+FNPRDDATA/fnprd/datafile/pblarge.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE PBWORK DATAFILE '+FNPRDDATA/fnprd/datafile/pbwork.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE PCAPP DATAFILE '+FNPRDDATA/fnprd/datafile/pcapp.dbf' SIZE 84M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE PCARCH DATAFILE '+FNPRDDATA/fnprd/datafile/pcarch.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE PCLARGE DATAFILE '+FNPRDDATA/fnprd/datafile/pclarge.dbf' SIZE 47M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE PCWORK DATAFILE '+FNPRDDATA/fnprd/datafile/pcwork.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE PGMAPP DATAFILE '+FNPRDDATA/fnprd/datafile/pgmapp.dbf' SIZE 24M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE PGMLARGE DATAFILE '+FNPRDDATA/fnprd/datafile/pgmlarge.dbf' SIZE 9M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE PGMWORK DATAFILE '+FNPRDDATA/fnprd/datafile/pgmwork.dbf' SIZE 51M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE PIPSAPP DATAFILE '+FNPRDDATA/fnprd/datafile/pipsapp.dbf' SIZE 5M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE PIPSLRG DATAFILE '+FNPRDDATA/fnprd/datafile/pipslrg.dbf' SIZE 5M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE PIPSWORK DATAFILE '+FNPRDDATA/fnprd/datafile/pipswork.dbf' SIZE 5M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE PLAPP DATAFILE '+FNPRDDATA/fnprd/datafile/plapp.dbf' SIZE 37M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE PLLARGE DATAFILE '+FNPRDDATA/fnprd/datafile/pllarge.dbf' SIZE 29M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE PLWORK DATAFILE '+FNPRDDATA/fnprd/datafile/plwork.dbf' SIZE 7M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE POAPP DATAFILE '+FNPRDDATA/fnprd/datafile/poapp.dbf' SIZE 112M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE POLARGE DATAFILE '+FNPRDDATA/fnprd/datafile/polarge.dbf' SIZE 39M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE POWORK DATAFILE '+FNPRDDATA/fnprd/datafile/powork.dbf' SIZE 286M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE PSIMAGE DATAFILE '+FNPRDDATA/fnprd/datafile/psimage.dbf' SIZE 850M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE PSIMGR DATAFILE '+FNPRDDATA/fnprd/datafile/psimgr.dbf' SIZE 5M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
         \par
CREATE TABLESPACE PSINDEX DATAFILE '+FNPRDDATA/fnprd/datafile/psindex.dbf' SIZE 7500M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE PSWORK DATAFILE '+FNPRDDATA/fnprd/datafile/pswork.dbf' SIZE 5M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE PTAMSG DATAFILE '+FNPRDDATA/fnprd/datafile/ptamsg.dbf' SIZE 5M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE PTAPP DATAFILE '+FNPRDDATA/fnprd/datafile/ptapp.dbf' SIZE 21M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE PTAPPE DATAFILE '+FNPRDDATA/fnprd/datafile/ptappe.dbf' SIZE 10M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE PTAUDIT DATAFILE '+FNPRDDATA/fnprd/datafile/ptaudit.dbf' SIZE 5M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE PTCMSTAR DATAFILE '+FNPRDDATA/fnprd/datafile/ptcmstar.dbf' SIZE 5M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE PTLOCK DATAFILE '+FNPRDDATA/fnprd/datafile/ptlock.dbf' SIZE 5M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE PTPRC DATAFILE '+FNPRDDATA/fnprd/datafile/ptprc.dbf' SIZE 6M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE PTPRJWK DATAFILE '+FNPRDDATA/fnprd/datafile/ptprjwk.dbf' SIZE 10M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE PTRPTS DATAFILE '+FNPRDDATA/fnprd/datafile/ptrpts.dbf' SIZE 5M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE PTTBL DATAFILE '+FNPRDDATA/fnprd/datafile/pttbl.dbf' SIZE 175M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE PTTLRG DATAFILE '+FNPRDDATA/fnprd/datafile/pttlrg.dbf' SIZE 565M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE PTTREE DATAFILE '+FNPRDDATA/fnprd/datafile/pttree.dbf' SIZE 5M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE PTWORK DATAFILE '+FNPRDDATA/fnprd/datafile/ptwork.dbf' SIZE 8M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE PVAPP DATAFILE '+FNPRDDATA/fnprd/datafile/pvapp.dbf' SIZE 36M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE PYAPP DATAFILE '+FNPRDDATA/fnprd/datafile/pyapp.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE RBAPP DATAFILE '+FNPRDDATA/fnprd/datafile/rbapp.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE RBTEMP DATAFILE '+FNPRDDATA/fnprd/datafile/rbtemp.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE REAPP DATAFILE '+FNPRDDATA/fnprd/datafile/reapp.dbf' SIZE 10M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE REIMAGE DATAFILE '+FNPRDDATA/fnprd/datafile/reimage.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE RELARGE DATAFILE '+FNPRDDATA/fnprd/datafile/relarge.dbf' SIZE 10M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE REWORK DATAFILE '+FNPRDDATA/fnprd/datafile/rework.dbf' SIZE 9M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE ROAPP DATAFILE '+FNPRDDATA/fnprd/datafile/roapp.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE RSAPP DATAFILE '+FNPRDDATA/fnprd/datafile/rsapp.dbf' SIZE 37M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE RSFAPP DATAFILE '+FNPRDDATA/fnprd/datafile/rsfapp.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE RSLARGE DATAFILE '+FNPRDDATA/fnprd/datafile/rslarge.dbf' SIZE 12M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE RSWORK DATAFILE '+FNPRDDATA/fnprd/datafile/rswork.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE SACAPP DATAFILE '+FNPRDDATA/fnprd/datafile/sacapp.dbf' SIZE 7M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE SACLRGE DATAFILE '+FNPRDDATA/fnprd/datafile/saclrge.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE SPAPP DATAFILE '+FNPRDDATA/fnprd/datafile/spapp.dbf' SIZE 95M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE SPLARGE DATAFILE '+FNPRDDATA/fnprd/datafile/splarge.dbf' SIZE 10M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE TDAPP DATAFILE '+FNPRDDATA/fnprd/datafile/tdapp.dbf' SIZE 5M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE TDLARGE DATAFILE '+FNPRDDATA/fnprd/datafile/tdlarge.dbf' SIZE 6M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE TDWORK DATAFILE '+FNPRDDATA/fnprd/datafile/tdwork.dbf' SIZE 7M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE TLAPP DATAFILE '+FNPRDDATA/fnprd/datafile/tlapp.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE TLWORK DATAFILE '+FNPRDDATA/fnprd/datafile/tlwork.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE TPMAPP DATAFILE '+FNPRDDATA/fnprd/datafile/tpmapp.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE TRAPP DATAFILE '+FNPRDDATA/fnprd/datafile/trapp.dbf' SIZE 69M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE TRARCH DATAFILE '+FNPRDDATA/fnprd/datafile/trarch.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE TRIMAGE DATAFILE '+FNPRDDATA/fnprd/datafile/trimage.dbf' SIZE 4M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
       \par
CREATE TABLESPACE TRLARGE DATAFILE '+FNPRDDATA/fnprd/datafile/trlarge.dbf' SIZE 7M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE TRWORK DATAFILE '+FNPRDDATA/fnprd/datafile/trwork.dbf' SIZE 28M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
\b CREATE TABLESPACE UPAPP DATAFILE '+FNPRDDATA/fnprd/datafile/upapp.dbf' SIZE 12M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE UPLARGE DATAFILE '+FNPRDDATA/fnprd/datafile/uplarge.dbf' SIZE 10M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE UPWORK DATAFILE '+FNPRDDATA/fnprd/datafile/upwork.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\b0\par
\par
CREATE TABLESPACE WMAPP DATAFILE '+FNPRDDATA/fnprd/datafile/wmapp.dbf' SIZE 22M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE WMIMAGE DATAFILE '+FNPRDDATA/fnprd/datafile/wmimage.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE WMLARGE DATAFILE '+FNPRDDATA/fnprd/datafile/wmlarge.dbf' SIZE 20M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE WMWORK DATAFILE '+FNPRDDATA/fnprd/datafile/wmwork.dbf' SIZE 23M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE WSAPP DATAFILE '+FNPRDDATA/fnprd/datafile/wsapp.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
CREATE TABLESPACE WSLARGE DATAFILE '+FNPRDDATA/fnprd/datafile/wslarge.dbf' SIZE 2M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\par
\par
\b CREATE TABLESPACE FSTEMP DATAFILE '+FNPRDDATA/fnprd/datafile/fstemp.dbf' SIZE 75M\par
EXTENT MANAGEMENT LOCAL AUTOALLOCATE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED;\b0\par
\par
\par
}
 