INSERT INTO JCDETAIL (JCDT_COMP_CODE, JCDT_DSRC_COMP_CODE, JCDT_TYPE_CODE, JCDT_DSRC_CODE
                    , JCDT_JOB_CODE, JCDT_JOB_CTRL_CODE, JCDT_PHS_CODE, JCDT_PHS_CTRL_CODE
                    , JCDT_CAT_CODE, JCDT_CAT_CTRL_CODE, JCDT_JOUR_CODE, JCDT_BCH_NUM
                    , JCDT_SRC_CODE, JCDT_SRC_DESC, JCDT_REF_CODE, JCDT_REF_DATE, JCDT_REF_DESC
                    , JCDT_POST_DATE, JCDT_UNIT, JCDT_AMT, JCDT_WM_CODE, JCDT_USER
                    , JCDT_DATE_TIME_ENTRY, JCDT_DEPT_CODE, JCDT_ACC_CODE,JCDT_CREATE_DATE
                    , JCDT_CURR_CODE, JCDT_EXCHG_CURR_CODE, JCDT_EXCHG_RATE,  JCDT_EXCHG_AMT
                     )
SELECT INV_COMP_CODE, INV_COMP_CODE, 'B', 'JB', INV_JOB_CODE, 'ALL', '999-00000'
     , 'ALL', 'B', 'ALL', 'JB', INV_BCH_NUM, INV_CUST_CODE, SUBSTR(BP_NAME, 1, 30), INV_NUM, INV_DATE, INV_DESC1
     , INV_POST_DATE, 0, INV_AMT, 'NA', 'DA', SYSDATE, JOB_BILL_DEPT_CODE, JOB_BILL_ACC_CODE
     , SYSDATE, 'US', 'US', 1, INV_AMT
FROM DA.INVOICE
   , DA.BPARTNERS
   , DA.JCJOB
WHERE INV_BCH_NUM < 0
  AND INV_CUST_CODE = BP_CODE
  AND INV_JOB_CODE  = JOB_CODE
  AND INV_COMP_CODE = JOB_COMP_CODE