
SET VERIFY OFF 
SET serveroutput on size 1000000

accept db prompt 'This script has to be run in Which database:'

begin

insert into DA.JBCTRL@&db
select dept_comp_code,   JBCTRL_AR_JOUR_CODE,
  JBCTRL_INTERNAL_VEN_CODE,
  JBCTRL_INTERNAL_VEN_DESC,
  JBCTRL_AR_SELF_INV_SER_CODE,
  JBCTRL_AR_SC_INV_SER_CODE,
  JBCTRL_CONT_TYPE,
  JBCTRL_DEFAULT_BILLING_TYPE,
  JBCTRL_DEFAULT_INV_FORMAT_CODE,
  JBCTRL_AUTO_APPROVE_CONT_FLAG,
  JBCTRL_AUTO_APPROVE_INV_FLAG,
  JBCTRL_MAX_GROUP_CAT_CODE,
  JBCTRL_MAX_CONT_CAT_CODE,
  JBCTRL_DEFAULT_JB_MAP_CODE,
  JBCTRL_MAT_STORED_INTERNAL,
  JBCTRL_DEFAULT_BILL_RATE_TABLE,
  JBCTRL_DEFAULT_MIN_CODE,
  JBCTRL_CONT_INV_APPRV_FLAG,
  JBCTRL_AIA_LICENSE_FLAG,
  JBCTRL_REV_GEN_BURDENS_FLAG,
  JBCTRL_REV_GEN_JOUR_CODE,
  JBCTRL_PM_CONTACT_ROLE,
  JBCTRL_DEFERRAL_DELETE_FLAG,
  JBCTRL_DISP_CONT_BUDGCHNG_FLAG,
  JBCTRL_USE_JOB_DEPT_FLAG,
  JBCTRL_USE_AKA_NAME_FLAG,
  JBCTRL_DEFAULT_TAX_FROM_SUBJOB,
  JBCTRL_EXCL_NONINV_RECITS,
  JBCTRL_SC_RFP_COST_FLAG,
  JBCTRL_VOID_SC_MAN_RFP_FLAG,
  JBCTRL__IU__CREATE_DATE,
  JBCTRL__IU__CREATE_USER,
  JBCTRL__IU__UPDATE_DATE,
  JBCTRL__IU__UPDATE_USER,
  JBCTRL_REL_MORE_RET_FLAG,
  JBCTRL_W_CAT_NO_BILL_CODE_FLAG,
  JBCTRL_INVOICE_LEVEL_RET_FLAG,
  JBCTRL_BILL_UNPOSTED_RFP_FLAG,
  JBCTRL_POST_DATE_DFLT_SD_FLAG,
  JBCTRL_BILL_UNAPPRVD_CONT_FLAG,
  JBCTRL_OVERRIDE_CONT_BUDGET,
  JBCTRL_RETRIEVE_BILLING_NAME,
  JBCTRL_SET_SELF_PERF_FLAG from
(select distinct dept_comp_code 
 from dept@&db where dept_comp_code not in ('ZZ','01')),
(SELECT 
  JBCTRL_COMP_CODE,
  JBCTRL_AR_JOUR_CODE,
  JBCTRL_INTERNAL_VEN_CODE,
  JBCTRL_INTERNAL_VEN_DESC,
  JBCTRL_AR_SELF_INV_SER_CODE,
  JBCTRL_AR_SC_INV_SER_CODE,
  JBCTRL_CONT_TYPE,
  JBCTRL_DEFAULT_BILLING_TYPE,
  JBCTRL_DEFAULT_INV_FORMAT_CODE,
  JBCTRL_AUTO_APPROVE_CONT_FLAG,
  JBCTRL_AUTO_APPROVE_INV_FLAG,
  JBCTRL_MAX_GROUP_CAT_CODE,
  JBCTRL_MAX_CONT_CAT_CODE,
  JBCTRL_DEFAULT_JB_MAP_CODE,
  JBCTRL_MAT_STORED_INTERNAL,
  JBCTRL_DEFAULT_BILL_RATE_TABLE,
  JBCTRL_DEFAULT_MIN_CODE,
  JBCTRL_CONT_INV_APPRV_FLAG,
  JBCTRL_AIA_LICENSE_FLAG,
  JBCTRL_REV_GEN_BURDENS_FLAG,
  JBCTRL_REV_GEN_JOUR_CODE,
  JBCTRL_PM_CONTACT_ROLE,
  JBCTRL_DEFERRAL_DELETE_FLAG,
  JBCTRL_DISP_CONT_BUDGCHNG_FLAG,
  JBCTRL_USE_JOB_DEPT_FLAG,
  JBCTRL_USE_AKA_NAME_FLAG,
  JBCTRL_DEFAULT_TAX_FROM_SUBJOB,
  JBCTRL_EXCL_NONINV_RECITS,
  JBCTRL_SC_RFP_COST_FLAG,
  JBCTRL_VOID_SC_MAN_RFP_FLAG,
  JBCTRL__IU__CREATE_DATE,
  JBCTRL__IU__CREATE_USER,
  JBCTRL__IU__UPDATE_DATE,
  JBCTRL__IU__UPDATE_USER,
  JBCTRL_REL_MORE_RET_FLAG,
  JBCTRL_W_CAT_NO_BILL_CODE_FLAG,
  JBCTRL_INVOICE_LEVEL_RET_FLAG,
  JBCTRL_BILL_UNPOSTED_RFP_FLAG,
  JBCTRL_POST_DATE_DFLT_SD_FLAG,
  JBCTRL_BILL_UNAPPRVD_CONT_FLAG,
  JBCTRL_OVERRIDE_CONT_BUDGET,
  JBCTRL_RETRIEVE_BILLING_NAME,
  JBCTRL_SET_SELF_PERF_FLAG
FROM JBCTRL@&db 
where jbctrl_comp_code = '01'
);

exception
WHEN OTHERS 
THEN
DBMS_OUTPUT.PUT_LINE (SQLERRM);

end;
/