-- **************************************************************
--        Confidentiality Information:                           
--                                                               
-- This module contains confidential and proprietary information 
-- of Oracle; it is not to be copied, reproduced, or transmitted 
-- in any form, by any means, in whole or in part, nor is it to  
-- be used for any purpose other than that for which it is       
-- expressly provided under the applicable license agreement.    
--                                                               
-- Copyright (C) 2006 Oracle. All Rights Reserved.               
-- **************************************************************
REMARK * This script is used to create tablespaces for the PeopleSoft 9 HRMS Products
REMARK * on Oracle UNIX.
REMARK * Date last modified: 01/30/2007

REMARK * NOTE: The sizing of the tablespaces here are only sample sizes that will
REMARK *      hold the demo database tables.  This is not sized correctly for a
REMARK *      production database.
REMARK *      production database.
       
REMARK * Users can choose to use the autoextending tablespace feature.
REMARK * The syntax is at the end of this script.

 

set echo on
spool hcddl.log

CREATE TABLESPACE AAAPP DATAFILE '+HRDMODATA' SIZE 21M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE AALARGE DATAFILE '+HRDMODATA' SIZE 6M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE ADAPP DATAFILE '+HRDMODATA' SIZE 60M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE AMAPP DATAFILE '+HRDMODATA' SIZE 42M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE AVAPP DATAFILE '+HRDMODATA' SIZE 19M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE BDAPP DATAFILE '+HRDMODATA' SIZE 2M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE BNAPP DATAFILE '+HRDMODATA' SIZE 52M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE BNLARGE DATAFILE '+HRDMODATA' SIZE 17M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE CCAPP DATAFILE '+HRDMODATA' SIZE 250M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE COAPP DATAFILE '+HRDMODATA' SIZE 6M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE CUAUDIT DATAFILE '+HRDMODATA' SIZE 2M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE CULARG1 DATAFILE '+HRDMODATA' SIZE 2M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE CULARG2 DATAFILE '+HRDMODATA' SIZE 2M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE CULARG3 DATAFILE '+HRDMODATA' SIZE 2M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE CULARGE DATAFILE '+HRDMODATA' SIZE 5M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE DIAPP DATAFILE '+HRDMODATA' SIZE 2M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE DTAPP DATAFILE '+HRDMODATA' SIZE 92M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOAPP DATAFILE '+HRDMODATA' SIZE 25M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOBFAPP DATAFILE '+HRDMODATA' SIZE 2M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOCFAPP DATAFILE '+HRDMODATA' SIZE 20M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOCMAPP DATAFILE '+HRDMODATA' SIZE 2M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOCMLRG DATAFILE '+HRDMODATA' SIZE 2M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOCMWRK DATAFILE '+HRDMODATA' SIZE 2M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOCUAPP DATAFILE '+HRDMODATA' SIZE 2M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOCULRG DATAFILE '+HRDMODATA' SIZE 2M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EODSAPP DATAFILE '+HRDMODATA' SIZE 6M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EODSLRG DATAFILE '+HRDMODATA' SIZE 2M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOECAPP DATAFILE '+HRDMODATA' SIZE 6M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOECLRG DATAFILE '+HRDMODATA' SIZE 2M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOECWRK DATAFILE '+HRDMODATA' SIZE 2M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOEIAPP DATAFILE '+HRDMODATA' SIZE 2M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOEILRG DATAFILE '+HRDMODATA' SIZE 2M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOEWAPP DATAFILE '+HRDMODATA' SIZE 9M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOEWLRG DATAFILE '+HRDMODATA' SIZE 2M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOEWWRK DATAFILE '+HRDMODATA' SIZE 2M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOIUAPP DATAFILE '+HRDMODATA' SIZE 2M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOIULRG DATAFILE '+HRDMODATA' SIZE 2M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOIUWRK DATAFILE '+HRDMODATA' SIZE 2M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOLARGE DATAFILE '+HRDMODATA' SIZE 7M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOLTAPP DATAFILE '+HRDMODATA' SIZE 5M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOPPAPP DATAFILE '+HRDMODATA' SIZE 6M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOPPLRG DATAFILE '+HRDMODATA' SIZE 2M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOTPAPP DATAFILE '+HRDMODATA' SIZE 2M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EOTPLRG DATAFILE '+HRDMODATA' SIZE 2M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EPAPP DATAFILE '+HRDMODATA' SIZE 10M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE EPLARGE DATAFILE '+HRDMODATA' SIZE 5M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE ERAPP DATAFILE '+HRDMODATA' SIZE 12M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE ERLARGE DATAFILE '+HRDMODATA' SIZE 2M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE ERWORK DATAFILE '+HRDMODATA' SIZE 2M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE FAAPP DATAFILE '+HRDMODATA' SIZE 300M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE FALARGE DATAFILE '+HRDMODATA' SIZE 14M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE FGAPP DATAFILE '+HRDMODATA' SIZE 35M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE FGLARGE DATAFILE '+HRDMODATA' SIZE 2M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE FSAPP DATAFILE '+HRDMODATA' SIZE 4M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE GIAPP DATAFILE '+HRDMODATA' SIZE 7M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE GPAPP DATAFILE '+HRDMODATA' SIZE 1000M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE GPDEAPP DATAFILE '+HRDMODATA' SIZE 2M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE HPAPP DATAFILE '+HRDMODATA' SIZE 65M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE HRAPP DATAFILE '+HRDMODATA' SIZE 350M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE HRAPP1 DATAFILE '+HRDMODATA' SIZE 17M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE HRAPP2 DATAFILE '+HRDMODATA' SIZE 17M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE HRAPP3 DATAFILE '+HRDMODATA' SIZE 6M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE HRAPP4 DATAFILE '+HRDMODATA' SIZE 16M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE HRAPP5 DATAFILE '+HRDMODATA' SIZE 13M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE HRAPP6 DATAFILE '+HRDMODATA' SIZE 35M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE HRAPP7 DATAFILE '+HRDMODATA' SIZE 3M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE HRIMAGE DATAFILE '+HRDMODATA' SIZE 2M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE HRLARG1 DATAFILE '+HRDMODATA' SIZE 2M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE HRLARGE DATAFILE '+HRDMODATA' SIZE 91M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE HRSAPP DATAFILE '+HRDMODATA' SIZE 51M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE HRSARCH DATAFILE '+HRDMODATA' SIZE 2M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE HRSLARGE DATAFILE '+HRDMODATA' SIZE 6M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE HRSWORK DATAFILE '+HRDMODATA' SIZE 14M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE HRWORK DATAFILE '+HRDMODATA' SIZE 20M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE HTAPP DATAFILE '+HRDMODATA' SIZE 2M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE INAPP DATAFILE '+HRDMODATA' SIZE 2M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PAAPP DATAFILE '+HRDMODATA' SIZE 59M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PALARGE DATAFILE '+HRDMODATA' SIZE 6M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PCAPP DATAFILE '+HRDMODATA' SIZE 4M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PCLARGE DATAFILE '+HRDMODATA' SIZE 5M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PIAPP DATAFILE '+HRDMODATA' SIZE 8M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PILARGE DATAFILE '+HRDMODATA' SIZE 2M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PIWORK DATAFILE '+HRDMODATA' SIZE 3M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE POAPP DATAFILE '+HRDMODATA' SIZE 33M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PSIMAGE DATAFILE '+HRDMODATA' SIZE 1000M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PSIMGR DATAFILE '+HRDMODATA' SIZE 3M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PSINDEX DATAFILE '+HRDMODATA' SIZE 6000M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTAMSG DATAFILE '+HRDMODATA' SIZE 43M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTAPP DATAFILE '+HRDMODATA' SIZE 50M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTAPPE DATAFILE '+HRDMODATA' SIZE 4M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTAUDIT DATAFILE '+HRDMODATA' SIZE 2M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTCMSTAR DATAFILE '+HRDMODATA' SIZE 3M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTLOCK DATAFILE '+HRDMODATA' SIZE 3M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTPRC DATAFILE '+HRDMODATA' SIZE 12M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTPRJWK DATAFILE '+HRDMODATA' SIZE 8M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTRPTS DATAFILE '+HRDMODATA' SIZE 3M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTTBL DATAFILE '+HRDMODATA' SIZE 264M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTTLRG DATAFILE '+HRDMODATA' SIZE 500M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTTREE DATAFILE '+HRDMODATA' SIZE 6M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PTWORK DATAFILE '+HRDMODATA' SIZE 12M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PVAPP DATAFILE '+HRDMODATA' SIZE 4M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PY0LRG DATAFILE '+HRDMODATA' SIZE 105M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PYAPP DATAFILE '+HRDMODATA' SIZE 110M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PYLARGE DATAFILE '+HRDMODATA' SIZE 3M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE PYWORK DATAFILE '+HRDMODATA' SIZE 30M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE SAAPP DATAFILE '+HRDMODATA' SIZE 300M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE SACAPP DATAFILE '+HRDMODATA' SIZE 5M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE SALARGE DATAFILE '+HRDMODATA' SIZE 8M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE SRAPP DATAFILE '+HRDMODATA' SIZE 151M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE STAPP DATAFILE '+HRDMODATA' SIZE 32M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE STLARGE DATAFILE '+HRDMODATA' SIZE 12M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE STWORK DATAFILE '+HRDMODATA' SIZE 17M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE TLAPP DATAFILE '+HRDMODATA' SIZE 100M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE TLLARGE DATAFILE '+HRDMODATA' SIZE 30M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE TLWORK DATAFILE '+HRDMODATA' SIZE 550M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE WAAPP DATAFILE '+HRDMODATA' SIZE 2M AUTOEXTEND ON NEXT 128K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO
/

spool off
