SELECT K.BUSINESS_UNIT, K.DEPTID, C.EMPLID, K.POSITION_NBR, K.JOBCODE, K.DESCR, C.ANNL_BENEF_BASE_RT, C.GRADE, K.FULL_PART_TIME, TO_CHAR(C.JOB_ENTRY_DT,'YYYY-MM-DD'), N.MIN_RT_ANNUAL, N.MAX_RT_ANNUAL, K.REPORTS_TO, D.DESCRSHORT, K.UNION_CD, K.MAX_HEAD_COUNT, K.BENEFIT_PROGRAM, K.MB_SAFETY_SENSITIV, C.SAL_ADMIN_PLAN, C.FLSA_STATUS, C.EMPL_STATUS, B.EEO4CODE, F.SEX, I.DESCR, TO_CHAR(C.ACTION_DT,'YYYY-MM-DD'), TO_CHAR(O.HIRE_DT,'YYYY-MM-DD'), P.ETHNIC_GRP_CD, F.NAME_PSFORMAT 
  FROM PS_MB_JOB_VW C, PS_MB_PERSONAL_VW F, PS_MB_POSITION_VW K, PS_MB_JOBCODE3_VW B, PS_MB_UNION_VW D, PS_MB_POSITION_VW I, PS_SAL_GRADE_TBL N, PS_EMPLOYMENT O, PS_DIVERS_ETHNIC P 
  WHERE K.POSITION_NBR = C.POSITION_NBR 
     AND F.EMPLID = C.EMPLID 
     AND C.EFFDT = 
        (SELECT MAX(C_ED.EFFDT) FROM PS_MB_JOB_VW C_ED 
        WHERE C.EMPLID = C_ED.EMPLID 
          AND C.EMPL_RCD = C_ED.EMPL_RCD 
          AND C_ED.EFFDT <= SYSDATE) 
    AND C.EFFSEQ = 
        (SELECT MAX(C_ES.EFFSEQ) FROM PS_MB_JOB_VW C_ES 
        WHERE C.EMPLID = C_ES.EMPLID 
          AND C.EMPL_RCD = C_ES.EMPL_RCD 
          AND C.EFFDT = C_ES.EFFDT) 
     AND C.EMPL_STATUS IN ('A','L','P') 
     AND B.JOBCODE = K.JOBCODE 
     AND D.UNION_CD = K.UNION_CD 
     AND K.EFFDT = 
        (SELECT MAX(K_ED.EFFDT) FROM PS_MB_POSITION_VW K_ED 
        WHERE K.POSITION_NBR = K_ED.POSITION_NBR 
          AND K_ED.EFFDT <= SYSDATE) 
     AND I.POSITION_NBR = K.REPORTS_TO 
     AND I.EFFDT = 
        (SELECT MAX(I_ED.EFFDT) FROM PS_MB_POSITION_VW I_ED 
        WHERE I.POSITION_NBR = I_ED.POSITION_NBR 
          AND I_ED.EFFDT <= SYSDATE) 
     AND C.JOBCODE NOT IN ('090000','098500') 
     AND N.EFFDT = 
        (SELECT MAX(N_ED.EFFDT) FROM PS_SAL_GRADE_TBL N_ED 
        WHERE N.SETID = N_ED.SETID 
          AND N.SAL_ADMIN_PLAN = N_ED.SAL_ADMIN_PLAN 
          AND N.GRADE = N_ED.GRADE 
          AND N_ED.EFFDT <= SYSDATE) 
     AND N.SAL_ADMIN_PLAN = C.SAL_ADMIN_PLAN 
     AND N.GRADE = C.GRADE 
     AND K.DESCR NOT LIKE 'Training-%' 
     AND K.DESCR NOT LIKE 'Recruitment%' 
     AND F.EMPLID = O.EMPLID 
     AND F.EMPLID = P.EMPLID 
UNION 
SELECT A.BUSINESS_UNIT, A.DEPTID,  '', A.POSITION_NBR, A.JOBCODE, A.DESCR, 0.0, L.GRADE, A.FULL_PART_TIME,  '', M.MIN_RT_ANNUAL, M.MAX_RT_ANNUAL, A.REPORTS_TO, G.DESCRSHORT, A.UNION_CD, A.MAX_HEAD_COUNT, A.BENEFIT_PROGRAM, A.MB_SAFETY_SENSITIV, L.SAL_ADMIN_PLAN, L.FLSA_STATUS,  '', L.EEO4CODE,  '', J.DESCR, TO_CHAR(A.ACTION_DT,'YYYY-MM-DD'), ' ',  '',  '' 
  FROM PS_POSITION_DATA A, PS_MB_JOBCODE3_VW L, PS_MB_UNION_VW G, PS_MB_POSITION_VW J, PS_SAL_GRADE_TBL M 
  WHERE NOT EXISTS (SELECT 'X' 
  FROM PS_MB_JOB_VW E 
  WHERE E.POSITION_NBR = A.POSITION_NBR 
     AND E.EFFDT = 
        (SELECT MAX(E_ED.EFFDT) FROM PS_MB_JOB_VW E_ED 
        WHERE E.EMPLID = E_ED.EMPLID 
          AND E.EMPL_RCD = E_ED.EMPL_RCD 
          AND E_ED.EFFDT <= SYSDATE) 
    AND E.EFFSEQ = 
        (SELECT MAX(E_ES.EFFSEQ) FROM PS_MB_JOB_VW E_ES 
        WHERE E.EMPLID = E_ES.EMPLID 
          AND E.EMPL_RCD = E_ES.EMPL_RCD 
          AND E.EFFDT = E_ES.EFFDT) 
     AND E.EMPL_STATUS IN ('A','L','P')) 
     AND A.EFFDT = 
        (SELECT MAX(A_ED.EFFDT) FROM PS_POSITION_DATA A_ED 
        WHERE A.POSITION_NBR = A_ED.POSITION_NBR 
          AND A_ED.EFFDT <= SYSDATE) 
     AND A.JOBCODE = L.JOBCODE 
     AND G.UNION_CD = A.UNION_CD 
     AND A.EFF_STATUS = 'A' 
     AND J.EFFDT = 
        (SELECT MAX(J_ED.EFFDT) FROM PS_MB_POSITION_VW J_ED 
        WHERE J.POSITION_NBR = J_ED.POSITION_NBR 
          AND J_ED.EFFDT <= SYSDATE) 
     AND J.POSITION_NBR = A.REPORTS_TO 
     AND L.JOBCODE NOT IN ('090000','098500') 
     AND M.EFFDT = 
        (SELECT MAX(M_ED.EFFDT) FROM PS_SAL_GRADE_TBL M_ED 
        WHERE M.SETID = M_ED.SETID 
          AND M.SAL_ADMIN_PLAN = M_ED.SAL_ADMIN_PLAN 
          AND M.GRADE = M_ED.GRADE 
          AND M_ED.EFFDT <= A.EFFDT) 
     AND M.SAL_ADMIN_PLAN = L.SAL_ADMIN_PLAN 
     AND M.GRADE = L.GRADE 
  ORDER BY 1, 5
