select distinct 1 as Col_Id
, 'AAA' as Col_Id1
, PHY_COMP_CODE
, PHY_PRN_CODE
--, PHY_PPR_YEAR
--, PHY_PPR_PERIOD
, /*TO_DATE(*/PPRD.PPR_END_DATE/*,'YYYY-MM-DD')*/ PPR_END_DATE
, 'SSN           PARTICIPANT NAME              401K      MATCH     PROFIT              BIRTH     HIRE      ENTRY     TERM      ADDRESS                                                     CITY                ST   ZIP CODE' Col_Data
FROM DA.PYEMPPAYHIST PHST
   , DA.PYCOMPAYPRD PPRD 
WHERE PHST.PHY_COMP_CODE = PPRD.PPR_COMP_CODE 
AND PHST.PHY_PRN_CODE = PPRD.PPR_PRN_CODE 
AND PHST.PHY_PPR_YEAR = PPRD.PPR_YEAR     
AND PHST.PHY_PPR_PERIOD = PPRD.PPR_PERIOD
UNION 
SELECT 2 as Col_Id,
        EMP_LAST_NAME Col_Id1,
        PHY_COMP_CODE,
        PHY_PRN_CODE,
--        PHY_PPR_YEAR,
--        PHY_PPR_PERIOD,
        /*TO_DATE(*/PPRD.PPR_END_DATE/*,'YYYY-MM-DD')*/ PPR_END_DATE,
        RPAD(EMP_SIN_NO, 14)
     || RPAD(EMP_LAST_NAME || ', ' || EMP_FIRST_NAME || ' ' || EMP_MIDDLE_NAME, 30) 
     || LPAD(LTRIM(REPLACE(TO_CHAR(SUM(PHY_PAY_AMOUNT)*-1, '9999999999.00'), '.','')), 10)  
     || LPAD(' ', 30)
     || RPAD(TO_CHAR(EMP_DATE_OF_BIRTH, 'MM-DD-YYYY'), 10) 
     || LPAD(' ', 30)
     || RPAD(UPPER(EMP_ADDRESS1), 60)  
     || RPAD(UPPER(EMP_ADDRESS3), 20)  
     || RPAD(UPPER(EMP_STATE_CODE), 5) 
     || SUBSTR(EMP_ZIP_CODE, 1, 5)        Col_Data
FROM DA.PYEMPLOYEE_TABLE
   , DA.PYEMPPAYHIST PHST
   , DA.PYCOMPAYPRD PPRD 
WHERE EMP_NO = PHST.PHY_EMP_NO
--AND PHY_EMP_NO = '01015'
AND PHST.PHY_TRAN_TYPE = 'DE'
AND PHST.PHY_TRAN_CODE IN ('401C', '401K')
AND PHST.PHY_COMP_CODE = PPRD.PPR_COMP_CODE 
AND PHST.PHY_PRN_CODE = PPRD.PPR_PRN_CODE 
AND PHST.PHY_PPR_YEAR = PPRD.PPR_YEAR     
AND PHST.PHY_PPR_PERIOD = PPRD.PPR_PERIOD
--AND PHY_COMP_CODE = '&Company_code'
--AND PHY_PRN_CODE = '&Prn_code'
--AND PHY_PPR_YEAR = '&Pay_Year'
--AND PHY_PPR_PERIOD = '&Pay_period'
GROUP BY RPAD(EMP_SIN_NO, 14), EMP_LAST_NAME
       , RPAD(EMP_LAST_NAME || ', ' || EMP_FIRST_NAME || ' ' || EMP_MIDDLE_NAME, 30)
       , LPAD('', 30)
       , RPAD(TO_CHAR(EMP_DATE_OF_BIRTH, 'MM-DD-YYYY'), 10)
       , RPAD(UPPER(EMP_ADDRESS1), 60)
       , RPAD(UPPER(EMP_ADDRESS3), 20)
       , RPAD(UPPER(EMP_STATE_CODE), 5)
       , SUBSTR(EMP_ZIP_CODE, 1, 5)
       , PHY_COMP_CODE
       , PHY_PRN_CODE
       , PHY_PPR_YEAR
       , PHY_PPR_PERIOD
       , /*TO_DATE(*/PPRD.PPR_END_DATE/*,'YYYY-MM-DD')*/ 
--ORDER BY RPAD(EMP_LAST_NAME || ', ' || EMP_FIRST_NAME || ' ' || EMP_MIDDLE_NAME, 30)


select distinct phy_ppr_year from DA.PYEMPPAYHIST

select * from DA.PYCOMPAYPRD