
  CREATE OR REPLACE FORCE VIEW "DA1"."EMPLOYEE_PAY_CADVW" ("EPC_ROW_ORDER", "EPC_START_DATE", "EPC_END_DATE", "EPC_EMP_NO1", "EPC_COMP_CODE", "EPC_EMP_NO2", "EPC_PERIOD", "EPC_FNAME_TSH_DATE", "EPC_SHIFT_CODE", "EPC_LNAME_TSH_NH_RATE_CODE", "EPC_MNAME_TSH_COMP_CODE", "EPC_JOB_CODE", "EPC_PHASE", "EPC_CATEGORY", "EPC_WORK_LOCATION", "EPC_TRADE_CODE", "EPC_NORMAL_HOURS", "EPC_NH_PAY_RATE", "EPC_NH_PAY_AMT", "EPC_WCB_CODE") AS 
  SELECT ROW_ORDER, PPR_START_DATE, PPR_END_DATE, TSH_EMP_NO1, TSH_COMP_CODE, TSH_EMP_NO2
     , PPR_PERIOD, EMP_FNAME_TSH_DATE, TSH_SHIFT_CODE, EMP_LNAME_TSH_NH_RATE_CODE
     , EMP_MNAME_TSH_COMP_CODE, TSH_JOB_CODE, TSH_PHASE, TSH_CATEGORY, TSH_WORK_LOCATION
     , TSH_TRADE_CODE, TSH_NORMAL_HOURS, TSH_NH_PAY_RATE, TSH_NH_PAY_AMT, TSH_WCB_CODE
FROM     
(
SELECT 1                           ROW_ORDER
     , PPRD.PPR_START_DATE         PPR_START_DATE
     , PPRD.PPR_END_DATE           PPR_END_DATE
     , PHST.TSH_EMP_NO             TSH_EMP_NO1
     , PHST.TSH_COMP_CODE          TSH_COMP_CODE
     
     , 'EMP NO:' || PHST.TSH_EMP_NO        TSH_EMP_NO2
     , 'EMP NO:' || PHST.TSH_EMP_NO        PPR_PERIOD 
     , UPPER(EMP.EMP_FIRST_NAME) || ', '   EMP_FNAME_TSH_DATE
     , NULL                        TSH_SHIFT_CODE
     , UPPER(EMP.EMP_LAST_NAME)  || ', '   EMP_LNAME_TSH_NH_RATE_CODE
     , UPPER(EMP.EMP_MIDDLE_NAME)  EMP_MNAME_TSH_COMP_CODE
     , NULL                        TSH_JOB_CODE   
     , NULL                        TSH_PHASE       
     , NULL                        TSH_CATEGORY
     , NULL                        TSH_WORK_LOCATION
     , NULL                        TSH_TRADE_CODE
     , NULL                        TSH_NORMAL_HOURS
     , NULL                        TSH_NH_PAY_RATE
     , NULL                        TSH_NH_PAY_AMT
     , NULL                        TSH_WCB_CODE
FROM DA.PYEMPTIMSHT PHST 
   , DA.PYCOMPAYPRD PPRD 
   , DA.PYEMPSALADJ SADJ 
   , DA.PYEMPLOYEE_TABLE EMP
WHERE PHST.TSH_COMP_CODE NOT IN ('ZZ')
--AND PHST.TSH_EMP_NO       = '12049'
AND PPRD.PPR_COMP_CODE   = PHST.TSH_COMP_CODE 
AND PPRD.PPR_PRN_CODE    = PHST.TSH_PRN_CODE 
AND PPRD.PPR_YEAR        = PHST.TSH_PPR_YEAR 
AND PPRD.PPR_PERIOD      = PHST.TSH_PPR_PERIOD
AND PPRD.PPR_COMP_CODE   = SADJ.SAD_COMP_CODE (+) 
AND PPRD.PPR_PRN_CODE    = SADJ.SAD_PRN_CODE  (+)
AND PPRD.PPR_YEAR        = SADJ.SAD_PPR_YEAR  (+)
AND PPRD.PPR_PERIOD      = SADJ.SAD_PPR_PERIOD(+)
AND PHST.TSH_JOB_CODE   >= '90002'
AND EMP.EMP_NO           = PHST.TSH_EMP_NO
/*AND NVL(PHST.TSH_NH_PAY_AMT, 0) 
  + NVL(PHST.TSH_OT_PAY_AMT, 0)
  + NVL(PHST.TSH_DOT_PAY_AMT, 0)
  + NVL(PHST.TSH_OH_PAY_AMT, 0)
  + NVL(SADJ.SAD_AMOUNT, 0) <> 0
  */
GROUP BY PPRD.PPR_START_DATE, PPRD.PPR_END_DATE, PHST.TSH_EMP_NO, PHST.TSH_COMP_CODE 
     , PHST.TSH_EMP_NO, EMP.EMP_FIRST_NAME, EMP.EMP_LAST_NAME, EMP.EMP_MIDDLE_NAME

UNION ALL

SELECT 2

     , PPRD.PPR_START_DATE
     , PPRD.PPR_END_DATE
     , PHST.TSH_EMP_NO
     , PHST.TSH_COMP_CODE
     
     , 'EMP NO:' || PHST.TSH_EMP_NO
     , TO_CHAR(PPRD.PPR_PERIOD )
     , TO_CHAR(PHST.TSH_DATE, 'MM-DD-YY')
     , PHST.TSH_SHIFT_CODE
     , PHST.TSH_NH_RATE_CODE
     , PHST.TSH_COMP_CODE
     , PHST.TSH_JOB_CODE
     , PHST.TSH_PHASE
     , PHST.TSH_CATEGORY
     , PHST.TSH_WORK_LOCATION
     , PHST.TSH_TRADE_CODE
     , PHST.TSH_NORMAL_HOURS
     , PHST.TSH_NH_PAY_RATE
     , PHST.TSH_NH_PAY_AMT
     , PHST.TSH_WCB_CODE
FROM DA.PYEMPTIMSHT PHST 
   , DA.PYCOMPAYPRD PPRD 
--   , DA.PYEMPLOYEE_TABLE EMP
WHERE PHST.TSH_COMP_CODE NOT IN ('ZZ')
AND NVL(PHST.TSH_NH_PAY_AMT, 0)  <> 0
--AND PHST.TSH_EMP_NO       = '12049'
AND PPRD.PPR_COMP_CODE            = PHST.TSH_COMP_CODE 
AND PPRD.PPR_PRN_CODE             = PHST.TSH_PRN_CODE 
AND PPRD.PPR_YEAR                 = PHST.TSH_PPR_YEAR 
AND PPRD.PPR_PERIOD               = PHST.TSH_PPR_PERIOD
AND PHST.TSH_JOB_CODE            >= '90002'
--AND EMP.EMP_NO            = PHST.TSH_EMP_NO

UNION ALL

SELECT 3

     , PPRD.PPR_START_DATE
     , PPRD.PPR_END_DATE
     , PHST.TSH_EMP_NO
     , PHST.TSH_COMP_CODE
     
     , 'EMP NO:' || PHST.TSH_EMP_NO
     , TO_CHAR(PPRD.PPR_PERIOD) 
     , TO_CHAR(PHST.TSH_DATE, 'MM-DD-YY')
     , PHST.TSH_SHIFT_CODE
     , PHST.TSH_OT_RATE_CODE
     , PHST.TSH_COMP_CODE
     , PHST.TSH_JOB_CODE
     , PHST.TSH_PHASE
     , PHST.TSH_CATEGORY
     , PHST.TSH_WORK_LOCATION
     , PHST.TSH_TRADE_CODE
     , PHST.TSH_OT_HOURS
     , PHST.TSH_OT_PAY_RATE
     , PHST.TSH_OT_PAY_AMT
     , PHST.TSH_WCB_CODE
FROM DA.PYEMPTIMSHT PHST 
   , DA.PYCOMPAYPRD PPRD 
--   , DA.PYEMPLOYEE_TABLE EMP
WHERE PHST.TSH_COMP_CODE NOT IN ('ZZ')
AND NVL(PHST.TSH_OT_PAY_AMT, 0)  <> 0
--AND PHST.TSH_EMP_NO       = '12049'
AND PPRD.PPR_COMP_CODE         = PHST.TSH_COMP_CODE 
AND PPRD.PPR_PRN_CODE          = PHST.TSH_PRN_CODE 
AND PPRD.PPR_YEAR              = PHST.TSH_PPR_YEAR 
AND PPRD.PPR_PERIOD            = PHST.TSH_PPR_PERIOD
AND PHST.TSH_JOB_CODE         >= '90002'
--AND EMP.EMP_NO            = PHST.TSH_EMP_NO

UNION ALL

SELECT 4
     , PPRD.PPR_START_DATE
     , PPRD.PPR_END_DATE
     , PHST.TSH_EMP_NO
     , PHST.TSH_COMP_CODE
     
     , 'EMP NO:' || PHST.TSH_EMP_NO
     , TO_CHAR(PPRD.PPR_PERIOD) 
     , TO_CHAR(PHST.TSH_DATE, 'MM-DD-YY')
     , PHST.TSH_SHIFT_CODE
     , PHST.TSH_DOT_RATE_CODE
     , PHST.TSH_COMP_CODE
     , PHST.TSH_JOB_CODE
     , PHST.TSH_PHASE
     , PHST.TSH_CATEGORY
     , PHST.TSH_WORK_LOCATION
     , PHST.TSH_TRADE_CODE
     , PHST.TSH_DOT_HOURS
     , PHST.TSH_DOT_PAY_RATE
     , PHST.TSH_DOT_PAY_AMT
     , PHST.TSH_WCB_CODE
FROM DA.PYEMPTIMSHT PHST 
   , DA.PYCOMPAYPRD PPRD 
--   , DA.PYEMPLOYEE_TABLE EMP
WHERE PHST.TSH_COMP_CODE NOT IN ('ZZ')
AND NVL(PHST.TSH_DOT_PAY_AMT, 0) <> 0
--AND PHST.TSH_EMP_NO       = '12049'
AND PPRD.PPR_COMP_CODE         = PHST.TSH_COMP_CODE 
AND PPRD.PPR_PRN_CODE          = PHST.TSH_PRN_CODE 
AND PPRD.PPR_YEAR              = PHST.TSH_PPR_YEAR 
AND PPRD.PPR_PERIOD            = PHST.TSH_PPR_PERIOD
AND PHST.TSH_JOB_CODE         >= '90002'
--AND EMP.EMP_NO            = PHST.TSH_EMP_NO

UNION ALL

SELECT 5
     , PPRD.PPR_START_DATE
     , PPRD.PPR_END_DATE
     , PHST.TSH_EMP_NO
     , PHST.TSH_COMP_CODE
     
     , 'EMP NO:' || PHST.TSH_EMP_NO
     , TO_CHAR(PPRD.PPR_PERIOD)
     , TO_CHAR(PHST.TSH_DATE, 'MM-DD-YY')
     , PHST.TSH_SHIFT_CODE
     , PHST.TSH_OH_RATE_CODE
     , PHST.TSH_COMP_CODE
     , PHST.TSH_JOB_CODE
     , PHST.TSH_PHASE
     , PHST.TSH_CATEGORY
     , PHST.TSH_WORK_LOCATION
     , PHST.TSH_TRADE_CODE
     , PHST.TSH_OTHER_HOURS
     , PHST.TSH_OH_PAY_RATE
     , PHST.TSH_OH_PAY_AMT
     , PHST.TSH_WCB_CODE
FROM DA.PYEMPTIMSHT PHST 
   , DA.PYCOMPAYPRD PPRD 
--   , DA.PYEMPLOYEE_TABLE EMP
WHERE PHST.TSH_COMP_CODE NOT IN ('ZZ')
AND NVL(PHST.TSH_OH_PAY_AMT, 0) <> 0
--AND PHST.TSH_EMP_NO       = '12049'
AND PPRD.PPR_COMP_CODE        = PHST.TSH_COMP_CODE 
AND PPRD.PPR_PRN_CODE         = PHST.TSH_PRN_CODE 
AND PPRD.PPR_YEAR             = PHST.TSH_PPR_YEAR 
AND PPRD.PPR_PERIOD           = PHST.TSH_PPR_PERIOD
AND PHST.TSH_JOB_CODE        >= '90002'
--AND EMP.EMP_NO            = PHST.TSH_EMP_NO

UNION ALL

SELECT 6
     , PPRD.PPR_START_DATE
     , PPRD.PPR_END_DATE
     , SADJ.SAD_EMP_NO
     , SADJ.SAD_COMP_CODE
     
     , 'EMP NO:' || SADJ.SAD_EMP_NO
     , TO_CHAR(PPRD.PPR_PERIOD) 
     , TO_CHAR(PPRD.PPR_END_DATE, 'MM-DD-YY')
     , NULL --SADJ.SAD_SHIFT_CODE
     , SADJ.SAD_RATE_CODE
     , SADJ.SAD_COMP_CODE
     , SADJ.SAD_JOB
     , SADJ.SAD_PHASE
     , SADJ.SAD_CATEGORY
     , SADJ.SAD_WRL_CODE
     , SADJ.SAD_TRADE_CODE
     , NULL --SADJ.SAD_OTHER_HOURS
     , NULL --SADJ.SAD_OH_PAY_RATE
     , SADJ.SAD_AMOUNT
     , SADJ.SAD_WCB_CODE
FROM DA.PYEMPSALADJ SADJ 
   , DA.PYCOMPAYPRD PPRD 
--   , DA.PYEMPLOYEE_TABLE EMP
WHERE SADJ.SAD_COMP_CODE NOT IN ('ZZ')
AND NVL(SADJ.SAD_AMOUNT, 0) <> 0
--AND SADJ.SAD_EMP_NO       = '12049'
AND PPRD.PPR_COMP_CODE       = SADJ.SAD_COMP_CODE 
AND PPRD.PPR_PRN_CODE        = SADJ.SAD_PRN_CODE 
AND PPRD.PPR_YEAR            = SADJ.SAD_PPR_YEAR 
AND PPRD.PPR_PERIOD          = SADJ.SAD_PPR_PERIOD
AND SADJ.SAD_JOB            >= '90002'
--AND EMP.EMP_NO            = SADJ.SAD_EMP_NO
)
ORDER BY TSH_EMP_NO1, ROW_ORDER;
 