alter session set current_schema=sysadm

select  A.EMPLID, A.ACTION, A.ACTION_DT, A.ACTION_REASON, A.JOB_ENTRY_DT
,A.EMPL_STATUS, A.STEP, A.HOURLY_RT, A.COMP_FREQUENCY, A.COMPRATE, A.ANNL_BENEF_BASE_RT, A.POSITION_NBR, A.EFFSEQ
,A.GL_PAY_TYPE, a.NAME_PSFORMAT, a.SEX, a.BIRTHDATE, a.ADDRESS1, a.CITY, a.STATE, a.POSTAL
,a.ADDRESS2, a.HIRE_DT, a.ETHNIC_GRP_CD,
--
a.effdt, a.empl_rcd, a.grade, a.sal_admin_plan, 
--
B.BUSINESS_UNIT, B.DEPTID, B.EFF_STATUS, B.DESCR, B.JOBCODE, E.DESCR, B.POSN_STATUS, B.BUDGETED_POSN
, B.MAX_HEAD_COUNT, B.REPORTS_TO, B.STD_HOURS, B.UNION_CD, B.REG_TEMP, B.FULL_PART_TIME, B.FTE, B.BENEFIT_PROGRAM
, B.REPORT_DOTTED_LINE, B.PHONE, B.MB_SAFETY_SENSITIV,G.DESCRSHORT, E.EFF_STATUS, E.SAL_ADMIN_PLAN, E.GRADE
, E.MANAGER_LEVEL, E.JOB_FAMILY, E.MED_CHKUP_REQ, E.FLSA_STATUS, E.EEO4CODE,E.JOB_FUNCTION, F.MIN_RT_ANNUAL
, F.MAX_RT_ANNUAL, H.BENEFIT_PROGRAM, E.EEO_JOB_GROUP, B.LOCATION, TO_CHAR(A.EFFDT,'YYYY-MM-DD')
, TO_CHAR(SYSDATE,'YYYY-MM-DD'),B.POSITION_NBR, TO_CHAR(B.EFFDT,'YYYY-MM-DD'),E.SETID,E.JOBCODE
, TO_CHAR(E.EFFDT,'YYYY-MM-DD'),G.UNION_CD,TO_CHAR(G.EFFDT,'YYYY-MM-DD') 
from
(
select A.EMPLID, A.ACTION,TO_CHAR(A.ACTION_DT,'YYYY-MM-DD') ACTION_DT, A.ACTION_REASON
, TO_CHAR(A.JOB_ENTRY_DT,'YYYY-MM-DD') JOB_ENTRY_DT
,A.EMPL_STATUS, A.STEP, A.HOURLY_RT, A.COMP_FREQUENCY, A.COMPRATE, A.ANNL_BENEF_BASE_RT, A.POSITION_NBR, A.EFFSEQ
,A.GL_PAY_TYPE, D.NAME_PSFORMAT, D.SEX, TO_CHAR(D.BIRTHDATE,'YYYY-MM-DD') BIRTHDATE, D.ADDRESS1, D.CITY, D.STATE, D.POSTAL
,D.ADDRESS2, TO_CHAR(I.HIRE_DT,'YYYY-MM-DD') HIRE_DT, J.ETHNIC_GRP_CD
--
, a.effdt, a.empl_rcd, a.grade, a.sal_admin_plan, a.jobcode 
--
FROM PS_MB_JOB_VW A
  , PS_MB_PERSONAL_VW D
  , PS_EMPLOYMENT I
  , PS_DIVERS_ETHNIC J
where A.JOBCODE <> '200300'
AND A.EMPL_STATUS IN ('A','L','P')    
AND A.EMPLID = D.EMPLID           
AND D.EMPLID = I.EMPLID 
AND D.EMPLID = J.EMPLID
) a
, PS_POSITION_DATA B
--, PS_MB_PERSONAL_VW D
, PS_JOBCODE_TBL E
, PS_SAL_GRADE_TBL F
, PS_UNION_TBL G
, PS_BEN_PROG_PARTIC H
--, PS_EMPLOYMENT I
--, PS_DIVERS_ETHNIC J 
WHERE G.UNION_CD = B.UNION_CD 
    AND A.EMPL_STATUS IN ('A','L','P') 
    AND A.EFFDT = 
        (SELECT MAX(A_ED.EFFDT) FROM PS_MB_JOB_VW A_ED 
        WHERE A.EMPLID = A_ED.EMPLID 
          AND A.EMPL_RCD = A_ED.EMPL_RCD 
          AND A_ED.EFFDT <= TO_DATE('2012-07-01','YYYY-MM-DD')) 
    AND A.EFFSEQ = 
        (SELECT MAX(A_ES.EFFSEQ) FROM PS_MB_JOB_VW A_ES 
        WHERE A.EMPLID = A_ES.EMPLID 
          AND A.EMPL_RCD = A_ES.EMPL_RCD 
          AND A.EFFDT = A_ES.EFFDT)           
     AND A.POSITION_NBR = B.POSITION_NBR 
     AND B.EFFDT =     
        (SELECT MAX(B_ED.EFFDT) FROM PS_POSITION_DATA B_ED 
        WHERE B.POSITION_NBR = B_ED.POSITION_NBR 
          AND B_ED.EFFDT <= TO_DATE('2012-07-01','YYYY-MM-DD')) 
     --AND A.EMPLID = D.EMPLID 
     AND A.JOBCODE = E.JOBCODE 
     AND E.EFFDT =      
        (SELECT MAX(E_ED.EFFDT) FROM PS_JOBCODE_TBL E_ED 
        WHERE E.SETID = E_ED.SETID 
          AND E.JOBCODE = E_ED.JOBCODE 
          AND E_ED.EFFDT <= A.EFFDT) 
     AND F.EFFDT =      
        (SELECT MAX(F_ED.EFFDT) FROM PS_SAL_GRADE_TBL F_ED 
        WHERE F.SETID = F_ED.SETID 
          AND F.SAL_ADMIN_PLAN = F_ED.SAL_ADMIN_PLAN 
          AND F.GRADE = F_ED.GRADE 
          AND F_ED.EFFDT <= A.EFFDT) 
     AND F.GRADE = A.GRADE 
     AND F.SAL_ADMIN_PLAN = A.SAL_ADMIN_PLAN 
     AND G.EFFDT =      
        (SELECT MAX(G_ED.EFFDT) FROM PS_UNION_TBL G_ED 
        WHERE G.UNION_CD = G_ED.UNION_CD 
          AND G_ED.EFFDT <= B.EFFDT) 
     AND A.EMPLID = H.EMPLID 
     AND H.EFFDT =      
        (SELECT MAX(H_ED.EFFDT) FROM PS_BEN_PROG_PARTIC H_ED 
        WHERE H.EMPLID = H_ED.EMPLID 
          AND H.EMPL_RCD = H_ED.EMPL_RCD 
          AND H.COBRA_EVENT_ID = H_ED.COBRA_EVENT_ID 
          AND H_ED.EFFDT <= TO_DATE('2012-07-01','YYYY-MM-DD')) 
     --AND A.EMPLID = D.EMPLID           
     --AND D.EMPLID = I.EMPLID 
     --AND D.EMPLID = J.EMPLID  
group by A.EMPLID, A.ACTION, A.ACTION_DT, A.ACTION_REASON, A.JOB_ENTRY_DT
,A.EMPL_STATUS, A.STEP, A.HOURLY_RT, A.COMP_FREQUENCY, A.COMPRATE, A.ANNL_BENEF_BASE_RT, A.POSITION_NBR, A.EFFSEQ
,A.GL_PAY_TYPE, a.NAME_PSFORMAT, a.SEX, a.BIRTHDATE, a.ADDRESS1, a.CITY, a.STATE, a.POSTAL
,a.ADDRESS2, a.HIRE_DT, a.ETHNIC_GRP_CD,
--
a.effdt, a.empl_rcd, a.grade, a.sal_admin_plan, 
--
B.BUSINESS_UNIT, B.DEPTID, B.EFF_STATUS, B.DESCR, B.JOBCODE, E.DESCR, B.POSN_STATUS, B.BUDGETED_POSN
, B.MAX_HEAD_COUNT, B.REPORTS_TO, B.STD_HOURS, B.UNION_CD, B.REG_TEMP, B.FULL_PART_TIME, B.FTE, B.BENEFIT_PROGRAM
, B.REPORT_DOTTED_LINE, B.PHONE, B.MB_SAFETY_SENSITIV,G.DESCRSHORT, E.EFF_STATUS, E.SAL_ADMIN_PLAN, E.GRADE
, E.MANAGER_LEVEL, E.JOB_FAMILY, E.MED_CHKUP_REQ, E.FLSA_STATUS, E.EEO4CODE,E.JOB_FUNCTION, F.MIN_RT_ANNUAL
, F.MAX_RT_ANNUAL, H.BENEFIT_PROGRAM, E.EEO_JOB_GROUP, B.LOCATION, TO_CHAR(A.EFFDT,'YYYY-MM-DD')
, TO_CHAR(SYSDATE,'YYYY-MM-DD'),B.POSITION_NBR, TO_CHAR(B.EFFDT,'YYYY-MM-DD'),E.SETID,E.JOBCODE
, TO_CHAR(E.EFFDT,'YYYY-MM-DD'),G.UNION_CD,TO_CHAR(G.EFFDT,'YYYY-MM-DD') 