-- ****************************************************************** 
-- ORACLE CONFIDENTIAL.  For authorized use only.  Except for as      
-- expressly authorized by Oracle, do not disclose, copy, reproduce,  
-- distribute, or modify.                                             
-- ****************************************************************** 
--                                                                    
--  PEOPLESOFT 8 DATABASE UPGRADE DDL TO CREATE TABLESPACES - PT
-- ******************************************************************
-- ******************************************************************
--
--                          
--
--   $Header:
--
-- ******************************************************************
--
--  THIS SCRIPT BUILDS NEWTABLESPACES AS PART OF THE
--  UPGRADE TO PEOPLESOFT 8. PEOPLETOOLS DELIVERS NEW TABLESPACES IN
--  PEOPLESOFT 8 TO ACCOMODATE TREES, APPLICATION ENGINE, TEMP TABLES
--  AND TABLES THAT REQUIRE ROW LEVEL LOCKING. THE REL800.SQL SCRIPT
--  CREATES TABLES IN THESE NEW TABLESPACES AND IT IS NECESSARY TO RUN
--  THIS SCRIPT PRIOR TO RUNNING REL800.SQL. OTHERWISE YOU WILL RECEIVE
--  TABLESPACE NOT FOUND ERROR MESSAGES. RUN THIS SCRIPT ON ORACLE
--  USING SQLPLUS.
--
--  REQUIREMENTS
--        RUN THIS SCRIPT BEFORE RUNNING REL800.SQL
--
--  FOR YOUR INFORMATION
--        1) CREATE ALL TABLESPACES BELOW. IF PTTBL, PTPRC, PTAPP, AND PSIMAGE
--           ALREADY EXIST THEN YOU CAN REMOVE THESE TABLESPACES FROM THE SCRIPT
--        2) PEOPLESOFT RECOMMENDS USING STANDARD TABLESPACE NAMES
--           AS SPECIFIED BELOW
--        3) GLOBALLY MAKE THE FOLLOWING EDITS:
--
--           CHANGE <u01> AND <SID> TO THE APPROPRIATE VALUES FOR YOUR SYSTEM

set echo on
spool ptddlupg.log

--
-- CREATE PEOPLETOOLS TABLESPACES (THESE TABLESPACES MAY ALREADY
-- EXIST IN TARGET DATABASE BECAUSE THESE ARE NOT NEW NAMES) IF
-- TABLESPACES ALREADY EXIST THEN PLEASE LEAVE THEM COMMENTED OUT

--CREATE TABLESPACE PTTBL DATAFILE '/u01/oradata/<SID>/pttbl.dbf' SIZE 60M
--EXTENT MANAGEMENT LOCAL AUTOALLOCATE
--SEGMENT SPACE MANAGEMENT AUTO
--;
--CREATE TABLESPACE PTPRC DATAFILE '/u01/oradata/<SID>/ptprc.dbf' SIZE 1M
--EXTENT MANAGEMENT LOCAL AUTOALLOCATE
--SEGMENT SPACE MANAGEMENT AUTO
--;
--CREATE TABLESPACE PTAPP DATAFILE '/u01/oradata/<SID>/ptapp.dbf' SIZE 4M
--EXTENT MANAGEMENT LOCAL AUTOALLOCATE
--SEGMENT SPACE MANAGEMENT AUTO
--;
--CREATE TABLESPACE PSIMAGE DATAFILE '/u01/oradata/<SID>/psimage.dbf' SIZE 320M
--EXTENT MANAGEMENT LOCAL AUTOALLOCATE
--SEGMENT SPACE MANAGEMENT AUTO
--;

-- CREATE PEOPLETOOLS TABLESPACES (THESE ARE NEW TABLESPACE NAMES
-- INTRODUCED IN PEOPLETOOLS 8)

CREATE TABLESPACE PTAPPE DATAFILE '/u01/oradata/<SID>/ptappe.dbf' SIZE 35M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
;
CREATE TABLESPACE PTTREE DATAFILE '/u01/oradata/<SID>/pttree.dbf' SIZE 5M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
;
CREATE TABLESPACE PSWORK DATAFILE '/u01/oradata/<SID>/pswork.dbf' SIZE 6M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
;
CREATE TABLESPACE PTTLRG DATAFILE '/u01/oradata/<SID>/pttlrg.dbf' SIZE 215M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
;
CREATE TABLESPACE PTAMSG DATAFILE '/u01/oradata/<SID>/ptamsg.dbf' SIZE 6M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
;
CREATE TABLESPACE PTWORK DATAFILE '/u01/oradata/<SID>/ptwork.dbf' SIZE 6M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
;
CREATE TABLESPACE PTLOCK DATAFILE '/u01/oradata/<SID>/ptlock.dbf' SIZE 6M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
;

-- CREATE PEOPLETOOLS TABLESPACES (THESE ARE NEW TABLESPACE NAMES
-- INTRODUCED IN PEOPLETOOLS 8.1)

CREATE TABLESPACE PTRPTS DATAFILE '/u01/oradata/<SID>/ptrpts.dbf' SIZE 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
;
CREATE TABLESPACE PTCMSTAR DATAFILE '/u01/oradata/<SID>/ptcmstar.dbf' SIZE 50M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
;

-- CREATE PEOPLETOOLS TABLESPACES (THESE ARE NEW TABLESPACE NAMES
-- INTRODUCED IN PEOPLETOOLS 8.12)

CREATE TABLESPACE PTPRJWK DATAFILE '/u01/oradata/<SID>/ptprjwk.dbf' SIZE 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
;

-- CREATE PEOPLETOOLS TABLESPACES (THESE ARE NEW TABLESPACE NAMES
-- INTRODUCED IN PEOPLETOOLS 8.14)

CREATE TABLESPACE PTAUDIT DATAFILE '/u01/oradata/<SID>/ptaudit.dbf' SIZE 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
;

-- CREATE PEOPLETOOLS TABLESPACES (THESE ARE NEW TABLESPACE NAMES
-- INTRODUCED IN PEOPLETOOLS 8.16)

CREATE TABLESPACE PSIMGR DATAFILE '/u01/oradata/<SID>/psimgr.dbf' SIZE 8M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO
;

spool off

