
declare

v_cnt      NUMBER;
v_cnt_conv NUMBER;
v_cnt_prod NUMBER;
record_count_mismatch exception;

begin
for i in
(
SELECT 
  BAB_COMP_CODE,
  BAB_DEPT_CODE,
  BAB_ACC_CODE,
  BAB_BANK_CODE,
  BAB_ACC_PREFIX,
  BAB_ACC_NUMBER,
  BAB_CURR_CODE,
  BAB_FXGAIN_DEPT_CODE,
  BAB_FXGAIN_ACC_CODE,
  BAB_FXLOSS_DEPT_CODE,
  BAB_FXLOSS_ACC_CODE,
  BAB_SUSP_REC_DEPT_CODE,
  BAB_SUSP_REC_ACC_CODE,
  BAB_SUSP_PAY_DEPT_CODE,
  BAB_SUSP_PAY_ACC_CODE,
  BAB_LAST_CHQ_NUM,
  BAB_ACC_TITLE,
  BAB_ACC_TYPE,
  BAB_EFT_DESC,
  BAB_EFT_FORMAT,
  BAB_FC_BAL_AMT,
  BAB_CREATE_USER,
  BAB_CREATE_DATE,
  BAB_LAST_UPD_USER,
  BAB_LAST_UPD_DATE,
  BAB_BRANCH_CODE,
  BAB_MICR_CODE,
  BAB_SIGN_FILE1,
  BAB_SIGN_FILE2,
  BAB_COMP_LOGO_FILE,
  BAB_AMT_FOR_TWO_SIGN,
  BAB_AMT_FOR_MAN_SIGN,
  BAB_PRINT_COMP_ADDR,
  BAB_COMP_ADDR_CODE,
  BAB_PRINT_BANK_ADDR,
  BAB_PRINT_CHECK_FRAME,
  BAB_ROUTING_CODE_A,
  BAB_ROUTING_CODE_B,
  BAB_PRINT_ROUTING,
  BAB_PRINT_MICR,
  BAB_EFT_FILE_FORMAT,
  BAB_EFT_FILE_CODE,
  BAB_CDA_ACC_NUMBER,
  BAB_CSR_ACC_NUMBER,
  BAB_BANK_CUSTOMER_ID,
  BAB_LAST_EFT_NUM,
  BAB_FILE_NUMBER,
  BAB_PAY_THROUGH,
  BAB_CURR_DESIGN,
  BAB_CHEQUE_DATE_FORMAT--,
  --BAB__IU__CREATE_DATE,
  --BAB__IU__CREATE_USER,
  --BAB__IU__UPDATE_DATE,
  --BAB__IU__UPDATE_USER
FROM DA.BABANKACCT@CONV 
WHERE BAB_COMP_CODE NOT IN ('ZZ')
) loop
INSERT INTO DA.BABANKACCT
(  
  BAB_COMP_CODE,
  BAB_DEPT_CODE,
  BAB_ACC_CODE,
  BAB_BANK_CODE,
  BAB_ACC_PREFIX,
  BAB_ACC_NUMBER,
  BAB_CURR_CODE,
  BAB_FXGAIN_DEPT_CODE,
  BAB_FXGAIN_ACC_CODE,
  BAB_FXLOSS_DEPT_CODE,
  BAB_FXLOSS_ACC_CODE,
  BAB_SUSP_REC_DEPT_CODE,
  BAB_SUSP_REC_ACC_CODE,
  BAB_SUSP_PAY_DEPT_CODE,
  BAB_SUSP_PAY_ACC_CODE,
  BAB_LAST_CHQ_NUM,
  BAB_ACC_TITLE,
  BAB_ACC_TYPE,
  BAB_EFT_DESC,
  BAB_EFT_FORMAT,
  BAB_FC_BAL_AMT,
  BAB_CREATE_USER,
  BAB_CREATE_DATE,
  BAB_LAST_UPD_USER,
  BAB_LAST_UPD_DATE,
  BAB_BRANCH_CODE,
  BAB_MICR_CODE,
  BAB_SIGN_FILE1,
  BAB_SIGN_FILE2,
  BAB_COMP_LOGO_FILE,
  BAB_AMT_FOR_TWO_SIGN,
  BAB_AMT_FOR_MAN_SIGN,
  BAB_PRINT_COMP_ADDR,
  BAB_COMP_ADDR_CODE,
  BAB_PRINT_BANK_ADDR,
  BAB_PRINT_CHECK_FRAME,
  BAB_ROUTING_CODE_A,
  BAB_ROUTING_CODE_B,
  BAB_PRINT_ROUTING,
  BAB_PRINT_MICR,
  BAB_EFT_FILE_FORMAT,
  BAB_EFT_FILE_CODE,
  BAB_CDA_ACC_NUMBER,
  BAB_CSR_ACC_NUMBER,
  BAB_BANK_CUSTOMER_ID,
  BAB_LAST_EFT_NUM,
  BAB_FILE_NUMBER,
  BAB_PAY_THROUGH,
  BAB_CURR_DESIGN,
  BAB_CHEQUE_DATE_FORMAT--,
  --BAB__IU__CREATE_DATE,
  --BAB__IU__CREATE_USER,
  --BAB__IU__UPDATE_DATE,
  --BAB__IU__UPDATE_USER
)
values
(
i.  BAB_COMP_CODE,
i.  BAB_DEPT_CODE,
i.  BAB_ACC_CODE,
i.  BAB_BANK_CODE,
i.  BAB_ACC_PREFIX,
i.  BAB_ACC_NUMBER,
i.  BAB_CURR_CODE,
i.  BAB_FXGAIN_DEPT_CODE,
i.  BAB_FXGAIN_ACC_CODE,
i.  BAB_FXLOSS_DEPT_CODE,
i.  BAB_FXLOSS_ACC_CODE,
i.  BAB_SUSP_REC_DEPT_CODE,
i.  BAB_SUSP_REC_ACC_CODE,
i.  BAB_SUSP_PAY_DEPT_CODE,
i.  BAB_SUSP_PAY_ACC_CODE,
i.  BAB_LAST_CHQ_NUM,
i.  BAB_ACC_TITLE,
i.  BAB_ACC_TYPE,
i.  BAB_EFT_DESC,
i.  BAB_EFT_FORMAT,
i.  BAB_FC_BAL_AMT,
i.  BAB_CREATE_USER,
i.  BAB_CREATE_DATE,
i.  BAB_LAST_UPD_USER,
i.  BAB_LAST_UPD_DATE,
i.  BAB_BRANCH_CODE,
i.  BAB_MICR_CODE,
i.  BAB_SIGN_FILE1,
i.  BAB_SIGN_FILE2,
i.  BAB_COMP_LOGO_FILE,
i.  BAB_AMT_FOR_TWO_SIGN,
i.  BAB_AMT_FOR_MAN_SIGN,
i.  BAB_PRINT_COMP_ADDR,
i.  BAB_COMP_ADDR_CODE,
i.  BAB_PRINT_BANK_ADDR,
i.  BAB_PRINT_CHECK_FRAME,
i.  BAB_ROUTING_CODE_A,
i.  BAB_ROUTING_CODE_B,
i.  BAB_PRINT_ROUTING,
i.  BAB_PRINT_MICR,
i.  BAB_EFT_FILE_FORMAT,
i.  BAB_EFT_FILE_CODE,
i.  BAB_CDA_ACC_NUMBER,
i.  BAB_CSR_ACC_NUMBER,
i.  BAB_BANK_CUSTOMER_ID,
i.  BAB_LAST_EFT_NUM,
i.  BAB_FILE_NUMBER,
i.  BAB_PAY_THROUGH,
i.  BAB_CURR_DESIGN,
i.  BAB_CHEQUE_DATE_FORMAT--,
--i.  --BAB__IU__CREATE_DATE,
--i.  --BAB__IU__CREATE_USER,
--i.  --BAB__IU__UPDATE_DATE,
--i.  --BAB__IU__UPDATE_USER
);
end loop;
--commit;
select count(1) into v_cnt_conv from BABANKACCT@conv;
select count(1) into v_cnt_prod from BABANKACCT@prod;
if v_cnt_conv - v_cnt_prod = 0
then
dbms_output.put_line ('Number of records in PROD match with CONV for BABANKACCT table.');
else
dbms_output.put_line ('Number of records in PROD does not match with CONV for BABANKACCT table.');
Raise record_count_mismatch;
end if;
Select count(1) into v_cnt from DA.BABANKACCT@PROD where BAB_COMP_CODE NOT IN ('ZZ');
dbms_output.put_line ('Inserted '||v_cnt||' records into BABANKACCT table, check and commit.');
EXCEPTION
WHEN record_count_mismatch
THEN
DBMS_OUTPUT.PUT_LINE ('There is a mismatch in PROD and CONV for this table.');
WHEN OTHERS 
THEN
DBMS_OUTPUT.PUT_LINE ('ERROR WHILE INSERTING INTO DA.BABANKACCT.');
DBMS_OUTPUT.PUT_LINE (SQLERRM);

end;
/ 