--set rowcount 100

SELECT  "select mbta_email_seq.nextval,'" + RTRIM(EMP.EMPLID) + "','" + RTRIM(EMP.FIRST_NAME) + "','" + RTRIM(EMP.MIDDLE_NAME) + "','" + RTRIM(EMP.LAST_NAME) + "','" + RTRIM(JCV.HR_STATUS) + "','" + RTRIM(JCV.DEPTID) + "','" + RTRIM(OPDT.DESCR) + "','" + RTRIM(OPJT.JOBCODE) + "','" + RTRIM(OPJT.DESCR) + "','" + RTRIM(PEA.EMAIL_ADDR) + "' from dual" 
FROM 
(
select EMPLID, upper(FIRST_NAME) FIRST_NAME, upper(MIDDLE_NAME) MIDDLE_NAME, upper(LAST_NAME) LAST_NAME
from PS_NAMES OPN
where upper(LAST_NAME) LIKE ('RAYMOND') 
--AND UPPER(FIRST_NAME) LIKE ('CREEDON')
--EMPLID = '17454'
and EFFDT = (select max(EFFDT) from PS_NAMES IPN where IPN.EMPLID = OPN.EMPLID)
) EMP,
PS_MB_JOB_CURR_VW JCV,
PS_EMAIL_ADDRESSES PEA,
PS_DEPT_TBL OPDT,
PS_JOBCODE_TBL OPJT
where JCV.EMPLID = EMP.EMPLID
AND PEA.EMPLID =* JCV.EMPLID
AND OPDT.DEPTID =* JCV.DEPTID  
AND OPDT.SETID =  'MBTA1'
AND OPDT.EFFDT = (SELECT max(EFFDT) FROM PS_DEPT_TBL IPDT WHERE IPDT.DEPTID = OPDT.DEPTID)
AND OPJT.JOBCODE =* JCV.JOBCODE
AND OPJT.SETID = 'MBTA1'
AND OPJT.EFFDT = (SELECT max(EFFDT) FROM PS_JOBCODE_TBL IPJT WHERE IPJT.JOBCODE = OPJT.JOBCODE)
