SELECT /*+ ORDERED */
    ARD_CPARTKEY,
    ARD_CUST_IDN,
    ARD_ACCT_SEQ,
       ARD_CUST_IDN||LPAD(ARD_ACCT_SEQ,4,0)||MAX(ACCT_CHECK_DIGIT) ACCOUNT_NUMBER,
       CUST_NAME,
       MAX(ADD_STREET_NUM)         ADD_STREET_NUM            ,
       MAX(ADD_STREET_NAME)        ADD_STREET_NAME           ,
       MAX(ADD_STREET_SUFX)        ADD_STREET_SUFX           ,
       MAX(ADD_POSTAL_CITY)        ADD_POSTAL_CITY           ,
       MAX(ADD_DS_STATE_NAME)      ADD_DS_STATE_NAME         ,
       MAX(ADD_ZIP_CODE)           ADD_ZIP_CODE              ,
       MAX(ADD_POSTAL_CITY)        CITY           ,
       DECODE(SITED.SER_MTR_LOCATION_CODE,5, 'INSIDE',9, 'INSIDE',22, 'INSIDE',18, 'INSIDE',19, 'INSIDE',20, 'INSIDE',21, 

'INSIDE','OUTSIDE') METER_LOCATION,
       SUM(ARD_CURRENT_AMT) CURRENT_AMT,
       SUM(ARD_ABAL_30_AMT) AMT_30,
       SUM(ARD_ABAL_60_AMT) AMT_60,
       SUM(ARD_ABAL_90_AMT) AMT_90,
       SUM(ARD_ABAL_OVER_90_AMT) AMT_OVER_90,
       SUM(ARD_ABAL_30_AMT) + SUM(ARD_ABAL_60_AMT) + SUM(ARD_ABAL_90_AMT) +    SUM(ARD_ABAL_OVER_90_AMT) TOTAL_ARREARS,
       to_Date('11/18/2007','mm/dd/yyyy') load_date
FROM ARREARS_DETAIL_TRANS ARDD,
     (SELECT /*+ ORDERED */
       DISTINCT
       ARD.ARD_CPARTKEY ACCT_CPARTKEY, 
       ARD.ARD_CUST_IDN ACCT_CUST_IDN, 
       ARD.ARD_ACCT_SEQ ACCT_SEQ,
       ARD.ARD_AGR_SEQ  ACCT_AGR_SEQ,
       ACCT.ACCT_CHECK_DIGIT,
       CUST_NAME,
       MAX(ADD_STREET_NUM)         ADD_STREET_NUM            ,
       MAX(ADD_STREET_NAME)        ADD_STREET_NAME           ,
       MAX(ADD_STREET_SUFX)        ADD_STREET_SUFX           ,
       MAX(ADD_POSTAL_CITY)        ADD_POSTAL_CITY           ,
       MAX(ADD_DS_STATE_NAME)      ADD_DS_STATE_NAME         ,
       MAX(ADD_ZIP_CODE)           ADD_ZIP_CODE              ,
       MAX(AGR.AGR_SPARTKEY)       AGR_SPARTKEY              ,
       MAX(AGR.AGR_SER_SEQ)        AGR_SER_SEQ               , 
       MAX(SER_MTR_LOCATION_CODE)  SER_MTR_LOCATION_CODE
      FROM ARREARS_DETAIL_TRANS ARD, 
           AGREEMENTS AGR, 
           ADDRESS_USAGES ADDU, 
           ADDRESSES ADDR,
           SERVICES SER,
           CUSTOMER_ACCOUNTS ACCT,
           CUSTOMERS CUST
     WHERE ARD.ARD_ARREAR_TYPE   = 4
     AND   ARD_ENTERPRISE_CODE IN (2,3,7)
     AND   ARD_ACCT_TYPE='NON'
     AND   ARD.ARD_CPARTKEY      = AGR.AGR_CPARTKEY (+)
     AND   ARD.ARD_CUST_IDN      = AGR.AGR_CUST_IDN (+)
     AND   ARD.ARD_ACCT_SEQ      = AGR.AGR_ACCT_SEQ (+)
     AND   AGR_SIT_IDN           = ADDU.ADDU_SIT_IDN 
     AND   ADDU.ADDU_TYPE        = 'SIT'
     AND   ADDU.ADDU_ADD_IDN     = ADDR.ADD_IDN
     AND   AGR.AGR_SIT_IDN       = SER.SER_SIT_IDN  (+)
     AND   AGR.AGR_SER_SEQ       = SER.SER_SEQ      (+)
     AND   AGR.AGR_SPARTKEY      = SER.SER_SPARTKEY (+)
     AND   ARD.ARD_CPARTKEY      = ACCT.ACCT_CPARTKEY
     AND   ARD.ARD_CUST_IDN      = ACCT.ACCT_CUST_IDN
     AND   ARD.ARD_ACCT_SEQ      = ACCT.ACCT_SEQ
     AND   ACCT_CPARTKEY         = CUST_CPARTKEY
     AND   ACCT_CUST_IDN         = CUST_IDN
GROUP BY     ARD_CPARTKEY, ARD_CUST_IDN, ARD_ACCT_SEQ,
ARD.ARD_CPARTKEY, ARD.ARD_CUST_IDN, ARD.ARD_ACCT_SEQ, ARD.ARD_AGR_SEQ, ARD.ARD_PRODUCT_TYPE,ACCT.ACCT_CHECK_DIGIT, CUST_NAME) 

SITED
WHERE  ARDD.ARD_ARREAR_TYPE   = 4
AND    ARDD.ARD_ENTERPRISE_CODE IN (2,3,7)
AND    ARDD.ARD_ACCT_TYPE     = 'NON'
AND    ARDD.ARD_CPARTKEY      = SITED.ACCT_CPARTKEY
AND    ARDD.ARD_CUST_IDN      = SITED.ACCT_CUST_IDN
AND    ARDD.ARD_ACCT_SEQ      = SITED.ACCT_SEQ
AND    ARDD.ARD_AGR_SEQ       = SITED.ACCT_AGR_SEQ
GROUP BY 

ARD_CPARTKEY,ARD_CUST_IDN,ARD_ACCT_SEQ,CUST_NAME,DECODE(SITED.SER_MTR_LOCATION_CODE,5,'INSIDE',9,'INSIDE',22,'INSIDE',18,'INSIDE',19,'INSIDE',20,'INSIDE',21, 'INSIDE','OUTSIDE')