SELECT DISTINCT a.ACCOUNT_NUMBER Account_Number,
       a.CUST_NAME Customer_Name,
             a.ADD_STREET_NUM || ' ' || a.ADD_STREET_NAME || ' ' ||  a.ADD_STREET_SUFX Address, 
         a.ADD_POSTAL_CITY City, 
               a.ADD_DS_STATE_NAME State, 
            a.ADD_ZIP_CODE ZIP,
       a.METER_LOCATION Meter_Location ,
         SUM(a.AMT_30) a30_Day , 
       SUM(a.AMT_60) a60_Day, 
       SUM(a.AMT_90) a90_Day, 
     SUM(a.AMT_OVER_90) Over_90_Day,
       SUM(a.TOTAL_ARREARS) Total_Energy_Arrears,
       b.gas_or_both Account_Designation,
       b.acct_type Commercial_Residential,
       DECODE(b.choice_nochoice, '2', 'Not Choice', NULL, b.choice_nochoice, 'Choice') Choice_NotChoice,
       b.COLL_CO_SCORE Collection_Chargeoff_Score,
       b.collection_status_cd Collection_Status_Code,
       b.collection_status_desc Collection_Status_Description,
       b.collector_id Collector_ID,
       b.date_last_pmt Last_Payment_Date,
       b.amt_last_pmt Last_Payment_Amount,
       b.coll_severity_code Severity_Code,
       b.current_age Current_Age,
       DECODE(a.active_gas_agr_flg,'Y','Active','N', 'Inactive', NULL) Active_or_Inactive
FROM COM_GAS_ACCOUNT_DETAILS A, 
com_gas_acct_details_from_ccs B
WHERE  a.account_number = b.account_no(+)
AND a.load_date = TO_DATE('11-18-2007','mm-dd-yyyy')
AND b.load_date(+) = TO_DATE('11-18-2007','mm-dd-yyyy')
HAVING SUM(a.AMT_30+ a.AMT_60 + a.AMT_90 + a.AMT_OVER_90) <> 0
GROUP BY a.ACCOUNT_NUMBER,
       a.CUST_NAME, 
       a.METER_LOCATION, 
        a.ADD_DS_STATE_NAME, 
       a.ADD_POSTAL_CITY, 
       a.ADD_STREET_NAME, 
       a.ADD_STREET_NUM, 
       a.ADD_STREET_SUFX, 
       a.ADD_ZIP_CODE,
       a.product_type,
       b.mtr_loc, 
       b.gas_or_both,
       b.acct_type,
       b.choice_nochoice,
       b.COLL_CO_SCORE,
       b.collection_status_cd,
       b.collection_status_desc,
       b.collector_id,
       b.date_last_pmt,
       b.amt_last_pmt,
       b.coll_severity_code,
       b.current_age,
       a.active_gas_agr_flg
