Set current schema = 'PSFNDV2' --DV2
Set current schema = 'PSFNTST'
Set current schema = 'PSFNDEV'

INSERT INTO PS_MB_POKK01_TMP02 
 SELECT 1--%Bind(MB_POKK01_1_AET.PROCESS_INSTANCE) 
 --, A.OPRID 
 --, A.RUN_CNTL_ID 
 --, A.REQUEST_ID 
 , A.TREE_NODE 
 , B.TREE_NODE 
 , B.PARENT_NODE_NUM 
 , B.TREE_NODE_NUM_END 
 , B.TREE_LEVEL_NUM 
 , B.PARENT_NODE_NAME 
 --, A.DESCR 
  FROM ( 
			 SELECT A.TREE_NODE_NUM 
			 , A.TREE_NODE_NUM_END 
			 , A.TREE_LEVEL_NUM 
			 , A.TREE_NODE 
			 , A.SETID 
			 , A.TREE_NAME 
			 , A.EFFDT 
			 --, B.RUN_CNTL_ID 
--			 , B.REQUEST_ID 
--			 , B.OPRID 
--			 , B.DESCR 
			  FROM PSTREENODE A 
			 -- , PS_MB_RUNCNTL_PO B 
			  , PS_DEPT_TBL C 
			 WHERE A.SETID = C.SETID 
			   AND C.EFFDT = ( 
								 SELECT MAX(C_ED.EFFDT) 
								  FROM PS_DEPT_TBL C_ED 
								 WHERE C.SETID = C_ED.SETID 
								   AND C.DEPTID = C_ED.DEPTID 
								   AND C_ED.EFFDT <= A.EFFDT
							) 
			   AND A.SETID = 'MBTA1'--B.SETID 
			   AND A.TREE_NAME = 'CC_DEPARTMENT'
			   AND A.EFFDT = '2010-07-01' 
			   AND A.TREE_LEVEL_NUM = 4 
			   AND A.TREE_NODE = '220000'--B.PARENT_NODE_NAME 
			   AND A.TREE_NODE = C.DEPTID
	    ) A
     , PSTREENODE B 
 WHERE B.TREE_NODE_NUM BETWEEN A.TREE_NODE_NUM AND A.TREE_NODE_NUM_END 
   AND A.SETID = B.SETID 
   AND A.TREE_NAME = B.TREE_NAME 
   AND A.EFFDT = B.EFFDT 
--   AND A.RUN_CNTL_ID = %Bind(MB_POKK01_1_AET.RUN_CNTL_ID) 
--   AND A.REQUEST_ID = %Bind(MB_POKK01_1_AET.REQUEST_ID) 
--   AND A.OPRID = %OperatorId


select * from PS_MB_RUNCTL_IN