/*
CREATE OR REPLACE FORCE VIEW DA1.COST_TO_COMPLETE_CADVW (CTC_COMP_CODE, CTC_JOB_CODE, CTC_PHS_CODE1
                                                 , CTC_PHS_CODE2, CTC_CAT_CODE, CTC_PHS_NAME, CTC_POST_DATE
                                                 , CTC_COMMITED_AMT, CTC_WM_CODE) 
AS
SELECT JCDT_COMP_CODE 
    , JCDT_JOB_CODE 
    , CASE 
      WHEN JCDT_PHS_CODE LIKE '%-%' 
      THEN SUBSTR(JCDT_PHS_CODE, 1, INSTR(JCDT_PHS_CODE,'-')-1)
      ELSE JCDT_PHS_CODE
      END CASE
    , CASE 
      WHEN JCDT_PHS_CODE LIKE '%-%' 
      THEN SUBSTR(JCDT_PHS_CODE, INSTR(JCDT_PHS_CODE,'-')+1, LENGTH(JCDT_PHS_CODE))
      ELSE
      NULL
      END CASE 
    , JCDT_CAT_CODE
    , JHP_NAME
    , TRUNC(JCDT_POST_DATE)
    , LTRIM(TO_CHAR(JCDT_AMT,'9999999990.00')) 
    , JCAT_WM_CODE
FROM DA.JCDETAIL DET,
     DA.JCJOBCAT CAT, 
     DA.JCJOBHPHS PHS
WHERE 1=1
--      JCDT_COMP_CODE = :P_COMPANY_CODE
AND CASE 
        WHEN JCDT_TYPE_CODE = 'O' 
--        AND TRUNC(JCDT_POST_DATE) <= TO_DATE (:P_POST_DATE,'MM-DD-YY')  
        THEN 'A'
        WHEN JCDT_TYPE_CODE = 'C' 
--        AND TRUNC(JCDT_POST_DATE) <= TO_DATE (:P_POST_DATE,'MM-DD-YY') 
        AND JCDT_SRC_COMM_CODE IS NULL 
        THEN 'B'
        END IN ('A','B')
AND DET.JCDT_JOB_CODE >= '90000'
AND DET.JCDT_COMP_CODE = PHS.JHP_COMP_CODE
AND DET.JCDT_JOB_CODE  = PHS.JHP_JOB_CODE
AND DET.JCDT_PHS_CODE  = PHS.JHP_CODE
AND CAT.JCAT_JOB_CODE  = DET.JCDT_JOB_CODE
AND CAT.JCAT_COMP_CODE = DET.JCDT_COMP_CODE
AND CAT.JCAT_PHS_CODE  = DET.JCDT_PHS_CODE
AND CAT.JCAT_CODE      = DET.JCDT_CAT_CODE

COMMENT ON VIEW DA1.COST_TO_COMPLETE_CADVW  IS 'COST TO COMPLETE REPORT';

--group by jcdt_comp_code 
  --  , jcdt_job_code 
    --, replace(jcdt_phs_code,'-',',') 
    --, '"'||jcdt_cat_code||'"' 
    --, '"'||jhp_name||'"' 
    --, '"'||to_char(to_date (:p_post_date,'mm-dd-yy'),'mm-dd-yyyy')||'"' 
    --, cat.jcat_wm_code
    --, '0.00'
    --, ''
*/ 

CREATE OR REPLACE FORCE VIEW DA1.COST_TO_COMPLETE_CADVW (CTC_COMP_CODE, CTC_JOB_CODE_NAME
                                                 , CTC_PHS_CODE1, CTC_PHS_CODE2, CTC_CAT_CODE
                                                 , CTC_PHS_NAME, CTC_POST_DATE, CTC_COMMITED_AMT
                                                 , CTC_WM_CODE, CTC_BUDG_AMT) 
AS
SELECT JCDT_COMP_CODE 
    , JCDT_JOB_CODE ||' - '|| JOB_NAME
    , CASE 
      WHEN JCDT_PHS_CODE LIKE '%-%' 
      THEN SUBSTR(JCDT_PHS_CODE, 1, INSTR(JCDT_PHS_CODE,'-')-1)
      ELSE JCDT_PHS_CODE
      END CASE
    , CASE 
      WHEN JCDT_PHS_CODE LIKE '%-%' 
      THEN SUBSTR(JCDT_PHS_CODE, INSTR(JCDT_PHS_CODE,'-')+1, LENGTH(JCDT_PHS_CODE))
      ELSE
      NULL
      END CASE 
    , JCDT_CAT_CODE
    , JHP_NAME
    , TRUNC(JCDT_POST_DATE)
    , nvl(JCDT_AMT,0)
    , JCAT_WM_CODE
    , nvl(JCAT_BUDG_AMT,0)
FROM DA.JCDETAIL DET,
     DA.JCJOBHPHS PHS,
     DA.JCJOBCAT CAT, 
     DA.JCJOB_TABLE JOB
WHERE 1=1
--      JCDT_COMP_CODE = :P_COMPANY_CODE
AND CASE 
      WHEN DET.JCDT_TYPE_CODE = 'O' 
--    AND TRUNC(JCDT_POST_DATE) <= TO_DATE (:P_POST_DATE,'MM-DD-YY')  
      THEN 'A'
      WHEN DET.JCDT_TYPE_CODE = 'C' 
--    AND TRUNC(JCDT_POST_DATE) <= TO_DATE (:P_POST_DATE,'MM-DD-YY') 
      AND DET.JCDT_SRC_COMM_CODE IS NULL 
      THEN 'B'
      END IN ('A','B')
AND DET.JCDT_JOB_CODE >= '90002'
AND DET.JCDT_COMP_CODE NOT IN ('ZZ')
AND DET.JCDT_COMP_CODE = PHS.JHP_COMP_CODE
AND DET.JCDT_JOB_CODE  = PHS.JHP_JOB_CODE
AND DET.JCDT_PHS_CODE  = PHS.JHP_CODE
AND DET.JCDT_JOB_CODE  = CAT.JCAT_JOB_CODE
AND DET.JCDT_COMP_CODE = CAT.JCAT_COMP_CODE
AND DET.JCDT_PHS_CODE  = CAT.JCAT_PHS_CODE
AND DET.JCDT_CAT_CODE  = CAT.JCAT_CODE
AND DET.JCDT_JOB_CODE  = JOB.JOB_CODE
AND DET.JCDT_COMP_CODE = JOB.JOB_COMP_CODE

select * from DA1.COST_TO_COMPLETE_CADVW

select * from DA.JCDETAIL DET