CREATE OR REPLACE VIEW DA1.TIME_SHEET_CADVW (TSC_JOB_CODE, TSC_START_DAT, TSC_END_DATE,
                                             TSC_PRN_CODE, TSC_COMP_CODE, TSC_SUM_NORMALHRS,
                                             TSC_WCB_CODE, TSC_DATA
                                            ) 
AS 

SELECT PHST.TSH_JOB_CODE -- 3 ASC
     , PPRD.PPR_START_DATE
     , PPRD.PPR_END_DATE
     , PHST.TSH_PRN_CODE
     , PHST.TSH_COMP_CODE
       
     , NVL(SUM(PHST.TSH_NORMAL_HOURS), 0) -- 1 DESC
     , PHST.TSH_WCB_CODE -- 2 ASC      
       
        , PHST.TSH_JOB_CODE
|| ',' || PHST.TSH_EMP_NO 
|| ',' || NVL(SUM(PHST.TSH_NORMAL_HOURS), 0)
|| ',' || NVL(SUM(PHST.TSH_OT_HOURS), 0)
|| ',' || NVL(SUM(PHST.TSH_DOT_HOURS), 0)
|| ',' || NVL(SUM(PHST.TSH_NH_PAY_AMT), 0)
|| ',' || NVL(SUM(PHST.TSH_OT_PAY_AMT), 0)
|| ',' || NVL(SUM(PHST.TSH_DOT_PAY_AMT), 0)
|| ',' || NVL(SUM(PHST.TSH_NH_PAY_RATE), 0)
|| ',' || PHST.TSH_TRADE_CODE
|| ',' || TO_CHAR(PHST.TSH_DATE, 'MM/DD/YYYY')
|| ',' || TO_CHAR(PPRD.PPR_END_DATE, 'MM/DD/YYYY')
|| ',' || EMP.EMP_SIN_NO
|| ',' || EMP.EMP_LAST_NAME
|| ',' || EMP.EMP_FIRST_NAME
|| ',' || EMP.EMP_MIDDLE_NAME
|| ',' || PHST.TSH_PHASE
|| ',' || PHST.TSH_WCB_CODE
|| ',' || PHST.TSH_SHIFT_CODE
FROM DA.PYEMPTIMSHT PHST 
   , DA.PYCOMPAYPRD PPRD 
   , DA.PYEMPLOYEE EMP
WHERE PHST.TSH_COMP_CODE NOT IN ('ZZ')
AND PPRD.PPR_COMP_CODE   = PHST.TSH_COMP_CODE 
AND PPRD.PPR_PRN_CODE    = PHST.TSH_PRN_CODE 
AND PPRD.PPR_YEAR        = PHST.TSH_PPR_YEAR 
AND PPRD.PPR_PERIOD      = PHST.TSH_PPR_PERIOD
AND PHST.TSH_JOB_CODE   >= '90002'
AND EMP.EMP_NO           = PHST.TSH_EMP_NO
GROUP BY PHST.TSH_TRADE_CODE, PHST.TSH_DATE, PHST.TSH_EMP_NO, PPRD.PPR_END_DATE
       , PHST.TSH_JOB_CODE, PHST.TSH_PHASE, PHST.TSH_WCB_CODE, EMP.EMP_FIRST_NAME
       , EMP.EMP_MIDDLE_NAME, EMP.EMP_LAST_NAME, EMP.EMP_SIN_NO, PHST.TSH_SHIFT_CODE
       , PPRD.PPR_START_DATE, PPRD.PPR_END_DATE, PHST.TSH_COMP_CODE, PHST.TSH_PRN_CODE  