-- ***************************************************************
--         Confidentiality Information:                           
--                                                                
--  This module contains confidential and proprietary information 
--  of PeopleSoft, Inc.; it is not to be copied, reproduced, or   
--  transmitted in any form, by any means, in whole or in part,   
--  nor is it to be used for any purpose other than that for      
--  which it is expressly provided under the applicable license   
--  agreement.                                                    
--                                                                
--  Copyright (C) 2005 PeopleSoft, Inc. All Rights Reserved.      
-- **************************************************************
Remark * Script: epddl.sql  Oracle on NT
Remark * Date last modified: 6/27/05

Remark * This script is used to create tablespaces for the PeopleSoft 8.9
Remark * Financials and Supply Chain Management Products.

Remark * NOTE: The sizing of the tablespaces here are only sample sizes that will
Remark *       hold the demo database tables.  This is not sized correctly for a
Remark *       production database.  
                                                                  
Remark * Users can choose to use the autoextending tablespace feature.
Remark * The syntax is at the end of this script.

Remark * Change the datafile name as appropriate for your site.

set echo on;
spool epddl.log;


CREATE TABLESPACE AMAPP DATAFILE '<drive>:\oradata\<SID>\amapp.dbf' SIZE 119M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE AMARCH DATAFILE '<drive>:\oradata\<SID>\amarch.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE AMLARGE DATAFILE '<drive>:\oradata\<SID>\amlarge.dbf' SIZE 72M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE AMWORK DATAFILE '<drive>:\oradata\<SID>\amwork.dbf' SIZE 63M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE APAPP DATAFILE '<drive>:\oradata\<SID>\apapp.dbf' SIZE 90M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE APARCH DATAFILE '<drive>:\oradata\<SID>\aparch.dbf' SIZE 5M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE APLARGE DATAFILE '<drive>:\oradata\<SID>\aplarge.dbf' SIZE 94M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE APWORK DATAFILE '<drive>:\oradata\<SID>\apwork.dbf' SIZE 193M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE ARAPP DATAFILE '<drive>:\oradata\<SID>\arapp.dbf' SIZE 42M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE ARARCH DATAFILE '<drive>:\oradata\<SID>\ararch.dbf' SIZE 3M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE ARLARGE DATAFILE '<drive>:\oradata\<SID>\arlarge.dbf' SIZE 46M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE ARWORK DATAFILE '<drive>:\oradata\<SID>\arwork.dbf' SIZE 159M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE AUCAPP DATAFILE '<drive>:\oradata\<SID>\aucapp.dbf' SIZE 20M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE AUCLRGE DATAFILE '<drive>:\oradata\<SID>\auclrge.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE BCAPP DATAFILE '<drive>:\oradata\<SID>\bcapp.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE BDAPP DATAFILE '<drive>:\oradata\<SID>\bdapp.dbf' SIZE 19M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE BDLARGE DATAFILE '<drive>:\oradata\<SID>\bdlarge.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/                                                                                      

CREATE TABLESPACE BIAPP DATAFILE '<drive>:\oradata\<SID>\biapp.dbf' SIZE 33M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE BILARGE DATAFILE '<drive>:\oradata\<SID>\bilarge.dbf' SIZE 22M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE BIWORK DATAFILE '<drive>:\oradata\<SID>\biwork.dbf' SIZE 121M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE CAAPP DATAFILE '<drive>:\oradata\<SID>\caapp.dbf' SIZE 77M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE CAWORK DATAFILE '<drive>:\oradata\<SID>\cawork.dbf' SIZE 68M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE CFGAPP DATAFILE '<drive>:\oradata\<SID>\cfgapp.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE CPAPP DATAFILE '<drive>:\oradata\<SID>\cpapp.dbf' SIZE 8M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE CPLARGE DATAFILE '<drive>:\oradata\<SID>\cplarge.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE CSAPP DATAFILE '<drive>:\oradata\<SID>\csapp.dbf' SIZE 8M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE CSLARGE DATAFILE '<drive>:\oradata\<SID>\cslarge.dbf' SIZE 3M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE CSWORK DATAFILE '<drive>:\oradata\<SID>\cswork.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE CUAUDIT DATAFILE '<drive>:\oradata\<SID>\cuaudit.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE CULARG1 DATAFILE '<drive>:\oradata\<SID>\cularg1.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE CULARG2 DATAFILE '<drive>:\oradata\<SID>\cularg2.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE CULARG3 DATAFILE '<drive>:\oradata\<SID>\cularg3.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE CULARGE DATAFILE '<drive>:\oradata\<SID>\cularge.dbf' SIZE 4M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE DIAPP DATAFILE '<drive>:\oradata\<SID>\diapp.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE DPAPP DATAFILE '<drive>:\oradata\<SID>\dpapp.dbf' SIZE 37M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE DPLARGE DATAFILE '<drive>:\oradata\<SID>\dplarge.dbf' SIZE 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE DPWORK DATAFILE '<drive>:\oradata\<SID>\dpwork.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE EOAPP DATAFILE '<drive>:\oradata\<SID>\eoapp.dbf' SIZE 3M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE EOBFAPP DATAFILE '<drive>:\oradata\<SID>\eobfapp.dbf' SIZE 3M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE EOCFAPP DATAFILE '<drive>:\oradata\<SID>\eocfapp.dbf' SIZE 8M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE EOCMAPP DATAFILE '<drive>:\oradata\<SID>\eocmapp.dbf' SIZE 72M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE EOCMLRG DATAFILE '<drive>:\oradata\<SID>\eocmlrg.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE EOCMWRK DATAFILE '<drive>:\oradata\<SID>\eocmwrk.dbf' SIZE 5M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE EOCUAPP DATAFILE '<drive>:\oradata\<SID>\eocuapp.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE EOCULRG DATAFILE '<drive>:\oradata\<SID>\eoculrg.dbf' SIZE 106M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE EODSAPP DATAFILE '<drive>:\oradata\<SID>\eodsapp.dbf' SIZE 5M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE EODSLRG DATAFILE '<drive>:\oradata\<SID>\eodslrg.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE EOECAPP DATAFILE '<drive>:\oradata\<SID>\eoecapp.dbf' SIZE 5M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE EOECLRG DATAFILE '<drive>:\oradata\<SID>\eoeclrg.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE EOECWRK DATAFILE '<drive>:\oradata\<SID>\eoecwrk.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE EOEIAPP DATAFILE '<drive>:\oradata\<SID>\eoeiapp.dbf' SIZE 133M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE EOEILRG DATAFILE '<drive>:\oradata\<SID>\eoeilrg.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE EOEPAPP DATAFILE '<drive>:\oradata\<SID>\eoepapp.dbf' SIZE 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE EOEPLRG DATAFILE '<drive>:\oradata\<SID>\eoeplrg.dbf' SIZE 5M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE EOEPWRK DATAFILE '<drive>:\oradata\<SID>\eoepwrk.dbf' SIZE 16M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE EOEWAPP DATAFILE '<drive>:\oradata\<SID>\eoewapp.dbf' SIZE 6M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE EOEWLRG DATAFILE '<drive>:\oradata\<SID>\eoewlrg.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE EOEWWRK DATAFILE '<drive>:\oradata\<SID>\eoewwrk.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE EOIUAPP DATAFILE '<drive>:\oradata\<SID>\eoiuapp.dbf' SIZE 5M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE EOIULRG DATAFILE '<drive>:\oradata\<SID>\eoiulrg.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE EOIUWRK DATAFILE '<drive>:\oradata\<SID>\eoiuwrk.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE EOLARGE DATAFILE '<drive>:\oradata\<SID>\eolarge.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE EOLTAPP DATAFILE '<drive>:\oradata\<SID>\eoltapp.dbf' SIZE 5M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE EOPPAPP DATAFILE '<drive>:\oradata\<SID>\eoppapp.dbf' SIZE 4M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE EOPPLRG DATAFILE '<drive>:\oradata\<SID>\eopplrg.dbf' SIZE 3M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE EOTPAPP DATAFILE '<drive>:\oradata\<SID>\eotpapp.dbf' SIZE 3M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE EOTPLRG DATAFILE '<drive>:\oradata\<SID>\eotplrg.dbf' SIZE 3M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE EXAPP DATAFILE '<drive>:\oradata\<SID>\exapp.dbf' SIZE 13M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE EXARCH DATAFILE '<drive>:\oradata\<SID>\exarch.dbf' SIZE 3M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE EXLARGE DATAFILE '<drive>:\oradata\<SID>\exlarge.dbf' SIZE 12M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE EXWORK DATAFILE '<drive>:\oradata\<SID>\exwork.dbf' SIZE 81M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE FAAPP DATAFILE '<drive>:\oradata\<SID>\faapp.dbf' SIZE 32M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE FALARGE DATAFILE '<drive>:\oradata\<SID>\falarge.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE FAWORK DATAFILE '<drive>:\oradata\<SID>\fawork.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE FGAPP DATAFILE '<drive>:\oradata\<SID>\fgapp.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE FGARCH DATAFILE '<drive>:\oradata\<SID>\fgarch.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE FGIMAGE DATAFILE '<drive>:\oradata\<SID>\fgimage.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE FGLARGE DATAFILE '<drive>:\oradata\<SID>\fglarge.dbf' SIZE 6M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE FGTEMP DATAFILE '<drive>:\oradata\<SID>\fgtemp.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE FGWORK DATAFILE '<drive>:\oradata\<SID>\fgwork.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE FIAPP DATAFILE '<drive>:\oradata\<SID>\fiapp.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE FILARGE DATAFILE '<drive>:\oradata\<SID>\filarge.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE FOAPP DATAFILE '<drive>:\oradata\<SID>\foapp.dbf' SIZE 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE FOIMAGE DATAFILE '<drive>:\oradata\<SID>\foimage.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE FOLARGE DATAFILE '<drive>:\oradata\<SID>\folarge.dbf' SIZE 8M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE FOWORK DATAFILE '<drive>:\oradata\<SID>\fowork.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE FSAPP DATAFILE '<drive>:\oradata\<SID>\fsapp.dbf' SIZE 202M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE FSAPP1 DATAFILE '<drive>:\oradata\<SID>\fsapp1.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE FSLARGE DATAFILE '<drive>:\oradata\<SID>\fslarge.dbf' SIZE 45M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE FSWORK DATAFILE '<drive>:\oradata\<SID>\fswork.dbf' SIZE 49M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE GLAPP DATAFILE '<drive>:\oradata\<SID>\glapp.dbf' SIZE 184M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE GLARCH DATAFILE '<drive>:\oradata\<SID>\glarch.dbf' SIZE 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE GLLARGE DATAFILE '<drive>:\oradata\<SID>\gllarge.dbf' SIZE 99M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE GLWORK DATAFILE '<drive>:\oradata\<SID>\glwork.dbf' SIZE 121M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE GMAPP DATAFILE '<drive>:\oradata\<SID>\gmapp.dbf' SIZE 41M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE HRAPP DATAFILE '<drive>:\oradata\<SID>\hrapp.dbf' SIZE 6M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE HRLARGE DATAFILE '<drive>:\oradata\<SID>\hrlarge.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE HTAPP DATAFILE '<drive>:\oradata\<SID>\htapp.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE INAPP DATAFILE '<drive>:\oradata\<SID>\inapp.dbf' SIZE 128M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE INARCH DATAFILE '<drive>:\oradata\<SID>\inarch.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE INLARGE DATAFILE '<drive>:\oradata\<SID>\inlarge.dbf' SIZE 75M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE INWORK DATAFILE '<drive>:\oradata\<SID>\inwork.dbf' SIZE 319M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE LCAPP DATAFILE '<drive>:\oradata\<SID>\lcapp.dbf' SIZE 175M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE LCLARGE DATAFILE '<drive>:\oradata\<SID>\lclarge.dbf' SIZE 8M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE MGAPP DATAFILE '<drive>:\oradata\<SID>\mgapp.dbf' SIZE 144M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE MGLARGE DATAFILE '<drive>:\oradata\<SID>\mglarge.dbf' SIZE 7M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE MPAPP DATAFILE '<drive>:\oradata\<SID>\mpapp.dbf' SIZE 12M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE MPLARGE DATAFILE '<drive>:\oradata\<SID>\mplarge.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE MPWORK DATAFILE '<drive>:\oradata\<SID>\mpwork.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE OEAPP DATAFILE '<drive>:\oradata\<SID>\oeapp.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE OMAPP DATAFILE '<drive>:\oradata\<SID>\omapp.dbf' SIZE 55M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE OMLARGE DATAFILE '<drive>:\oradata\<SID>\omlarge.dbf' SIZE 27M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE OMWORK DATAFILE '<drive>:\oradata\<SID>\omwork.dbf' SIZE 367M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE PBAPP DATAFILE '<drive>:\oradata\<SID>\pbapp.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE PBIMAGE DATAFILE '<drive>:\oradata\<SID>\pbimage.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE PBLARGE DATAFILE '<drive>:\oradata\<SID>\pblarge.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE PBWORK DATAFILE '<drive>:\oradata\<SID>\pbwork.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE PCAPP DATAFILE '<drive>:\oradata\<SID>\pcapp.dbf' SIZE 84M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE PCARCH DATAFILE '<drive>:\oradata\<SID>\pcarch.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE PCLARGE DATAFILE '<drive>:\oradata\<SID>\pclarge.dbf' SIZE 47M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE PCWORK DATAFILE '<drive>:\oradata\<SID>\pcwork.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE PGMAPP DATAFILE '<drive>:\oradata\<SID>\pgmapp.dbf' SIZE 24M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE PGMLARGE DATAFILE '<drive>:\oradata\<SID>\pgmlarge.dbf' SIZE 9M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE PGMWORK DATAFILE '<drive>:\oradata\<SID>\pgmwork.dbf' SIZE 51M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE PIPSAPP DATAFILE '<drive>:\oradata\<SID>\pipsapp.dbf' SIZE 5M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE PIPSLRG DATAFILE '<drive>:\oradata\<SID>\pipslrg.dbf' SIZE 5M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE PIPSWORK DATAFILE '<drive>:\oradata\<SID>\pipswork.dbf' SIZE 5M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE PLAPP DATAFILE '<drive>:\oradata\<SID>\plapp.dbf' SIZE 37M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE PLLARGE DATAFILE '<drive>:\oradata\<SID>\pllarge.dbf' SIZE 29M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE PLWORK DATAFILE '<drive>:\oradata\<SID>\plwork.dbf' SIZE 7M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE POAPP DATAFILE '<drive>:\oradata\<SID>\poapp.dbf' SIZE 112M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE POLARGE DATAFILE '<drive>:\oradata\<SID>\polarge.dbf' SIZE 39M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE POWORK DATAFILE '<drive>:\oradata\<SID>\powork.dbf' SIZE 286M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE PSIMAGE DATAFILE '<drive>:\oradata\<SID>\psimage.dbf' SIZE 850M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE PSIMGR DATAFILE '<drive>:\oradata\<SID>\psimgr.dbf' SIZE 5M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/
         
CREATE TABLESPACE PSINDEX DATAFILE '<drive>:\oradata\<SID>\psindex.dbf' SIZE 7500M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE PSWORK DATAFILE '<drive>:\oradata\<SID>\pswork.dbf' SIZE 5M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE PTAMSG DATAFILE '<drive>:\oradata\<SID>\ptamsg.dbf' SIZE 5M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE PTAPP DATAFILE '<drive>:\oradata\<SID>\ptapp.dbf' SIZE 21M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE PTAPPE DATAFILE '<drive>:\oradata\<SID>\ptappe.dbf' SIZE 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE PTAUDIT DATAFILE '<drive>:\oradata\<SID>\ptaudit.dbf' SIZE 5M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE PTCMSTAR DATAFILE '<drive>:\oradata\<SID>\ptcmstar.dbf' SIZE 5M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE PTLOCK DATAFILE '<drive>:\oradata\<SID>\ptlock.dbf' SIZE 5M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE PTPRC DATAFILE '<drive>:\oradata\<SID>\ptprc.dbf' SIZE 6M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE PTPRJWK DATAFILE '<drive>:\oradata\<SID>\ptprjwk.dbf' SIZE 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE PTRPTS DATAFILE '<drive>:\oradata\<SID>\ptrpts.dbf' SIZE 5M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE PTTBL DATAFILE '<drive>:\oradata\<SID>\pttbl.dbf' SIZE 175M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE PTTLRG DATAFILE '<drive>:\oradata\<SID>\pttlrg.dbf' SIZE 565M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE PTTREE DATAFILE '<drive>:\oradata\<SID>\pttree.dbf' SIZE 5M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE PTWORK DATAFILE '<drive>:\oradata\<SID>\ptwork.dbf' SIZE 8M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE PVAPP DATAFILE '<drive>:\oradata\<SID>\pvapp.dbf' SIZE 36M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE PYAPP DATAFILE '<drive>:\oradata\<SID>\pyapp.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE RBAPP DATAFILE '<drive>:\oradata\<SID>\rbapp.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE RBTEMP DATAFILE '<drive>:\oradata\<SID>\rbtemp.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE REAPP DATAFILE '<drive>:\oradata\<SID>\reapp.dbf' SIZE 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE REIMAGE DATAFILE '<drive>:\oradata\<SID>\reimage.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE RELARGE DATAFILE '<drive>:\oradata\<SID>\relarge.dbf' SIZE 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE REWORK DATAFILE '<drive>:\oradata\<SID>\rework.dbf' SIZE 9M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE ROAPP DATAFILE '<drive>:\oradata\<SID>\roapp.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE RSAPP DATAFILE '<drive>:\oradata\<SID>\rsapp.dbf' SIZE 37M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE RSFAPP DATAFILE '<drive>:\oradata\<SID>\rsfapp.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE RSLARGE DATAFILE '<drive>:\oradata\<SID>\rslarge.dbf' SIZE 12M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE RSWORK DATAFILE '<drive>:\oradata\<SID>\rswork.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE SACAPP DATAFILE '<drive>:\oradata\<SID>\sacapp.dbf' SIZE 7M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE SACLRGE DATAFILE '<drive>:\oradata\<SID>\saclrge.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE SPAPP DATAFILE '<drive>:\oradata\<SID>\spapp.dbf' SIZE 95M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE SPLARGE DATAFILE '<drive>:\oradata\<SID>\splarge.dbf' SIZE 10M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE TDAPP DATAFILE '<drive>:\oradata\<SID>\tdapp.dbf' SIZE 5M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE TDLARGE DATAFILE '<drive>:\oradata\<SID>\tdlarge.dbf' SIZE 6M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE TDWORK DATAFILE '<drive>:\oradata\<SID>\tdwork.dbf' SIZE 7M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE TLAPP DATAFILE '<drive>:\oradata\<SID>\tlapp.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE TLWORK DATAFILE '<drive>:\oradata\<SID>\tlwork.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE TPMAPP DATAFILE '<drive>:\oradata\<SID>\tpmapp.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE TRAPP DATAFILE '<drive>:\oradata\<SID>\trapp.dbf' SIZE 69M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE TRARCH DATAFILE '<drive>:\oradata\<SID>\trarch.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE TRIMAGE DATAFILE '<drive>:\oradata\<SID>\trimage.dbf' SIZE 4M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/
       
CREATE TABLESPACE TRLARGE DATAFILE '<drive>:\oradata\<SID>\trlarge.dbf' SIZE 7M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE TRWORK DATAFILE '<drive>:\oradata\<SID>\trwork.dbf' SIZE 28M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE WMAPP DATAFILE '<drive>:\oradata\<SID>\wmapp.dbf' SIZE 22M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE WMIMAGE DATAFILE '<drive>:\oradata\<SID>\wmimage.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE WMLARGE DATAFILE '<drive>:\oradata\<SID>\wmlarge.dbf' SIZE 20M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE WMWORK DATAFILE '<drive>:\oradata\<SID>\wmwork.dbf' SIZE 23M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE WSAPP DATAFILE '<drive>:\oradata\<SID>\wsapp.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

CREATE TABLESPACE WSLARGE DATAFILE '<drive>:\oradata\<SID>\wslarge.dbf' SIZE 2M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
/

Remark * Users can choose to use the autoextending tablespace feature
Remark * by uncommenting the following lines.

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\amapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\amarch.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\amlarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\amwork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\apapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\aparch.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\aplarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\apwork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\arapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\ararch.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\arlarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;
 
REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\arwork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\aucapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\auclrge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\bcapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\bdapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\bdlarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;
            
REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\biapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\bilarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\biwork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\caapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\cawork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\cfgapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\cpapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\cplarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\csapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\cslarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\cswork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\cuaudit.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\cularg1.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\cularg2.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\cularg3.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\cularge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\diapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\dpapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\dplarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\dpwork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\eoapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\eobfapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\eocfapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\eocmapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\eocmlrg.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\eocmwrk.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\eocuapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\eoculrg.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\eodsapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\eodslrg.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\eoecapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\eoeclrg.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\eoecwrk.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\eoeiapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\eoeilrg.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\eoepapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\eoeplrg.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\eoepwrk.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\eoewapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\eoewlrg.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\eoewwrk.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\eoiuapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\eoiulrg.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\eoiuwrk.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\eolarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\eoltapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\eoppapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\eopplrg.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\eotpapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\eotplrg.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\exapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\exarch.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\exlarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\exwork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\faapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\falarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\fawork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\fgapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\fgarch.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\fgimage.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\fglarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\fgtemp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\fgwork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\fiapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\filarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\foapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\foimage.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\folarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\fowork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\fsapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;
 
REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\fsapp1.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;
 
REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\fslarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;
 
REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\fswork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\glapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\glarch.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\gllarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\glwork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\gmapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\hrapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;
 
REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\hrlarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\htapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\inapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\inarch.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\inlarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\inwork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\lcapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\lclarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\mgapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\mglarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\mpapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\mplarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\mpwork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\oeapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\omapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;
 
REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\omlarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;      
 
REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\omwork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\pbapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\pbimage.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\pblarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\pbwork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\pcapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\pcarch.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\pclarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\pcwork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\pgmapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;
 
REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\pgmlarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;
 
REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\pgmwork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\pipsapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;
 
REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\pipslrg.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;
 
REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\pipswork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\plapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;
 
REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\pllarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;
 
REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\plwork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\poapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;
 
REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\polarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;
 
REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\powork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\psimage.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\psimgr.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ; 

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\psindex.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\pswork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\ptamsg.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\ptapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\ptappe.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\ptaudit.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\ptcmstar.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\ptlock.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\ptprc.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;
 
REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\ptprjwk.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\ptrpts.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\pttbl.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\pttlrg.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\pttree.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\ptwork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\pvapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\pvlarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\pyapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\rbapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\rbtemp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\reapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\reimage.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\relarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\rework.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\roapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\rsapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\rsfapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\rslarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\rswork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\sacapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\saclrge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\spapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\splarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\tdapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\tdlarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\tdwork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\tlapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\tlwork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\tpmapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\trapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\trarch.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\trimage.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\trlarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\trwork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\wmapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\wmimage.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\wmlarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\wmwork.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\wsapp.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

REMARK ALTER DATABASE DATAFILE '<drive>:\oradata\<SID>\wslarge.dbf' AUTOEXTEND ON NEXT 5M MAXSIZE UNLIMITED ;

spool off;
