Attribute VB_Name = "A2AConst"
Option Explicit

' Object type aliases
Public Const OTA_ABS As String = "Abs"
Public Const OTA_ABS_ABS_TYPE As String = "AbsAbsType"
Public Const OTA_ABS_GRP As String = "AbsGrp"
Public Const OTA_ABS_TYPE As String = "AbsType"
Public Const OTA_ABS_TYPE_GRP As String = "AbsTypeGrp"
Public Const OTA_ABS_TYPE_GRP_ABS_TYPE As String = "AbsTypeGrpAbsType"
Public Const OTA_DIS As String = "Dis"
Public Const OTA_DIS_ACT As String = "DisAct"
Public Const OTA_DIS_ACT_TYPE As String = "DisActType"
Public Const OTA_DIS_TYPE As String = "DisType"
Public Const OTA_EMP As String = "Emp"
Public Const OTA_NOTIF As String = "Notif"
Public Const OTA_NOTIF_TYPE As String = "NotifType"
Public Const OTA_RULE As String = "Rule"
Public Const OTA_SRC As String = "Src"
Public Const OTA_USER As String = "User"
Public Const OTA_USER_TYPE As String = "UserType"
Public Const OTA_USER_WATCH_EMP As String = "UserWatchEmp"
Public Const OTA_USER_PROXY As String = "UserProxy"
Public Const OTA_ABS_TO_REPLACE As String = "AbsToReplace"
Public Const OTA_WATCH_PREF As String = "WatchPref"
Public Const OTA_EMP_FMLA As String = "EmpFMLA"
Public Const OTA_ABS_CAL_DAY As String = "AbsCalDay"
Public Const OTA_EXTENDED_EMP_INFO As String = "ExtendedEmpInfo"
Public Const OTA_SUMM_ABS_TO_REPL As String = "SummAbsToRepl"
Public Const OTA_EXT_NOTIF As String = "ExtNotif"
Public Const OTA_SEC_OVERRIDE As String = "SecOverride"
Public Const OTA_EXT_WATCH_PREF = "ExtWatchPref"
Public Const OTA_AREA = "Area"
Public Const OTA_EXT_ABS = "ExtAbs"
Public Const OTA_ABS_TO_REPL_ABS_TYPE = "AbsToReplAbsType"

' Object attribute aliases
Public Const OAA_ABS_SYSKEY As String = "absSyskey"
Public Const OAA_ABS_ID As String = "absId"
Public Const OAA_ABS_DATE As String = "absDate"
Public Const OAA_ABS_EMPLOYEE As String = "absEmployee"
Public Const OAA_ABS_IS_REPLACED As String = "absIsReplaced"
Public Const OAA_ABS_REPLACED_BY As String = "absReplacedBy"
Public Const OAA_ABS_SOURCE As String = "absSource"
Public Const OAA_ABS_CREATOR As String = "absCreator"
Public Const OAA_ABS_DATE_CREATED As String = "absDateCreated"
Public Const OAA_ABS_PRIMARY_ABS_TYPE As String = "absPrimAbsType"
Public Const OAA_ABS_AREA As String = "absArea"

Public Const OAA_ABS_ABS_TYPE_SYSKEY As String = "absabstypeSyskey"
Public Const OAA_ABS_ABS_TYPE_ID As String = "absabstypeId"
Public Const OAA_ABS_ABS_TYPE_ABSENCE As String = "absabstypeAbsence"
Public Const OAA_ABS_ABS_TYPE_ABS_TYPE As String = "absabstypeAbsType"
Public Const OAA_ABS_ABS_TYPE_MINUTES As String = "absabstypeMinutes"

Public Const OAA_ABS_GRP_SYSKEY As String = "absgrpSyskey"
Public Const OAA_ABS_GRP_ID As String = "absgrpId"
Public Const OAA_ABS_GRP_CREATOR As String = "absgrpCreator"

Public Const OAA_ABS_TYPE_SYSKEY As String = "abstypeSyskey"
Public Const OAA_ABS_TYPE_ID As String = "abstypeId"
Public Const OAA_ABS_TYPE_DESC As String = "abstypeDesc"
Public Const OAA_ABS_TYPE_SHORT_DESC As String = "abstypeShortDesc"
Public Const OAA_ABS_TYPE_ALIAS As String = "abstypeAlias"
Public Const OAA_ABS_TYPE_APP_ORDER As String = "abstypeAppOrder"
Public Const OAA_ABS_TYPE_IS_PROTECTED As String = "abstypeIsProtected"
Public Const OAA_ABS_TYPE_IS_UNPROTECTED As String = "abstypeIsUnprotected"
Public Const OAA_ABS_TYPE_IS_WORKED As String = "abstypeIsWorked"
Public Const OAA_ABS_TYPE_INACTIVE As String = "abstypeInactive"
Public Const OAA_ABS_TYPE_INSTANCE_POINTS As String = "abstypeInstancePoints"
Public Const OAA_ABS_TYPE_DAY_POINTS As String = "abstypeDayPoints"
Public Const OAA_ABS_TYPE_SPECIAL As String = "abstypeHasSpecialHandling"
Public Const OAA_ABS_TYPE_NAME_ON_SLIPS As String = "abstypeNameOnDisSlips"

Public Const OAA_ABS_TYPE_GRP_SYSKEY As String = "abstypegrpSyskey"
Public Const OAA_ABS_TYPE_GRP_ID As String = "abstypegrpId"
Public Const OAA_ABS_TYPE_GRP_DESC As String = "abstypegrpDesc"
Public Const OAA_ABS_TYPE_GRP_SHORT_DESC As String = "abstypegrpShortDesc"
Public Const OAA_ABS_TYPE_GRP_IS_UNPROT As String = "abstypegrpIsUnprotected"
Public Const OAA_ABS_TYPE_GRP_IS_WORKED As String = "abstypegrpIsWorked"
Public Const OAA_ABS_TYPE_GRP_ALIAS As String = "abstypegrpAlias"

Public Const OAA_ABS_TYPE_GRP_ABS_TYPE_SYSKEY As String = "abstypegrpabstypeSyskey"
Public Const OAA_ABS_TYPE_GRP_ABS_TYPEID As String = "abstypegrpabstypeId"
Public Const OAA_ABS_TYPE_GRP_ABS_TYPE_ABS_TYPE_GRP As String = "abstypegrpabstypeAbsTypeGrp"
Public Const OAA_ABS_TYPE_GRP_ABS_TYPE_ABS_TYPE As String = "abstypegrpabstypeAbsType"

Public Const OAA_DIS_SYSKEY As String = "disSyskey"
Public Const OAA_DIS_ID As String = "disId"
Public Const OAA_DIS_INIT_DATE As String = "disInitDate"
Public Const OAA_DIS_DIS_TYPE As String = "disDisType"
Public Const OAA_DIS_ABS_GRP As String = "disAbsGrp"
Public Const OAA_DIS_EMP As String = "disEmp"
Public Const OAA_DIS_INIT_USER As String = "disInitUser"
Public Const OAA_DIS_RULE As String = "disRule"
Public Const OAA_DIS_STATUS As String = "disStatus"
Public Const OAA_DIS_DATE_TRIGGERED As String = "disDateTriggered"
Public Const OAA_DIS_AREA_AT_INIT As String = "disAreaAtInit"
Public Const OAA_DIS_EFF_DATE As String = "disEffDate"
Public Const OAA_DIS_TRIGGER_NOTE As String = "disTriggerNote"

Public Const OAA_DIS_ACT_SYSKEY As String = "disactSyskey"
Public Const OAA_DIS_ACT_ID As String = "disactId"
Public Const OAA_DIS_ACT_DIS As String = "disactDis"
Public Const OAA_DIS_ACT_TYPE As String = "disactType"
Public Const OAA_DIS_ACT_EFF_DATE As String = "disactEffDate"
Public Const OAA_DIS_ACT_NOTES As String = "disactNotes"
Public Const OAA_DIS_ACT_CREATOR As String = "disactCreator"
Public Const OAA_DIS_ACT_DATE_CREATED As String = "disactDateCreated"

Public Const OAA_DIS_ACT_TYPE_SYSKEY As String = "disacttypeSyskey"
Public Const OAA_DIS_ACT_TYPE_ID As String = "disacttypeId"
Public Const OAA_DIS_ACT_TYPE_DESC As String = "disacttypeDesc"
Public Const OAA_DIS_ACT_TYPE_SHORT_DESC As String = "disacttypeShortDesc"
Public Const OAA_DIS_ACT_TYPE_SETS_STATUS_TO As String = "disacttypeSetsDisStatusTo"
Public Const OAA_DIS_ACT_TYPE_SETS_TYPE_TO As String = "disacttypeSetsDisTypeTo"
Public Const OAA_DIS_ACT_TYPE_SORT_ORDER As String = "disacttypeSortOrder"
Public Const OAA_DIS_ACT_TYPE_IS_INACTIVE As String = "disacttypeIsInactive"

Public Const OAA_DIS_TYPE_SYSKEY As String = "distypeSyskey"
Public Const OAA_DIS_TYPE_ID As String = "distypeId"
Public Const OAA_DIS_TYPE_DESC As String = "distypeDesc"
Public Const OAA_DIS_TYPE_SHORT_DESC As String = "distypeShortDesc"
Public Const OAA_DIS_TYPE_HAS_ABS_GRP As String = "distypeHasAbsGrp"

Public Const OAA_EMP_SYSKEY As String = "empSyskey"
Public Const OAA_EMP_ID As String = "empId"
Public Const OAA_EMP_BADGE_NUM As String = "empBadgeNum"
Public Const OAA_EMP_NAME As String = "empName"
Public Const OAA_EMP_IS_INACTIVE As String = "empIsInactive"
Public Const OAA_EMP_REPORTS_TO As String = "empReportsTo"
Public Const OAA_EMP_LAST_DATE_WORKED As String = "empLastDateWorked"

Public Const OAA_NOTIF_SYSKEY As String = "notifSyskey"
Public Const OAA_NOTIF_ID As String = "notifId"
Public Const OAA_NOTIF_TYPE As String = "notifType"
Public Const OAA_NOTIF_EMP As String = "notifEmp"
Public Const OAA_NOTIF_DATE_CREATED As String = "notifDateCreated"
Public Const OAA_NOTIF_IS_CANCELLED As String = "notifIsCancelled"
Public Const OAA_NOTIF_RULE As String = "notifRule"
Public Const OAA_NOTIF_ABS_GRP As String = "notifAbsGrp"
Public Const OAA_NOTIF_DATE_TRIGGERED As String = "notifDateTriggered"
Public Const OAA_NOTIF_TRIGGER_NOTE As String = "notifTriggerNote"

Public Const OAA_NOTIF_TYPE_SYSKEY As String = "notiftypeSyskey"
Public Const OAA_NOTIF_TYPE_ID As String = "notiftypeId"
Public Const OAA_NOTIF_TYPE_DESC As String = "notiftypeDesc"
Public Const OAA_NOTIF_TYPE_SHORT_DESC As String = "notiftypeShortDesc"
Public Const OAA_NOTIF_TYPE_SEVERITY As String = "notiftypeSeverity"
Public Const OAA_NOTIF_TYPE_ALIAS As String = "notiftypeAlias"

Public Const OAA_RULE_SYSKEY As String = "ruleSyskey"
Public Const OAA_RULE_ID As String = "ruleId"
Public Const OAA_RULE_ALIAS As String = "ruleAlias"
Public Const OAA_RULE_DESC As String = "ruleDesc"
Public Const OAA_RULE_SHORT_DESC As String = "ruleShortDesc"

Public Const OAA_SRC_SYSKEY As String = "srcSyskey"
Public Const OAA_SRC_ID As String = "srcId"
Public Const OAA_SRC_DESC As String = "srcDesc"
Public Const OAA_SRC_SHORT_DESC As String = "srcShortDesc"

Public Const OAA_USER_SYSKEY As String = "userSyskey"
Public Const OAA_USER_ID As String = "userId"
Public Const OAA_USER_USERNAME As String = "userUsername"
Public Const OAA_USER_DISPLAY_NAME As String = "userDisplayName"
Public Const OAA_USER_SORT_NAME As String = "userSortName"
Public Const OAA_USER_TYPE As String = "userType"
Public Const OAA_USER_EMP As String = "userEmp"
Public Const OAA_USER_CAN_ALTER_SECURITY As String = "userCanAlterSecurity"
Public Const OAA_USER_CAN_ALTER_OWN_WATCHES As String = "userCanAlterOwnWatches"
Public Const OAA_USER_IS_DISABLED As String = "userIsDisabled"
Public Const OAA_USER_TKS_USERNAME As String = "userTKSUsername"
Public Const OAA_USER_EMAIL_ENABLED As String = "userIsEmailEnabled"
Public Const OAA_USER_EMAIL_ADDRESS As String = "userEmailAddress"
Public Const OAA_USER_OPEN_NOTIF_EMAIL_DAYS As String = "userOpenNotifEmailThreshold"
Public Const OAA_USER_OPEN_DIS_EMAIL_DAYS As String = "userOpenDisEmailThreshold"

Public Const OAA_USER_TYPE_SYSKEY As String = "usertypeSyskey"
Public Const OAA_USER_TYPE_ID As String = "usertypeId"
Public Const OAA_USER_TYPE_DESC As String = "usertypeDesc"
Public Const OAA_USER_TYPE_SHORT_DESC As String = "usertypeShortDesc"
Public Const OAA_USER_TYPE_IS_EMPLOYEE As String = "usertypeIsEmployee"

Public Const OAA_ABS_GRP_ABS_SYSKEY As String = "absgrpabsSyskey"
Public Const OAA_ABS_GRP_ABS_ID As String = "absgrpabsId"
Public Const OAA_ABS_GRP_ABS_ABS_GRP As String = "absgrpabsAbsGrp"
Public Const OAA_ABS_GRP_ABS_ABS As String = "absgrpabsAbs"

Public Const OAA_USER_PROXY_SYSKEY As String = "userproxySyskey"
Public Const OAA_USER_PROXY_ID As String = "userproxyId"
Public Const OAA_USER_PROXY_CAN_ACT As String = "userproxyCanAct"
Public Const OAA_USER_PROXY_ACT_AS As String = "userproxyActAs"

Public Const OAA_ABS_TO_REPLACE_SYSKEY As String = "abstoreplSyskey"
Public Const OAA_ABS_TO_REPLACE_ID As String = "abstoreplId"
Public Const OAA_ABS_TO_REPLACE_EMP As String = "abstoreplEmp"
Public Const OAA_ABS_TO_REPLACE_DATE As String = "abstoreplDate"

Public Const OAA_WATCH_PREF_SYSKEY As String = "watchprefSyskey"
Public Const OAA_WATCH_PREF_ID As String = "watchprefId"
Public Const OAA_WATCH_PREF_USER As String = "watchprefUser"
Public Const OAA_WATCH_PREF_AREA_NUM As String = "watchprefAreaNum"
Public Const OAA_WATCH_PREF_IS_WATCHING As String = "watchprefIsWatching"

Public Const OAA_EMP_FMLA_SYSKEY As String = "empfmlaSyskey"
Public Const OAA_EMP_FMLA_ID As String = "empfmlaId"
Public Const OAA_EMP_FMLA_EMP As String = "empfmlaEmp"
Public Const OAA_EMP_FMLA_LEAVE_REASON As String = "empfmlaLeaveReason"
Public Const OAA_EMP_FMLA_LEAVE_TYPE As String = "empfmlaLeaveType"
Public Const OAA_EMP_FMLA_BEGIN_DATE As String = "empfmlaBeginDate"
Public Const OAA_EMP_FMLA_END_DATE As String = "empfmlaEndDate"
Public Const OAA_EMP_FMLA_LEAVE_STATUS As String = "empfmlaLeaveStatus"

Public Const OAA_ABS_CAL_DAY_DATE As String = "abscaldayDate"
Public Const OAA_ABS_CAL_DAY_EMP As String = "abscaldayEmp"
Public Const OAA_ABS_CAL_DAY_PROTECTED As String = "abscaldayIsProtected"
Public Const OAA_ABS_CAL_DAY_UNPROTECTED As String = "abscaldayIsUnprotected"
Public Const OAA_ABS_CAL_DAY_WORKED As String = "abscaldayIsWorked"
Public Const OAA_ABS_CAL_DAY_INST_PTS As String = "abscaldayInstancePoints"
Public Const OAA_ABS_CAL_DAY_DAY_PTS As String = "abscaldayDayPoints"
Public Const OAA_ABS_CAL_DAY_SPECIAL As String = "abscaldayHasSpecialHandling"
Public Const OAA_ABS_CAL_DAY_ABS As String = "abscaldayAbsReference"
Public Const OAA_ABS_CAL_DAY_HAS_WORK As String = "abscaldayHasAnyWork"

Public Const OAA_EXT_EMP_INFO_SYSKEY As String = "extendedempinfoSyskey"
Public Const OAA_EXT_EMP_INFO_ID As String = "extendedempinfoId"
Public Const OAA_EXT_EMP_INFO_EMP As String = "extendedempinfoEmp"
Public Const OAA_EXT_EMP_INFO_BADGE_NUM As String = "extendedempinfoBadgeNum"
Public Const OAA_EXT_EMP_INFO_FIRST_NAME As String = "extendedempinfoFirstName"
Public Const OAA_EXT_EMP_INFO_LAST_NAME As String = "extendedempinfoLastName"
Public Const OAA_EXT_EMP_INFO_MIDDLE_NAME As String = "extendedempinfoMiddleName"
Public Const OAA_EXT_EMP_INFO_AREA_NUM As String = "extendedempinfoAreaNum"
Public Const OAA_EXT_EMP_INFO_AREA_DESC As String = "extendedempinfoAreaDesc"
Public Const OAA_EXT_EMP_INFO_AREA_GRP_DESC As String = "extendedempinfoAreaGrpDesc"
Public Const OAA_EXT_EMP_INFO_SSN As String = "extendedempinfoSSN"
Public Const OAA_EXT_EMP_INFO_TITLE As String = "extendedempinfoTitle"
Public Const OAA_EXT_EMP_INFO_HIRE_DATE As String = "extendedempinfoHireDate"
Public Const OAA_EXT_EMP_INFO_UNION_CODE As String = "extendedempinfoUnionCode"

Public Const OAA_SUMM_ABS_TO_REPL_ID As String = "summabstoreplId"
Public Const OAA_SUMM_ABS_TO_REPL_LOW_NUM As String = "summabstoreplLowAbs"
Public Const OAA_SUMM_ABS_TO_REPL_HIGH_NUM As String = "summabstoreplHighAbs"

Public Const OAA_EXT_NOTIF_SYSKEY As String = "extnotifSyskey"
Public Const OAA_EXT_NOTIF_ID As String = "extnotifId"
Public Const OAA_EXT_NOTIF_DATE_CREATED As String = "extNotifDateCreated"
Public Const OAA_EXT_NOTIF_IS_CANCELLED As String = "extNotifIsCancelled"
Public Const OAA_EXT_NOTIF_DATE_TRIGGERED As String = "extNotifDateTriggered"
Public Const OAA_EXT_NOTIF_SEVERITY As String = "extNotifSeverity"
Public Const OAA_EXT_NOTIF_SHORT_RULE_DESC As String = "extNotifShortRuleDesc"
Public Const OAA_EXT_NOTIF_RULE_DESC As String = "extNotifRuleDesc"
Public Const OAA_EXT_NOTIF_BADGE_NUMBER As String = "extNotifBadgeNumber"
Public Const OAA_EXT_NOTIF_LAST_NAME As String = "extNotifLastName"
Public Const OAA_EXT_NOTIF_LAST_DATE_WORKED As String = "extNotifLastDateWorked"
Public Const OAA_EXT_NOTIF_AREA_NUM As String = "extNotifAreaNum"
Public Const OAA_EXT_NOTIF_DATE_RETURNED As String = "extNotifDateReturned"
Public Const OAA_EXT_NOTIF_NOTIF_OBJ As String = "extNotifNotif"
Public Const OAA_EXT_NOTIF_IS_RETURNED As String = "extNotifIsReturned"
Public Const OAA_EXT_NOTIF_AREA_DESC As String = "extNotifAreaDesc"
Public Const OAA_EXT_NOTIF_AREA_GRP_DESC As String = "extNotifAreaGrpDesc"

Public Const OAA_SEC_OVERRIDE_SYSKEY As String = "secoverrideSyskey"
Public Const OAA_SEC_OVERRIDE_ID As String = "secoverrideId"
Public Const OAA_SEC_OVERRIDE_USER As String = "secoverrideUser"
Public Const OAA_SEC_OVERRIDE_AREA_NUM As String = "secoverrideAreaNumber"
Public Const OAA_SEC_OVERRIDE_CAN_VIEW As String = "secoverrideCanView"
Public Const OAA_SEC_OVERRIDE_CAN_ALTER As String = "secoverrideCanAlter"
Public Const OAA_SEC_OVERRIDE_IS_INACTIVE As String = "secoverrideIsInactive"

Public Const OAA_EXTWATCHPREF_SYSKEY = "extwatchprefSyskey"
Public Const OAA_EXTWATCHPREF_ID = "extwatchprefId"
Public Const OAA_EXTWATCHPREF_WATCH_PREF = "extwatchprefWatchPref"
Public Const OAA_EXTWATCHPREF_AREA_DESC = "extwatchprefAreaDesc"
Public Const OAA_EXTWATCHPREF_AREA_GRP_DESC = "extwatchprefAreaGrpDesc"
Public Const OAA_EXTWATCHPREF_USER = "extwatchprefUser"
Public Const OAA_EXTWATCHPREF_AREA_NUM = "extwatchprefAreaNum"
Public Const OAA_EXTWATCHPREF_IS_WATCHING = "extwatchprefIsWatching"

Public Const OAA_AREA_SYSKEY = "areaSyskey"
Public Const OAA_AREA_ID = "areaNum"
Public Const OAA_AREA_DESC = "areaDesc"
Public Const OAA_AREA_GRP_DESC = "areaGrpDesc"

Public Const OAA_EXTABS_SYSKEY = "extabsSyskey"
Public Const OAA_EXTABS_ID = "extabsId"
Public Const OAA_EXTABS_ABS = "extabsAbs"
Public Const OAA_EXTABS_H_T_M_L_DESC = "extabsHTMLDesc"
Public Const OAA_EXTABS_DESC = "extabsDesc"
Public Const OAA_EXTABS_BADGE_NUM = "extabsBadgeNum"
Public Const OAA_EXTABS_EMP_NAME = "extabsEmpName"
Public Const OAA_EXTABS_AREA_DESC = "extabsAreaDesc"
Public Const OAA_EXTABS_AREA_GRP_DESC = "extabsAreaGrpDesc"
Public Const OAA_EXTABS_AREA_NUM = "extabsAreaNum"
Public Const OAA_EXTABS_DATE = "extabsDate"

Public Const OAA_ABS_TO_REPL_ABS_TYPE_SYSKEY As String = "abstoreplabstypeSyskey"
Public Const OAA_ABS_TO_REPL_ABS_TYPE_ID As String = "abstoreplabstypeId"
Public Const OAA_ABS_TO_REPL_ABS_TYPE_ABS_TO_REPL As String = "abstoreplabstypeAbsenceToReplace"
Public Const OAA_ABS_TO_REPL_ABS_TYPE_ABS_TYPE As String = "abstoreplabstypeAbsType"
Public Const OAA_ABS_TO_REPL_ABS_TYPE_MINUTES As String = "abstoreplabstypeMinutes"

' Lookup type aliases
Public Const LTA_EMP_BY_BADGE_NUM As String = "EmpByBadgeNum"
    Public Const LTPA_EMP_BY_BADGE_BADGE_NUM As String = "badgeNum"

Public Const LTA_ABS_TYPE_FOR_ABS As String = "AbsTypesForAbs"
    Public Const LTPA_ABS_TYPS_FOR_ABS_ABS As String = "abs"

Public Const LTA_RECENT_ABS_FOR_USER As String = "GetRecentAbsForUser"
    Public Const LTPA_RECENT_ABS_FOR_USER_SINCE_DATE As String = "sinceDate"
    Public Const LTPA_RECENT_ABS_FOR_USER_PROT As String = "incProtected"
    Public Const LTPA_RECENT_ABS_FOR_USER_UNPROT As String = "incUnprotected"

Public Const LTA_OPEN_NOTIF_FOR_USER As String = "GetOpenNotifForUser"
    Public Const LTPA_OPEN_NOTIF_USER_SHOW_VIOL As String = "showViolations"
    Public Const LTPA_OPEN_NOTIF_USER_SHOW_WARN As String = "showWarnings"
    Public Const LTPA_OPEN_NOTIF_USER_SHOW_INFO As String = "showInformation"

Public Const LTA_ABS_IN_NOTIF As String = "GetAbsInNotif"
    Public Const LTPA_ABS_IN_NOTIF_NOTIF As String = "notif"

Public Const LTA_OPEN_DIS_FOR_USER As String = "GetOpenDisForUser"
    
Public Const LTA_REPLACE_ABS As String = "ReplaceAbs"
    Public Const LTPA_REPLACE_ABS_ORIG As String = "abs"
    Public Const LTPA_REPLACE_ABS_NEW_SRC As String = "src"
    
Public Const LTA_ADD_TYPE_TO_ABS As String = "AddTypeToAbs"
    Public Const LTPA_ADD_TYPE_TO_ABS_ABS As String = "abs"
    Public Const LTPA_ADD_TYPE_TO_ABS_ABS_TYPE As String = "absType"
    
Public Const LTA_UNPROT_UNWAIVED_ABS_FOR_EMP As String = "GetUnprotUnwaivedAbsForEmp"
    Public Const LTPA_UNPROT_UNWAIVED_ABS_FOR_EMP_EMP As String = "emp"
    Public Const LTPA_UNPROT_UNWAIVED_ABS_FOR_EMP_SINCE_DATE As String = "sinceDate"
    
Public Const LTA_UNPROT_ABS_FOR_EMP As String = "GetUnprotectedAbs"
    Public Const LTPA_UNPROT_ABS_FOR_EMP_EMP As String = "emp"
    Public Const LTPA_UNPROT_ABS_FOR_EMP_SINCE_DATE As String = "sinceDate"

Public Const LTA_NOTIFS_FOR_EMP As String = "GetNotifForEmp"
    Public Const LTPA_NOTIFS_FOR_EMP_EMP As String = "emp"
    Public Const LTPA_NOTIFS_FOR_EMP_OPEN_ONLY As String = "openOnly"

Public Const LTA_ABS_IN_ABS_GRP As String = "GetAbsInAbsGrp"
    Public Const LTPA_ABS_IN_ABS_GRP As String = "absGrp"

Public Const LTA_ADD_ABS_GRP As String = "AddAbsGrp"

Public Const LTA_ADD_ABS_TO_GRP As String = "AddAbsToGrp"
    Public Const LTPA_ADD_ABS_TO_GRP_ABS As String = "abs"
    Public Const LTPA_ADD_ABS_TO_GRP_GRP As String = "absGrp"

Public Const LTA_NOTIF_TYPE_BY_ALIAS As String = "GetNotifTypeFromAlias"
    Public Const LTPA_NOTIF_TYPE_BY_ALIAS As String = "alias"

Public Const LTA_RULE_BY_ALIAS As String = "GetRuleFromAlias"
    Public Const LTPA_RULE_BY_ALIAS As String = "alias"

Public Const LTA_NOTIFS_FOR_ABS As String = "GetNotifContainingAbs"
    Public Const LTPA_NOTIFS_FOR_ABS_ABS As String = "abs"
    Public Const LTPA_NOTIFS_FOR_ABS_OPEN_ONLY As String = "openOnly"

Public Const LTA_DIS_FOR_ABS As String = "GetDisContainingAbs"
    Public Const LTPA_DIS_FOR_ABS_ABS As String = "abs"
    Public Const LTPA_DIS_FOR_ABS_OPEN_EFF_ONLY As String = "openEffOnly"

Public Const LTA_DIS_FOR_ABS_WITH_DEFERRED As String = "GetDisContainingAbsWithDeferred"
    Public Const LTPA_DIS_FOR_ABS_DEF_ABS As String = "abs"
    Public Const LTPA_DIS_FOR_ABS_DEF_OPEN_EFF_ONLY As String = "openEffOnly"

Public Const LTA_CANCEL_NOTIF As String = "CancelNotif"
    Public Const LTPA_CANCEL_NOTIF As String = "notif"

Public Const LTA_ABS_REPLACED_BY As String = "GetAbsReplacedByAbs"
    Public Const LTPA_ABS_REPLACED_BY_ABS As String = "abs"

Public Const LTA_DIS_ACT_FOR_DIS As String = "GetDisActForDis"
    Public Const LTPA_DIS_ACT_FOR_DIS As String = "dis"

Public Const LTA_ADD_ACT_TO_DIS As String = "AddActToDis"
    Public Const LTPA_ADD_ACT_TO_DIS_DIS As String = "dis"
    Public Const LTPA_ADD_ACT_TO_DIS_ACT_TYPE As String = "disActType"
    Public Const LTPA_ADD_ACT_TO_DIS_EFF_DATE As String = "effDate"
    Public Const LTPA_ADD_ACT_TO_DIS_NOTES As String = "notes"

Public Const LTA_ADD_DIS As String = "AddDis"
    Public Const LTPA_ADD_DIS_EMP As String = "emp"
    Public Const LTPA_ADD_DIS_RULE As String = "rule"
    Public Const LTPA_ADD_DIS_ABS_GRP As String = "absGrp"

Public Const LTA_GET_ALL_DIS_TYPES As String = "GetAllDisTypes"

Public Const LTA_GET_ALL_DIS_ACT_TYPES As String = "GetAllDisActTypes"

Public Const LTA_SET_ADMIN_RIGHT As String = "SetAdminRight"
    Public Const LTPA_SET_ADMIN_RIGHT_USER As String = "user"
    Public Const LTPA_SET_ADMIN_RIGHT_TO As String = "canAdmin"

Public Const LTA_PROXIES_FOR_USER As String = "GetProxiesForUser"
    Public Const LTPA_PROXIES_FOR_USER As String = "user"

Public Const LTA_SET_PROXY As String = "SetProxy"
    Public Const LTPA_SET_PROXY_ACTING As String = "userActing"
    Public Const LTPA_SET_PROXY_ACT_AS As String = "userToActAs"
    Public Const LTPA_SET_PROXY_CAN_ACT As String = "canAct"

Public Const LTA_PROXYABLE_BY_USER As String = "GetUsersProxyableAs"
    Public Const LTPA_PROXYABLE_BY_USER As String = "user"

Public Const LTA_VIEWABLE_BY_SPEC_USER As String = "GetEmpsSpecUserCanView"
    Public Const LTPA_VIEWABLE_BY_SPEC_USER As String = "user"

Public Const LTA_ALTERABLE_BY_SPEC_USER As String = "GetEmpsSpecUserCanAlter"
    Public Const LTPA_ALTERABLE_BY_SPEC_USER As String = "user"

Public Const LTA_WATCHED_BY_SPEC_USER As String = "GetEmpsSpecUserIsWatching"
    Public Const LTPA_WATCHED_BY_SPEC_USER As String = "user"

Public Const LTA_SET_WATCH As String = "SetWatch"
    Public Const LTPA_SET_WATCH_USER As String = "user"
    Public Const LTPA_SET_WATCH_EMP As String = "emp"
    Public Const LTPA_SET_WATCH_TO As String = "isWatching"

Public Const LTA_SET_VIEW_RIGHT As String = "SetViewRight"
    Public Const LTPA_SET_VIEW_RIGHT_USER As String = "user"
    Public Const LTPA_SET_VIEW_RIGHT_EMP As String = "emp"
    Public Const LTPA_SET_VIEW_RIGHT_TO As String = "canView"

Public Const LTA_SET_ALTER_RIGHT As String = "SetViewRight"
    Public Const LTPA_SET_ALTER_RIGHT_USER As String = "user"
    Public Const LTPA_SET_ALTER_RIGHT_EMP As String = "emp"
    Public Const LTPA_SET_ALTER_RIGHT_TO As String = "canAlter"

Public Const LTA_GET_CURRENT_USER As String = "GetCurrentUser"

Public Const LTA_ABS_FOR_EMP_WITH_TYPE As String = "GetAbsForEmpWithType"
    Public Const LTPA_ABS_FOR_EMP_WITH_TYPE_EMP  As String = "emp"
    Public Const LTPA_ABS_FOR_EMP_WITH_TYPE_ABS_TYPE As String = "absType"

Public Const LTA_ABS_TYPE_BY_ALIAS As String = "GetAbsTypeByAlias"
    Public Const LTPA_ABS_TYPE_BY_ALIAS As String = "alias"

Public Const LTA_SET_USER_DISABLED As String = "SetUserDisabled"
    Public Const LTPA_SET_USER_DISABLED_USER As String = "user"
    Public Const LTPA_SET_USER_DISABLED_TO As String = "isDisabled"

Public Const LTA_RESET_PASSWORD As String = "ResetPassword"
    Public Const LTPA_RESET_PASSWORD_USER As String = "user"
    Public Const LTPA_RESET_PASSWORD_TO As String = "newPassword"

Public Const LTA_CHANGE_PASSWORD As String = "ChangePassword"
    Public Const LTPA_CHANGE_PASSWORD_FROM As String = "oldPassword"
    Public Const LTPA_CHANGE_PASSWORD_TO As String = "newPassword"

Public Const LTA_SET_USER_NAMES As String = "SetUserNames"
    Public Const LTPA_SET_USER_NAMES_USER As String = "user"
    Public Const LTPA_SET_USER_NAMES_USERNAME As String = "username"
    Public Const LTPA_SET_USER_NAMES_DISPNAME As String = "displayName"
    Public Const LTPA_SET_USER_NAMES_SORTNAME As String = "sortName"

Public Const LTA_SET_ALTER_WATCHES_RIGHT As String = "SetAlterWatchesRight"
    Public Const LTPA_SET_ALTER_WATCHES_RIGHT_USER As String = "user"
    Public Const LTPA_SET_ALTER_WATCHES_RIGHT_TO As String = "canAlter"

Public Const LTA_ABS_FOR_EMP As String = "GetAbsForEmp"
    Public Const LTPA_ABS_FOR_EMP_EMP As String = "emp"
    Public Const LTPA_ABS_FOR_EMP_SINCE_DATE As String = "sinceDate"
    Public Const LTPA_ABS_FOR_EMP_INC_PROTECTED As String = "incProtected"
    Public Const LTPA_ABS_FOR_EMP_INC_UNPROTECTED  As String = "incUnprotected"
    Public Const LTPA_ABS_FOR_EMP_INC_WORKED  As String = "incWorked"
    Public Const LTPA_ABS_FOR_EMP_INC_UNCLASSIFIED  As String = "incUnclassified"

Public Const LTA_DIS_FOR_EMP As String = "GetDisForEmp"
    Public Const LTPA_DIS_FOR_EMP_EMP As String = "emp"
    Public Const LTPA_DIS_FOR_EMP_INC_OPEN As String = "incOpen"
    Public Const LTPA_DIS_FOR_EMP_INC_EFFECTIVE  As String = "incEffective"
    Public Const LTPA_DIS_FOR_EMP_INC_CANCELLED  As String = "incCancelled"
    Public Const LTPA_DIS_FOR_EMP_INC_WAIVED  As String = "incWaived"
    Public Const LTPA_DIS_FOR_EMP_INC_DEFERRED  As String = "incWaived"

Public Const LTA_GET_ABS_TO_REPLACE As String = "GetAbsToReplace"

Public Const LTA_GET_ABS_TYPES_FOR_ABS_TO_REPL As String = "GetAbsTypesForAbsToReplace"
    Public Const LTPA_GET_ABS_TYPES_FOR_ABS_TO_REPL_ABS_TO_REPL As String = "absToRepl"

Public Const LTA_SET_ABS_TO_REPL_PROCD As String = "SetAbsToReplaceProcessed"
    Public Const LTPA_SET_ABS_TO_REPL_PROCD_EMP As String = "emp"
    Public Const LTPA_SET_ABS_TO_REPL_PROCD_DATE As String = "date"

Public Const LTA_GET_OPEN_DIS_TRIGGERED_SINCE As String = "GetOpenDisTriggeredSince"
    Public Const LTPA_GET_OPEN_DIS_TRIGGERED_SINCE As String = "sinceDate"

Public Const LTA_GET_OPEN_NOTIF_TRIGGERED_SINCE As String = "GetOpenNotifTriggeredSince"
    Public Const LTPA_GET_OPEN_NOTIF_TRIGGERED_SINCE As String = "sinceDate"

Public Const LTA_SET_WATCH_PREF As String = "SetWatchPref"
    Public Const LTPA_SET_WATCH_PREF_USER  As String = "user"
    Public Const LTPA_SET_WATCH_PREF_AREA_NUM As String = "areaNum"
    Public Const LTPA_SET_WATCH_PREF_IS_WATCHING As String = "isWatching"

Public Const LTA_GET_WATCH_PREFS_FOR_USER As String = "GetWatchPrefsForUser"
    Public Const LTPA_GET_WATCH_PREFS_FOR_USER  As String = "user"

Public Const LTA_REGEN_WATCH_PREFS_FOR_USER As String = "RegenWatchPrefsForUser"
    Public Const LTPA_REGEN_WATCH_PREFS_FOR_USER  As String = "user"

Public Const LTA_GET_FMLA_FOR_EMP As String = "GetFMLAForEmp"
    Public Const LTPA_GET_FMLA_FOR_EMP As String = "emp"

Public Const LTA_GET_ABS_CAL As String = "GetAbsCalendar"
    Public Const LTPA_GET_ABS_CAL_EMP As String = "emp"
    Public Const LTPA_GET_ABS_CAL_FROM_DATE As String = "fromDate"
    Public Const LTPA_GET_ABS_CAL_TO_DATE As String = "toDate"

Public Const LTA_GET_EXTENDED_INFO_FOR_EMP As String = "GetExtendedEmpInfoByEmp"
    Public Const LTPA_GET_EXTENDED_INFO_FOR_EMP As String = "emp"

Public Const LTA_GET_DAYS_WORKED As String = "GetDaysWorkedForEmp"
    Public Const LTPA_GET_DAYS_WORKED_EMP As String = "emp"
    Public Const LTPA_GET_DAYS_WORKED_FROM_DATE As String = "fromDate"
    Public Const LTPA_GET_DAYS_WORKED_TO_DATE As String = "toDate"

Public Const LTA_GET_RANDOM_NOTIFS As String = "GetRandNotifSample"
    Public Const LTA_GET_RANDOM_NOTIFS_FROM_DATE As String = "fromDate"
    Public Const LTA_GET_RANDOM_NOTIFS_TO_DATE As String = "toDate"

Public Const LTA_GET_DIS_RELATED_TO_NOTIF As String = "GetDisRelatedToNotif"
    Public Const LTPA_GET_DIS_RELATED_TO_NOTIF As String = "notif"

Public Const LTA_GET_SUMM_ABS_TO_REPL As String = "GetSummAbsToRepl"

Public Const LTA_GET_ABS_TO_REPL_IN_RANGE As String = "GetSummAbsToRepl"
    Public Const LTPA_GET_ABS_TO_REPL_IN_RANGE_LOW As String = "lowNum"
    Public Const LTPA_GET_ABS_TO_REPL_IN_RANGE_HIGH As String = "lowNum"

Public Const LTA_OPEN_EXT_NOTIF As String = "GetOpenExtNotif"
    Public Const LTPA_OPEN_EXT_NOTIF_SINCE_DATE As String = "sinceDate"

Public Const LTA_OPEN_EXT_NOTIF_FOR_WATCHED As String = "GetOpenExtNotifForWatchedEmps"

Public Const LTA_GET_ALL_SEC_OVERRIDES As String = "GetAllSecOverrides"
    Public Const LTPA_GET_ALL_SEC_OVERRIDES_INCL_INACTIVE As String = "inclInactive"

Public Const LTA_ADD_SEC_OVERRIDE As String = "AddSecOverride"
    Public Const LTPA_ADD_SEC_OVERRIDE_USER As String = "user"
    Public Const LTPA_ADD_SEC_AREA_NUM As String = "areaNum"
    Public Const LTPA_ADD_SEC_CAN_VIEW As String = "canView"
    Public Const LTPA_ADD_SEC_CAN_ALTER As String = "canAlter"

Public Const LTA_DELETE_SEC_OVERRIDE As String = "DeleteSecOverride"
    Public Const LTPA_DELETE_SEC_OVERRIDE As String = "secOverride"

Public Const LTA_GET_ALL_USERS As String = "GetAllUsers"

Public Const LTA_SET_USER_TKS_NAME As String = "SetUserTKSName"
    Public Const LTPA_SET_USER_TKS_NAME_USER As String = "user"
    Public Const LTPA_SET_USER_TKS_NAME_TO As String = "tksUserName"

Public Const LTA_GET_EXT_WATCH_PREFS_FOR_USER As String = "GetExtWatchPrefsForUser"
    Public Const LTPA_GET_EXT_WATCH_PREFS_FOR_USER As String = "user"

Public Const LTA_GET_RECENT_EXT_ABS_FOR_USER = "GetRecentExtAbsForUser"
    Public Const LTPA_RECENT_EXT_ABS_FOR_USER_SINCE_DATE = "sinceDate"
    Public Const LTPA_RECENT_EXT_ABS_FOR_USER_INC_PROTECTED = "incProtected"
    Public Const LTPA_RECENT_EXT_ABS_FOR_USER_INC_UNPROTECTED = "incUnprotected"

Public Const LTA_GET_EXT_ABS_IN_ABS_GRP = "GetExtAbsInAbsGrp"
    Public Const LTPA_GET_EXT_ABS_IN_ABS_GRP = "absGrp"

Public Const LTA_GET_EMPS_BY_NAME = "GetEmpsByName"
    Public Const LTPA_GET_EMPS_BY_NAME = "lastName"

Public Const LTA_GET_EXT_INFO_FOR_NOTIF = "GetExtInfoForNotif"
    Public Const LTPA_GET_EXT_INFO_FOR_NOTIF = "notif"

Public Const LTA_SET_EMAIL_OPTIONS = "SetEmailOptions"
    Public Const LTPA_SET_EMAIL_OPTIONS_USER = "user"
    Public Const LTPA_SET_EMAIL_OPTIONS_ENABLED = "isEnabled"
    Public Const LTPA_SET_EMAIL_OPTIONS_ADDRESS = "emailAddress"
    Public Const LTPA_SET_EMAIL_OPTIONS_NOTIF_DAYS = "notifDayThreshold"
    Public Const LTPA_SET_EMAIL_OPTIONS_DIS_DAYS = "disDayThreshold"

Public Const LTA_ADD_USER = "AddUser"
    Public Const LTPA_ADD_USER_USERNAME = "userName"
    Public Const LTPA_ADD_USER_DISPLAY_NAME = "displayName"
    Public Const LTPA_ADD_USER_SORT_NAME = "sortName"
    Public Const LTPA_ADD_USER_USER_TYPE = "userType"
    Public Const LTPA_ADD_USER_INITIAL_PASSWORD = "initialPassword"

Public Const LTA_ADD_TYPE_TO_ABS_WITH_MINUTES As String = "AddTypeToAbsWithMinutes"
    Public Const LTPA_ADD_TYPE_TO_ABS_WITH_MINUTES_ABS As String = "abs"
    Public Const LTPA_ADD_TYPE_TO_ABS_WITH_MINUTES_ABS_TYPE As String = "absType"
    Public Const LTPA_ADD_TYPE_TO_ABS_WITH_MINUTES_MINUTES As String = "minutes"

Public Const LTA_GET_ABS_TYPES_FOR_ABS_WITH_MINUTES As String = "GetAbsTypesForAbsWithMinutes"
    Public Const LTPA_GET_ABS_TYPES_FOR_ABS_WITH_MINUTES_ABS As String = "abs"
