GRANT EXECUTE ON SP_RIDERSHIP_2007_MBTA TO EXECUTE_MBTA_STORED_PROCEDURES;

GRANT EXECUTE ON SP_RIDERSHIP_2007_MBTA TO RIGHTS_TO_MBTA_PROCEDURES;

GRANT EXECUTE ON SP_OUTPUT_MBTA TO EXECUTE_MBTA_STORED_PROCEDURES;

GRANT EXECUTE ON SP_OUTPUT_MBTA TO RIGHTS_TO_MBTA_PROCEDURES
/
