SELECT 1 APERE_P_ENT_SEQ,
--DECODE(ARR_ENTERPRISE_CODE,'GAS','GAS','CEL','ELECTRIC CHOICE','CGA','GAS CHOICE','ELECTRIC')  APERE_P_ENTERPRISE_CODE,
DECODE(ARR_ENTERPRISE_CODE,'GAS','GAS',
                           'CGA','GAS CHOICE LDC(Buy Sell)',
                           'CEL','ELECTRIC CHOICE LDC(Non Buy Sell)',
                           'EAS','EASMENT',
                           'ECE','ELECTRIC CHOICE ENERGY(Non Buy Sell)',
                           'GCE','GAS CHOICE ENERGY(Buy Sell)',
                           'ELECTRIC')  APERE_P_ENTERPRISE_CODE,
DECODE(ARR_ACCT_TYPE,'RES','RESIDENTIAL','NON-RESIDENTIAL')  APERE_P_ACCT_TYPE,
ARR_PROFILE_CATEGORY  APERE_P_PROFILE_CATEGORY,
-- '('||DECODE(ARR_ENTERPRISE_CODE,'GAS','GAS','CEL','ELECTRIC CHOICE','CGA','GAS CHOICE','ELECTRIC')||')' APERE_P_ENTERPRISE_CODE1,
'('|| DECODE(ARR_ENTERPRISE_CODE,'GAS','GAS',
                           'CGA','GAS CHOICE LDC(Buy Sell)',
                           'CEL','ELECTRIC CHOICE LDC(Non Buy Sell)',
                           'EAS','EASMENT',
                           'ECE','ELECTRIC CHOICE ENERGY(Non Buy Sell)',
                           'GCE','GAS CHOICE ENERGY(Buy Sell)',
                           'ELECTRIC') ||')' APERE_P_ENTERPRISE_CODE1,
'('||DECODE(ARR_ACCT_TYPE,'RES','RESIDENTIAL','NON-RESIDENTIAL') ||')' APERE_P_ACCT_TYPE1,
'('||ARR_PROFILE_CATEGORY||')'  APERE_P_PROFILE_CATEGORY1,
SUM(ARR_ACCOUNT_COUNT) APERE_P_ACCOUNT_COUNT,
SUM(ARR_CURRENT_AMT) APERE_P_CURRENT_AMT,
SUM(ARR_ABAL_30_AMT) APERE_P_30_AMT,
SUM(ARR_ABAL_60_AMT) APERE_P_60_AMT,
SUM(ARR_ABAL_90_AMT) APERE_P_90_AMT,
SUM(ARR_ABAL_OVER_90_AMT) APERE_P_OVER_90_AMT,
SUM(ARR_ABAL_NON_ENERGY_AMT) APERE_P_NON_ENERGY_AMT,
SUM(DECODE(ARR_AGING_CATEGORY,'Accounts with >90 Arrears',ARR_ACCOUNT_COUNT)) A_91, 
SUM(DECODE(ARR_AGING_CATEGORY,'Accounts with 90 Arrears',ARR_ACCOUNT_COUNT))   A_90,
SUM(DECODE(ARR_AGING_CATEGORY,'Accounts with 60 Arrears',ARR_ACCOUNT_COUNT))   A_60,
SUM(DECODE(ARR_AGING_CATEGORY,'Accounts with 30 Arrears',ARR_ACCOUNT_COUNT))   A_30,
SUM(DECODE(ARR_AGING_CATEGORY,'Account with Current',ARR_ACCOUNT_COUNT))         A_CUR
FROM ARREARS_TRANS
WHERE  ARR_ARREAR_TYPE = 'ACTIVE'
GROUP BY
ARR_ENTERPRISE_CODE,
ARR_ACCT_TYPE,
ARR_PROFILE_CATEGORY
UNION ALL
SELECT 2,
'All Enterprises'  APERE_P_ENTERPRISE_CODE,
DECODE(ARR_ACCT_TYPE,'RES','RESIDENTIAL','NON-RESIDENTIAL')  APERE_P_ACCT_TYPE,
ARR_PROFILE_CATEGORY  APERE_P_PROFILE_CATEGORY,
'('||'All Enterprises'||')'  APERE_P_ENTERPRISE_CODE1,
'('||DECODE(ARR_ACCT_TYPE,'RES','RESIDENTIAL','NON-RESIDENTIAL')  ||')' APERE_P_ACCT_TYPE1,
'('||ARR_PROFILE_CATEGORY||')'  APERE_P_PROFILE_CATEGORY1,
SUM(ARR_ACCOUNT_COUNT) APERE_P_ACCOUNT_COUNT,
SUM(ARR_CURRENT_AMT) APERE_P_CURRENT_AMT,
SUM(ARR_ABAL_30_AMT) APERE_P_30_AMT,
SUM(ARR_ABAL_60_AMT) APERE_P_60_AMT,
SUM(ARR_ABAL_90_AMT) APERE_P_90_AMT,
SUM(ARR_ABAL_OVER_90_AMT) APERE_P_OVER_90_AMT,
SUM(ARR_ABAL_NON_ENERGY_AMT) APERE_P_NON_ENERGY_AMT,
SUM(DECODE(ARR_AGING_CATEGORY,'Accounts with >90 Arrears',ARR_ACCOUNT_COUNT)) A_91, 
SUM(DECODE(ARR_AGING_CATEGORY,'Accounts with 90 Arrears',ARR_ACCOUNT_COUNT))   A_90,
SUM(DECODE(ARR_AGING_CATEGORY,'Accounts with 60 Arrears',ARR_ACCOUNT_COUNT))   A_60,
SUM(DECODE(ARR_AGING_CATEGORY,'Accounts with 30 Arrears',ARR_ACCOUNT_COUNT))   A_30,
SUM(DECODE(ARR_AGING_CATEGORY,'Account with Current',ARR_ACCOUNT_COUNT))         A_CUR
FROM ARREARS_TRANS
WHERE  ARR_ARREAR_TYPE = 'ACTIVE'
GROUP BY
ARR_ACCT_TYPE,
ARR_PROFILE_CATEGORY
ORDER BY 1

select * from all_objects where object_name like 'ARREARS_TRANS'      CSBINT.ARREARS_TRANS@RPTS

select * from CSBINT.ARREARS_TRANS@RPTS



 
 
 
 
 
