INSERT INTO DA.CMSTATUS  
select dept_comp_code,CMST_STAT_CODE,CMST_STAT_NAME,CMST_PENDING_TYPE_CODE,CMST_PROCEEDING_FLAG,
  CMST_INCL_FORECAST_FLAG,CMST__IU__CREATE_DATE,CMST__IU__CREATE_USER,CMST__IU__UPDATE_DATE,
  CMST__IU__UPDATE_USER,CMST_PCI_BILLING_FLAG
from
(select distinct dept_comp_code from dept where dept_comp_code not in ('ZZ','01')),
(select CMST_COMP_CODE,CMST_STAT_CODE,CMST_STAT_NAME,CMST_PENDING_TYPE_CODE,CMST_PROCEEDING_FLAG,
  CMST_INCL_FORECAST_FLAG,CMST__IU__CREATE_DATE,CMST__IU__CREATE_USER,CMST__IU__UPDATE_DATE,
  CMST__IU__UPDATE_USER,CMST_PCI_BILLING_FLAG
FROM CMSTATUS
where cmst_comp_code not in ('ZZ')
)

select * from DA.CMSTATUS   