
ALTER TABLE UETD_BUILDERSRI
ADD CONSTRAINT BUILDERSRI_PMPROJECT_FK
    FOREIGN KEY (PROJ_SEQ)
    REFERENCES PMPROJECT_TABLE (PMP_PROJ_ORASEQ)
/

ALTER TABLE UETD_RIDERPARAG
ADD CONSTRAINT RIDERPARAG_PMPROJECT_FK
    FOREIGN KEY (PROJ_SEQ)
    REFERENCES PMPROJECT_TABLE (PMP_PROJ_ORASEQ)
/

ALTER TABLE UETD_PLANDATES
ADD CONSTRAINT PLANDATES_PMPROJECT_FK
    FOREIGN KEY (PROJ_SEQ)
    REFERENCES PMPROJECT_TABLE (PMP_PROJ_ORASEQ)
/

ALTER TABLE UETD_PROJECTRAT
ADD CONSTRAINT PROJECTRAT_PMPROJECT_FK
    FOREIGN KEY (PROJ_SEQ)
    REFERENCES PMPROJECT_TABLE (PMP_PROJ_ORASEQ)
/

ALTER TABLE UETD_PROJECTSTA
ADD CONSTRAINT PROJECTSTA_PMPROJECT_FK
    FOREIGN KEY (PROJ_SEQ)
    REFERENCES PMPROJECT_TABLE (PMP_PROJ_ORASEQ)
/

--UETD_BOND   bp and scmast



/*
ALTER TABLE UETD_EFTPRENOT
ADD CONSTRAINT EFTPRENOT_BPVENDORS_FK
    FOREIGN KEY (COMP_CODE, VEN_CODE)
    REFERENCES BPVENDORS (BPVEN_COMP_CODE, BPVEN_BP_CODE)
/

*/


--TO DISABLE/ENABLE FOREIGN KEY
--ALTER TABLE UETD_BUILDERSRI ENABLE CONSTRAINT BUILDERSRI_PMPROJECT_FK