
  CREATE TABLE "DA1"."DC_JCDETAIL" 
   (	"DC_ROWNUM" NUMBER, 
	"JCDT_HLDBK_RLS_EXCHG_AMT" NUMBER(18,2), 
	"JCDT_WBSV_CODE4" VARCHAR2(10 BYTE), 
	"JCDT_SRC_DESC3" VARCHAR2(30 BYTE), 
	"JCDT_SRC_DESC" VARCHAR2(150 BYTE), 
	"JCDT_DSRC_COMP_CODE" VARCHAR2(2 BYTE), 
	"JCDT_JB_REVISION_NUM" NUMBER(3,0), 
	"JCDT_OVERHEAD_BASE_AMT" NUMBER(18,2), 
	"JCDT_PYJB_BILLING_ADJ_QTY" NUMBER(16,8), 
	"JCDT_CURR_CODE" VARCHAR2(3 BYTE), 
	"JCDT_HOME_DEPT_CODE" VARCHAR2(6 BYTE), 
	"JCDT_EXCHG_OUTBOUND_AMT" NUMBER(18,2), 
	"JCDT_VOU_NUM" NUMBER, 
	"JCDT_NEXT_BILLABLE_STATE" VARCHAR2(1 BYTE), 
	"JCDT_JB_DEFERRAL_REVISION_NUM" NUMBER(3,0), 
	"JCDT_BILL_CODE_UPDATE_FLAG" VARCHAR2(1 BYTE), 
	"JCDT_BILLING_RECALC_ORASEQ" NUMBER(38,0), 
	"JCDT_IB_TRANS_FLAG" VARCHAR2(1 BYTE), 
	"JCDT_OVERHEAD_RATE_OR_PCT" NUMBER(18,2), 
	"JCDT_JB_HLDBK_AMT" NUMBER(18,2), 
	"JCDT_BILLING_RECALC_ORIG_RATE" NUMBER(18,2), 
	"JCDT_BILLING_RECALC_USER" VARCHAR2(30 BYTE), 
	"JCDT_JOB_CTRL_CODE" VARCHAR2(10 BYTE), 
	"JCDT_TRAN_SRC_CODE" VARCHAR2(1 BYTE), 
	"JCDT_WBSV_CODE10" VARCHAR2(10 BYTE), 
	"JCDT_ORIG_UNBILLED_REV_AMT" NUMBER(18,2), 
	"JCDT_JB_DRAW_NUM" NUMBER(6,0), 
	"JCDT_EXCHG_AMT" NUMBER(18,2), 
	"JCDT_ACCRUAL_FLAG" VARCHAR2(1 BYTE), 
	"JCDT_TEMP_DATE" DATE, 
	"JCDT_BILL_CODE" VARCHAR2(35 BYTE), 
	"JCDT_FREEZE_ADJ_LINE_FLAG" VARCHAR2(1 BYTE), 
	"JCDT_IB_OUTBOUND_COST_AMT" NUMBER(18,2), 
	"JCDT_COMP_CODE" VARCHAR2(2 BYTE), 
	"JCDT_CLOSE_STATE" VARCHAR2(1 BYTE), 
	"JCDT_IB_FROM_DEPT_CODE" VARCHAR2(6 BYTE), 
	"JCDT_CREATE_DATE" DATE, 
	"JCDT_POSHP_ORASEQ" NUMBER, 
	"JCDT_WBSV_CODE2" VARCHAR2(10 BYTE), 
	"JCDT_IB_REVENUE_AMT" NUMBER(18,2), 
	"JCDT_WBSV_CODE3" VARCHAR2(10 BYTE), 
	"JCDT_IB_ABOVE_COST_AMT" NUMBER(18,2), 
	"JCDT_PHS_CODE" VARCHAR2(16 BYTE), 
	"JCDT_POST_DATE_CHANGE_DATE" DATE, 
	"JCDT_SCSCH_ORASEQ" NUMBER(38,0), 
	"JCDT_OVERHEAD_BASE_UNIT" NUMBER(18,2), 
	"JCDT_ACC_CODE" VARCHAR2(8 BYTE), 
	"JCDT_BCH_NUM" NUMBER(11,0), 
	"JCDT_HOME_COMP_CODE" VARCHAR2(2 BYTE), 
	"JCDT_CAT_CODE" VARCHAR2(4 BYTE), 
	"JCDT_ADJ_NUM" NUMBER(11,0), 
	"JCDT_PM_CODE" VARCHAR2(30 BYTE), 
	"JCDT_HLDBK_EXCHG_AMT" NUMBER(18,2), 
	"JCDT_NEXT_CLOSE_STATE" VARCHAR2(1 BYTE), 
	"JCDT_UNBILLED_REV_AMT" NUMBER(18,2), 
	"JCDT_HLDBK_AMT" NUMBER(18,2), 
	"JCDT_JOB_CODE" VARCHAR2(10 BYTE), 
	"JCDT_REF_DATE" DATE, 
	"JCDT_SRC_CODE" VARCHAR2(16 BYTE), 
	"JCDT_WBSV_CODE6" VARCHAR2(10 BYTE), 
	"JCDT_REF_DESC" VARCHAR2(150 BYTE), 
	"JCDT_DSRC_BCH_NUM" NUMBER(11,0), 
	"JCDT_AR_INV_NUM" VARCHAR2(11 BYTE), 
	"JCDT_EXCHG_RATE" NUMBER(12,7), 
	"JCDT_NUM" NUMBER(11,0), 
	"JCDT_WBSV_CODE8" VARCHAR2(10 BYTE), 
	"JCDT_SRC_COMM_CODE" VARCHAR2(16 BYTE), 
	"JCDT_USER" VARCHAR2(30 BYTE), 
	"JCDT_POSHP_LINE_NUM" NUMBER, 
	"JCDT_WBSV_CODE5" VARCHAR2(10 BYTE), 
	"JCDT_WBSV_CODE7" VARCHAR2(10 BYTE), 
	"JCDT_ADJUSTMENT_ID_NUM" NUMBER(11,0), 
	"JCDT_VDIST_VOU_NUM" NUMBER(11,0), 
	"JCDT_JB_DEFERRAL_DRAW_NUM" NUMBER(6,0), 
	"JCDT_INV_DATE" DATE, 
	"JCDT_JB_HLDBK_RLS_AMT" NUMBER(18,2), 
	"JCDT_ADJUSTMENT_BCH_NUM" NUMBER(11,0), 
	"JCDT_JOUR_CODE" VARCHAR2(2 BYTE), 
	"JCDT_AMT" NUMBER(18,2), 
	"JCDT_DEPT_CODE" VARCHAR2(6 BYTE), 
	"JCDT_POST_OVERHD_FLAG" VARCHAR2(1 BYTE), 
	"JCDT_UNBILLED_REV_RATE_AMT" NUMBER(19,3), 
	"JCDT_SRC_CODE2" VARCHAR2(16 BYTE), 
	"JCDT_PHS_CTRL_CODE" VARCHAR2(16 BYTE), 
	"JCDT_INV_CODE" VARCHAR2(11 BYTE), 
	"JCDT_WBSV_CODE9" VARCHAR2(10 BYTE), 
	"JCDT_BILLABLE_STATE" VARCHAR2(1 BYTE), 
	"JCDT_POST_DATE" DATE, 
	"JCDT_HLDBK_RLS_AMT" NUMBER(18,2), 
	"JCDT_EXCHG_CURR_CODE" VARCHAR2(3 BYTE), 
	"JCDT_TYPE_CODE" VARCHAR2(1 BYTE), 
	"JCDT_SRC_CODE3" VARCHAR2(16 BYTE), 
	"JCDT_REF_CODE" VARCHAR2(16 BYTE), 
	"JCDT_CAT_CTRL_CODE" VARCHAR2(4 BYTE), 
	"JCDT_SEC_PAY_RUN" VARCHAR2(1 BYTE), 
	"JCDT_DSRC_CODE" VARCHAR2(2 BYTE), 
	"JCDT_JB_CONT_EXCHG_RATE" NUMBER(18,8), 
	"JCDT_INV_NUM" VARCHAR2(11 BYTE), 
	"JCDT_REV_ABOVE_GENERATED_AMT" NUMBER(18,2), 
	"JCDT_BILL_AMT" NUMBER(18,4), 
	"JCDT_BILLING_RECALC_DATE" DATE, 
	"JCDT_UNIT" NUMBER(16,8), 
	"JCDT_INV_BCH_NUM" NUMBER(11,0), 
	"JCDT_WBSV_CODE11" VARCHAR2(10 BYTE), 
	"JCDT_WBSV_CODE12" VARCHAR2(10 BYTE), 
	"JCDT_BILLING_RECALC_ORIG_AMT" NUMBER(18,2), 
	"JCDT_OVERHEAD_RATE_TYPE_CODE" VARCHAR2(1 BYTE), 
	"JCDT_BILL_RATE_TYPE_CODE" VARCHAR2(1 BYTE), 
	"JCDT_WBSV_CODE1" VARCHAR2(10 BYTE), 
	"JCDT_IB_OUTBOUND_LOST_AMT" NUMBER(18,2), 
	"JCDT_DATE_TIME_ENTRY" DATE, 
	"JCDT_WM_CODE" VARCHAR2(2 BYTE), 
	"JCDT_BILL_PCT_OR_RATE" NUMBER(16,8), 
	"JCDT_OBJECT_ORASEQ" NUMBER(38,0), 
	"JCDT_IB_FROM_COMP_CODE" VARCHAR2(2 BYTE), 
	"JCDT_JB_DEFER_BILLING_FLAG" VARCHAR2(1 BYTE), 
	"JCDT_REV_GENERATED_AMT" NUMBER(18,2), 
	"JCDT_ID_NUM" NUMBER(11,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 

  CREATE INDEX "DA1"."IJCDT_BCH_NUM_DC" ON "DA1"."DC_JCDETAIL" ("JCDT_BCH_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 
  CREATE INDEX "DA1"."IJCDT_INV_BCH_NUM_DC" ON "DA1"."DC_JCDETAIL" ("JCDT_INV_BCH_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 
  CREATE INDEX "DA1"."IJCDT_JOB_CODE_DC" ON "DA1"."DC_JCDETAIL" ("JCDT_JOB_CODE", "JCDT_PHS_CODE", "JCDT_CAT_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 
  CREATE INDEX "DA1"."IJCDT_NUM_DC" ON "DA1"."DC_JCDETAIL" ("JCDT_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 
  CREATE INDEX "DA1"."I_COMPJOBPHSCAT_JCDETAIL_DC" ON "DA1"."DC_JCDETAIL" ("JCDT_COMP_CODE", "JCDT_JOB_CODE", "JCDT_PHS_CODE", "JCDT_CAT_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 
  CREATE INDEX "DA1"."I_JCDT_AR_INV_NUM_DC" ON "DA1"."DC_JCDETAIL" ("JCDT_AR_INV_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 
  CREATE INDEX "DA1"."I_JCDT_ID_NUM_DC" ON "DA1"."DC_JCDETAIL" ("JCDT_ID_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 
  CREATE INDEX "DA1"."I_JCDT_INV_NUM_DC" ON "DA1"."DC_JCDETAIL" ("JCDT_INV_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 
  CREATE INDEX "DA1"."I_JCDT_JOB_CAT_DC" ON "DA1"."DC_JCDETAIL" ("JCDT_COMP_CODE", "JCDT_JOB_CODE", "JCDT_CAT_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 
  CREATE INDEX "DA1"."JCDETAIL_BILL_CODE_IDX_DC" ON "DA1"."DC_JCDETAIL" ("JCDT_JOB_CODE", "JCDT_BILL_CODE", "JCDT_COMP_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 
  CREATE INDEX "DA1"."JCDETAIL_UK_DC" ON "DA1"."DC_JCDETAIL" ("JCDT_ADJ_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 
  CREATE INDEX "DA1"."JCDETAIL_VOU_NUM_IDX_DC" ON "DA1"."DC_JCDETAIL" ("JCDT_VOU_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 
